// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop01
{
    public static class AddonNode
    {
        private static FormLink<IAddonNodeGetter> Construct(uint id) => new FormLink<IAddonNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAddonNodeGetter> DLC02FXWorkshopNixieTubeLightAddOn01 => Construct(0xe8e);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopBetaWaveEmitter => Construct(0xc73);
        public static FormLink<IAddonNodeGetter> DLC02MPSMetalGrindSparks01 => Construct(0xbc3);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopTrafficLightYellow => Construct(0xa33);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopTrafficLightRed => Construct(0xa32);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopTrafficLightGreen => Construct(0xa31);
        public static FormLink<IAddonNodeGetter> DLC02MPSWaterSpray01 => Construct(0xa2d);
        public static FormLink<IAddonNodeGetter> DLC02MPSWaterMist01 => Construct(0xa2c);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLight03 => Construct(0x9be);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLight02 => Construct(0x995);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLight01 => Construct(0x994);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightYellow03 => Construct(0x987);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightYellow02 => Construct(0x986);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightRed03 => Construct(0x985);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightRed02 => Construct(0x984);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightPurple03 => Construct(0x983);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightPurple02 => Construct(0x982);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightOrange03 => Construct(0x981);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightOrange02 => Construct(0x980);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightGreen03 => Construct(0x97f);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightGreen02 => Construct(0x97e);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightBlue03 => Construct(0x97d);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightBlue02 => Construct(0x97c);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightYellow => Construct(0x944);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightRed => Construct(0x943);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightPurple => Construct(0x942);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightOrange => Construct(0x941);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightGreen => Construct(0x940);
        public static FormLink<IAddonNodeGetter> LightNodeWorkshopCyclingLightBlue => Construct(0x93f);
    }
}
