// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop01
{
    public static partial class FormList
    {
        private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_Purple => Construct(0xd47);
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_Yellow => Construct(0xd45);
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_Orange => Construct(0xd41);
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_Green => Construct(0xd18);
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_Signs => Construct(0xbd6);
        public static FormLink<IFormListGetter> WorkshopConcreteWalls10 => Construct(0xca1);
        public static FormLink<IFormListGetter> WorkshopConcreteWalls06 => Construct(0xca0);
        public static FormLink<IFormListGetter> WorkshopConcreteWalls04 => Construct(0xc9f);
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_White => Construct(0xbc0);
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_Red => Construct(0xbbf);
        public static FormLink<IFormListGetter> DLC02WorkshopNeonLightLetters01_Blue => Construct(0xafe);
        public static FormLink<IFormListGetter> DLC02WorkshopMenu01Power02NeonLights => Construct(0xad5);
        public static FormLink<IFormListGetter> DLC02WorkshopSmallLetters => Construct(0x975);
        public static FormLink<IFormListGetter> WorkshopConcreteWalls08 => Construct(0x93a);
        public static FormLink<IFormListGetter> DLC02WorkshopSummonedToRelaxObserveCombat => Construct(0x868);
        public static FormLink<IFormListGetter> DLC02WorkshopSummonedToRelaxIgnoreFactions => Construct(0x866);
        public static FormLink<IFormListGetter> DLC02WorkshopCageInsectTamedList => Construct(0x861);
        public static FormLink<IFormListGetter> DLC02WorkshopCageRadstagTamedList => Construct(0x858);
        public static FormLink<IFormListGetter> DLC02WorkshopCageDogTamedList => Construct(0x850);
    }
}
