// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop01
{
    public static partial class SoundMarker
    {
        private static FormLink<ISoundMarkerGetter> Construct(uint id) => new FormLink<ISoundMarkerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISoundMarkerGetter> DLC02VOCArenaCrowdCheerLPmarker => Construct(0xd32);
        public static FormLink<ISoundMarkerGetter> OBJCageTrapBangingSmallmarker => Construct(0xa2a);
        public static FormLink<ISoundMarkerGetter> OBJCageTrapBangingMediummarker => Construct(0xa29);
        public static FormLink<ISoundMarkerGetter> OBJCageTrapBangingLargermarker => Construct(0xa28);
        public static FormLink<ISoundMarkerGetter> OBJCageTrapBangingHumanmarker => Construct(0xa27);
        public static FormLink<ISoundMarkerGetter> DLC02NPCDeathclawCageIdleLooping => Construct(0x806);
    }
}
