// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class Dawnguard
    {
        public static class AcousticSpace
        {
            private static FormLink<IAcousticSpaceGetter> Construct(uint id) => new FormLink<IAcousticSpaceGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IAcousticSpaceGetter> DLC1IntFalmerValleyLargeStoneBossChapel => Construct(0x14c61);
            public static FormLink<IAcousticSpaceGetter> IntVampireCastleGuildhall => Construct(0xf695);
            public static FormLink<IAcousticSpaceGetter> IntDungeonDLC1DarkfallPassageAcousticSpace => Construct(0x18421);
            public static FormLink<IAcousticSpaceGetter> DLC1IntDarkDungeonCave => Construct(0x6b0d);
        }
    }
}
