// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class Dawnguard
{
    public static class Impact
    {
        private static FormLink<IImpactGetter> Construct(uint id) => new FormLink<IImpactGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IImpactGetter> NPCVampireLordFootRunImpact => Construct(0x13775);
        public static FormLink<IImpactGetter> NPCVampireLordFootWalkImpact => Construct(0x13774);
        public static FormLink<IImpactGetter> FXHarkonPush => Construct(0x11f8a);
        public static FormLink<IImpactGetter> NPCDogIdleWhineImpact => Construct(0x1180d);
        public static FormLink<IImpactGetter> NPCDogIdleShakeImpact => Construct(0x11809);
        public static FormLink<IImpactGetter> NPCDogIdleScratchBImpact => Construct(0x11803);
        public static FormLink<IImpactGetter> NPCDogIdleScratchAImpact => Construct(0x11802);
        public static FormLink<IImpactGetter> NPCDogBarkDistantImpact => Construct(0x11801);
        public static FormLink<IImpactGetter> NPCDogAttackPowerImpact => Construct(0x11800);
        public static FormLink<IImpactGetter> NPCDogAttackImpact => Construct(0x117ff);
        public static FormLink<IImpactGetter> NPCDogAggroWarningImpact => Construct(0x117fe);
        public static FormLink<IImpactGetter> NPCDogHuskyIdleWhineImpact => Construct(0x1175b);
        public static FormLink<IImpactGetter> NPCDogHuskyIdleShakeImpact => Construct(0x1175a);
        public static FormLink<IImpactGetter> NPCDogHuskyIdleScratchBImpact => Construct(0x11759);
        public static FormLink<IImpactGetter> NPCDogHuskyIdleScratchAImpact => Construct(0x11758);
        public static FormLink<IImpactGetter> NPCDogHuskyBarkDistantImpact => Construct(0x1174b);
        public static FormLink<IImpactGetter> NPCDogHuskyBarkImpact => Construct(0x11747);
        public static FormLink<IImpactGetter> NPCDogHuskyAttackPowerImpact => Construct(0x116ff);
        public static FormLink<IImpactGetter> NPCDogHuskyAttackImpact => Construct(0x116f0);
        public static FormLink<IImpactGetter> NPCDogHuskyAggroWarningImpact => Construct(0x116e5);
        public static FormLink<IImpactGetter> NPCDogDeathHoundBreatheRunImpact => Construct(0x11680);
        public static FormLink<IImpactGetter> NPCDogDeathHoundBarkImpact => Construct(0x11658);
        public static FormLink<IImpactGetter> NPCDogDeathHoundAttackPowerShortImpact => Construct(0x11657);
        public static FormLink<IImpactGetter> NPCDogDeathHoundAttackPowerImpact => Construct(0x11654);
        public static FormLink<IImpactGetter> NPCDogDeathHoundAttackBImpact => Construct(0x11653);
        public static FormLink<IImpactGetter> NPCDogDeathHoundAttackAImpact => Construct(0x1164d);
        public static FormLink<IImpactGetter> NPCDogDeathHoundBreatheImpact => Construct(0x1160d);
        public static FormLink<IImpactGetter> DLC1SunFireImpact => Construct(0xd9ac);
        public static FormLink<IImpactGetter> NPCArmoredTrollFootFrontWalkImpact => Construct(0x39a2);
        public static FormLink<IImpactGetter> NPCArmoredTrollFootBackWalkImpact => Construct(0x39a1);
        public static FormLink<IImpactGetter> DLC1MAGVampireDrainImpact => Construct(0x1a3fa);
        public static FormLink<IImpactGetter> testMAGLightSpellImpact => Construct(0x15414);
        public static FormLink<IImpactGetter> FXGargoyleFleshImpact => Construct(0x10a29);
        public static FormLink<IImpactGetter> NPCGargoyleFootWalkRImpact => Construct(0xf8a8);
        public static FormLink<IImpactGetter> NPCGargoyleFootWalkLImpact => Construct(0xf8a7);
        public static FormLink<IImpactGetter> NPCHorseSkeletonFootSprintBackImpact => Construct(0xefa9);
        public static FormLink<IImpactGetter> NPCHorseSkeletonFootSprintFrontImpact => Construct(0xefa8);
        public static FormLink<IImpactGetter> NPCHorseSkeletonFootWalkBackImpact => Construct(0xefa7);
        public static FormLink<IImpactGetter> NPCHorseSkeletonFootWalkFrontImpact => Construct(0xefa6);
        public static FormLink<IImpactGetter> WPNBoltVsBounceImpact => Construct(0xd218);
        public static FormLink<IImpactGetter> WPNBoltVsStickImpact => Construct(0xd216);
        public static FormLink<IImpactGetter> BloodSprayImpactBoltInsect => Construct(0xa310);
        public static FormLink<IImpactGetter> BloodSprayImpactBoltAlduin => Construct(0xa30f);
        public static FormLink<IImpactGetter> WPNBoltVsFleshDraugrImpact => Construct(0xa30e);
        public static FormLink<IImpactGetter> WPNBoltVsFleshImpactLG => Construct(0xa30d);
        public static FormLink<IImpactGetter> WPNBoltVsFleshImpact => Construct(0xa30c);
        public static FormLink<IImpactGetter> DLC01MAGSoulRendSpellImpact => Construct(0x7cbf);
    }
}
