// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class Dawnguard
{
    public static class SoundMarker
    {
        private static FormLink<ISoundMarkerGetter> Construct(uint id) => new FormLink<ISoundMarkerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISoundMarkerGetter> AMBDLC1WaterfallMediumLP => Construct(0x14c5b);
        public static FormLink<ISoundMarkerGetter> NPCDurnehviirDeath => Construct(0x14b61);
        public static FormLink<ISoundMarkerGetter> NPCShellBugDeath => Construct(0x145f0);
        public static FormLink<ISoundMarkerGetter> NPCShellBugAlive => Construct(0x145ec);
        public static FormLink<ISoundMarkerGetter> QSTDLC01ElderScrollFinalRead2DLPM => Construct(0x145e8);
        public static FormLink<ISoundMarkerGetter> QSTFalmerBossExplosionSettle2D => Construct(0x145cf);
        public static FormLink<ISoundMarkerGetter> QSTDLC01ElderScrollReadB2D => Construct(0x144e7);
        public static FormLink<ISoundMarkerGetter> QSTDLC01ElderScrollRead2D => Construct(0x13e28);
        public static FormLink<ISoundMarkerGetter> AMBBatsWildernessEncounter => Construct(0x13835);
        public static FormLink<ISoundMarkerGetter> MAGNightCloakBatsOut => Construct(0x13781);
        public static FormLink<ISoundMarkerGetter> MAGNightCloakBatsIn => Construct(0x13780);
        public static FormLink<ISoundMarkerGetter> AMBDLC1WaterfallLargeLP => Construct(0x13339);
        public static FormLink<ISoundMarkerGetter> AMBDLC1WaterfallMedium2DLP => Construct(0x13331);
        public static FormLink<ISoundMarkerGetter> AMBDLC1WaterfallDistant2DLP => Construct(0x13330);
        public static FormLink<ISoundMarkerGetter> AMBDLC1WaterfallLarge2DLP => Construct(0x1332d);
        public static FormLink<ISoundMarkerGetter> QSTDLC01ElderScrollRead2DLPM => Construct(0x12f69);
        public static FormLink<ISoundMarkerGetter> QSTDLC01ElderScrollReadHeavy2D => Construct(0x12f68);
        public static FormLink<ISoundMarkerGetter> AMBBonehawkFlock => Construct(0x12e73);
        public static FormLink<ISoundMarkerGetter> QSTArkngthamzPuzzleSuccessE => Construct(0x12875);
        public static FormLink<ISoundMarkerGetter> QSTArkngthamzPuzzleSuccessD => Construct(0x12874);
        public static FormLink<ISoundMarkerGetter> QSTArkngthamzPuzzleSuccessC => Construct(0x12873);
        public static FormLink<ISoundMarkerGetter> QSTArkngthamzPuzzleSuccessB => Construct(0x12872);
        public static FormLink<ISoundMarkerGetter> QSTArkngthamzPuzzleFail => Construct(0x12861);
        public static FormLink<ISoundMarkerGetter> QSTArkngthamzPuzzleSuccessA => Construct(0x12860);
        public static FormLink<ISoundMarkerGetter> QSTFalmerBossColumnDestruction2D => Construct(0x11e3c);
        public static FormLink<ISoundMarkerGetter> MAGAetherialShieldImpactmarker => Construct(0x11cde);
        public static FormLink<ISoundMarkerGetter> MAGAlterationTelekinesisVampireThrow => Construct(0x119a1);
        public static FormLink<ISoundMarkerGetter> MAGAlterationTelekinesisVampireGrab => Construct(0x119a0);
        public static FormLink<ISoundMarkerGetter> MAGPowersBatsFinishMarker => Construct(0x1199d);
        public static FormLink<ISoundMarkerGetter> AMBSteamSoulCrackHarvest => Construct(0x10fc3);
        public static FormLink<ISoundMarkerGetter> AMBSteamCrackSoulCairnWhispers2DLP => Construct(0x10fa1);
        public static FormLink<ISoundMarkerGetter> QSTFinalExplosionFalmerBoss2D => Construct(0x10f35);
        public static FormLink<ISoundMarkerGetter> FXRumbleFalmerBoss2D => Construct(0x10f33);
        public static FormLink<ISoundMarkerGetter> MAGPowersSupernaturalReflexesOutMarker => Construct(0x10ec5);
        public static FormLink<ISoundMarkerGetter> MAGPowersSupernaturalReflexesInMarker => Construct(0x10ec4);
        public static FormLink<ISoundMarkerGetter> MAGPowersMistformOutMarker => Construct(0x10e0a);
        public static FormLink<ISoundMarkerGetter> MAGPowersMistformInMarker => Construct(0x10e09);
        public static FormLink<ISoundMarkerGetter> QSTWaystoneMagicBarrierLPMDUPLICATE001 => Construct(0xe999);
        public static FormLink<ISoundMarkerGetter> FXSeranaTombDrainLife2D => Construct(0xd838);
        public static FormLink<ISoundMarkerGetter> OBJParagonAmbienceLPM => Construct(0x692e);
        public static FormLink<ISoundMarkerGetter> QSTSeranaTombMagicAmbience2D => Construct(0x692a);
        public static FormLink<ISoundMarkerGetter> QSTSeranaTombBrazierFireLPM => Construct(0x6929);
        public static FormLink<ISoundMarkerGetter> AMBLavaLoLPmarker => Construct(0x513f);
        public static FormLink<ISoundMarkerGetter> AMBLavaHiLPmarker => Construct(0x513e);
        public static FormLink<ISoundMarkerGetter> OBJDwemerGearForge => Construct(0x1aa28);
        public static FormLink<ISoundMarkerGetter> TRPHarvestBloomWarnLPM => Construct(0x1aa24);
        public static FormLink<ISoundMarkerGetter> OBJPipeValveWheelRotateMarker => Construct(0x1a4f4);
        public static FormLink<ISoundMarkerGetter> MAGPowersBatsMarker => Construct(0x19d82);
        public static FormLink<ISoundMarkerGetter> FXExplosionIceDragonExitMonoDUPLICATE001 => Construct(0x19cb0);
        public static FormLink<ISoundMarkerGetter> FXExplosionIceDragonExit2DDUPLICATE001 => Construct(0x19caf);
        public static FormLink<ISoundMarkerGetter> FXExplosionIceDragonDiveMonoDUPLICATE001 => Construct(0x19cae);
        public static FormLink<ISoundMarkerGetter> FXExplosionIceDragonDive2DDUPLICATE001 => Construct(0x19cad);
        public static FormLink<ISoundMarkerGetter> AMBWayshrinePortalOpenLP => Construct(0x1920b);
        public static FormLink<ISoundMarkerGetter> QSTSoulCairnPortalOpenMonoExtLP => Construct(0x19208);
        public static FormLink<ISoundMarkerGetter> QSTSoulCairnPortalOpenExtLP => Construct(0x19207);
        public static FormLink<ISoundMarkerGetter> AMBSoulCairnTowerRocksCLPmarker => Construct(0x18b6b);
        public static FormLink<ISoundMarkerGetter> AMBSoulCairnTowerRocksBLPmarker => Construct(0x18b6a);
        public static FormLink<ISoundMarkerGetter> AMBSoulCairnTowerRocksALPmarker => Construct(0x18b69);
        public static FormLink<ISoundMarkerGetter> AMBSoulCairnCraterSteamBLPMarker => Construct(0x178b7);
        public static FormLink<ISoundMarkerGetter> AMBSoulCairnCraterSteamALPMarker => Construct(0x178b6);
        public static FormLink<ISoundMarkerGetter> QSTBridgeBreak => Construct(0x175e0);
        public static FormLink<ISoundMarkerGetter> AMBWeatherLightningPre => Construct(0x142cc);
        public static FormLink<ISoundMarkerGetter> AMBRopeBridgeCreaking => Construct(0x141f0);
        public static FormLink<ISoundMarkerGetter> AMBrIceWallCracking => Construct(0x141ae);
        public static FormLink<ISoundMarkerGetter> AMBrIceLakeCracking => Construct(0x13f15);
        public static FormLink<ISoundMarkerGetter> FXFireFlameStart => Construct(0x13f0e);
        public static FormLink<ISoundMarkerGetter> AMBWaterCoastRocksLP => Construct(0xd245);
        public static FormLink<ISoundMarkerGetter> AMBSoulCairnWall2DLP => Construct(0xa2d6);
        public static FormLink<ISoundMarkerGetter> AMBSteamCrackSoulCairn2DLP => Construct(0xa2cf);
        public static FormLink<ISoundMarkerGetter> AMBEvernightCryptRumble => Construct(0xa261);
        public static FormLink<ISoundMarkerGetter> DLC1AMBWaterRapidsMedium2DLP => Construct(0x6b1e);
    }
}
