// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class AddonNode
    {
        private static FormLink<IAddonNodeGetter> Construct(uint id) => new FormLink<IAddonNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAddonNodeGetter> DLC03_RedEyeLightAddOn => Construct(0x56a1d);
        public static FormLink<IAddonNodeGetter> DLC03_NucleusYellowLight01MED => Construct(0x54549);
        public static FormLink<IAddonNodeGetter> DLC03_NucleusYellowLight01 => Construct(0x54548);
        public static FormLink<IAddonNodeGetter> DLC03_MPSMistNearLg => Construct(0x4e06c);
        public static FormLink<IAddonNodeGetter> DLC03MPSMistLg => Construct(0x4e06b);
        public static FormLink<IAddonNodeGetter> DLC03_MPSAnglerSpitImpact01 => Construct(0x49ba4);
        public static FormLink<IAddonNodeGetter> DLC03_AnglerHeadLampGlowFillLight => Construct(0x4872d);
        public static FormLink<IAddonNodeGetter> DLC03_AnglerHeadLampLight => Construct(0x48729);
        public static FormLink<IAddonNodeGetter> DLC03ConsoleHeadGearLightDUPLICATE000 => Construct(0x4332f);
        public static FormLink<IAddonNodeGetter> DLC03VRRetrieverFXAttach => Construct(0x42fcb);
        public static FormLink<IAddonNodeGetter> DLC03_MPSMistNear => Construct(0x3fe24);
        public static FormLink<IAddonNodeGetter> DLC03_MPSCondensorCore => Construct(0x3fe23);
        public static FormLink<IAddonNodeGetter> DLC03_MPSCondensorShocks => Construct(0x3fe22);
        public static FormLink<IAddonNodeGetter> DLC03_LightSubMissileFlashFill => Construct(0x2f312);
        public static FormLink<IAddonNodeGetter> DLC03_LightSubMissileFlash => Construct(0x2f30f);
        public static FormLink<IAddonNodeGetter> DLC03_LightSubMissileTail => Construct(0x2f30e);
        public static FormLink<IAddonNodeGetter> DLC03_MPSVRBeamMuz => Construct(0x2f02b);
        public static FormLink<IAddonNodeGetter> DLC03_MPSWaveIntro => Construct(0x124d0);
        public static FormLink<IAddonNodeGetter> DLC03_MPSWaveSmallSplash => Construct(0x11b7b);
        public static FormLink<IAddonNodeGetter> DLC03_MPSWaveSplash01 => Construct(0x11b5f);
        public static FormLink<IAddonNodeGetter> DLC03_VimQuartz => Construct(0xa2c8);
        public static FormLink<IAddonNodeGetter> DLC03_VimRefresh => Construct(0xa2c7);
        public static FormLink<IAddonNodeGetter> DLC03_VimCaptainsBlendGlow => Construct(0xa2c4);
        public static FormLink<IAddonNodeGetter> DLC03_MPSMistUpper => Construct(0x46ef);
        public static FormLink<IAddonNodeGetter> DLC03MPSMist01 => Construct(0x46ec);
    }
}
