// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class AnimationSoundTagSet
    {
        private static FormLink<IAnimationSoundTagSetGetter> Construct(uint id) => new FormLink<IAnimationSoundTagSetGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCWolfATS => Construct(0x5d71c);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCHermitCrabATS => Construct(0x5d674);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCVRDefenderTurretATS => Construct(0x5d669);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCGulperATS => Construct(0x56651);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCAnglerATS => Construct(0x544f3);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCChickenATS => Construct(0x515af);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCDataRetrieverATS => Construct(0x515ae);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCDataRetrieverATSDEL => Construct(0x515ad);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCFogCrawlerATS => Construct(0x4b473);
        public static FormLink<IAnimationSoundTagSetGetter> DLC03NPCRobotRobobrainATS => Construct(0x4b472);
    }
}
