// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class ArtObject
    {
        private static FormLink<IArtObjectGetter> Construct(uint id) => new FormLink<IArtObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IArtObjectGetter> DLC03WorkshopStructuresBarnMiscIcon => Construct(0x5d71b);
        public static FormLink<IArtObjectGetter> DLC03WorkshopStructuresBarnFloorIcon => Construct(0x5d71a);
        public static FormLink<IArtObjectGetter> DLC03WorkshopStructuresBarnWallIcon => Construct(0x5d719);
        public static FormLink<IArtObjectGetter> DLC03WorkshopStructuresBarnPrefabsIcon => Construct(0x5d40d);
        public static FormLink<IArtObjectGetter> DLC03WorkshopStructuresBarnIcon => Construct(0x5d0f0);
        public static FormLink<IArtObjectGetter> DLC03MirelurkRedEyeFX => Construct(0x56a1a);
        public static FormLink<IArtObjectGetter> DLC03AnglerFXAddons => Construct(0x48728);
        public static FormLink<IArtObjectGetter> DLC03DataRetrieverFXAO => Construct(0x43659);
        public static FormLink<IArtObjectGetter> DLC03ScreenDistort => Construct(0x1806e);
        public static FormLink<IArtObjectGetter> DLC03VRWorkshopIcon02 => Construct(0x750c);
        public static FormLink<IArtObjectGetter> DLC03VRWorkshopCategoryIcon01 => Construct(0x750b);
    }
}
