// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static partial class AttractionRule
    {
        private static FormLink<IAttractionRuleGetter> Construct(uint id) => new FormLink<IAttractionRuleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAttractionRuleGetter> DLC03VRObjectRule => Construct(0x385b);
    }
}
