// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class BodyPartData
    {
        private static FormLink<IBodyPartDataGetter> Construct(uint id) => new FormLink<IBodyPartDataGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBodyPartDataGetter> DLC03_TurretDefenderBodyPartData => Construct(0x4e774);
        public static FormLink<IBodyPartDataGetter> DLC03_RadChickenBodyPartData => Construct(0x3fd67);
        public static FormLink<IBodyPartDataGetter> DLC03_MutatedWolfBodyPartData => Construct(0x3ec80);
        public static FormLink<IBodyPartDataGetter> DLC03_RadRabbitBodyPartData => Construct(0x3dddf);
        public static FormLink<IBodyPartDataGetter> DLC03_GulperBodyPartData => Construct(0x37b67);
        public static FormLink<IBodyPartDataGetter> DLC03RoboBrainBodyPartData => Construct(0x3673f);
        public static FormLink<IBodyPartDataGetter> DLC03_HermitCrabBodyPartData => Construct(0x21c19);
        public static FormLink<IBodyPartDataGetter> DLC03_FogCrawlerPartData => Construct(0x19d3d);
        public static FormLink<IBodyPartDataGetter> DLC03_AnglerBodyPartData => Construct(0xfeed);
    }
}
