// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class Book
    {
        private static FormLink<IBookGetter> Construct(uint id) => new FormLink<IBookGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBookGetter> DLC03CoA_FFNucleus03_MaiRepairNote => Construct(0x5711d);
        public static FormLink<IBookGetter> DLC03CoA_HCNote_Division => Construct(0x54258);
        public static FormLink<IBookGetter> DLC03_POIVimDriverNote01 => Construct(0x54226);
        public static FormLink<IBookGetter> DLC03_ADV001Note01 => Construct(0x54216);
        public static FormLink<IBookGetter> DLC03_POICOANote01 => Construct(0x54204);
        public static FormLink<IBookGetter> DLC03_POIRefugeeNote01 => Construct(0x54203);
        public static FormLink<IBookGetter> DLC03_POIBuriedStashNote01 => Construct(0x54200);
        public static FormLink<IBookGetter> DLC03_POIRadiomanNote02 => Construct(0x541ff);
        public static FormLink<IBookGetter> DLC03_POIRadiomanNote01 => Construct(0x541fe);
        public static FormLink<IBookGetter> DLC03AcadiaM04Note => Construct(0x540a4);
        public static FormLink<IBookGetter> DLC03POI04_DummyNote => Construct(0x500a9);
        public static FormLink<IBookGetter> DLC03CoA_MartinNote_ANewLife => Construct(0x4fd1c);
        public static FormLink<IBookGetter> DLC03_ADV004Note => Construct(0x4fd11);
        public static FormLink<IBookGetter> DLC03FarHarborLastPlankNote04 => Construct(0x4fba3);
        public static FormLink<IBookGetter> DLC03FarHarborLastPlankNote03 => Construct(0x4fba2);
        public static FormLink<IBookGetter> DLC03FarHarborLastPlankNote02 => Construct(0x4fba1);
        public static FormLink<IBookGetter> DLC03FarHarborLastPlankNote01 => Construct(0x4fba0);
        public static FormLink<IBookGetter> DLC03FarHarborMitchWarningNote => Construct(0x4fb9d);
        public static FormLink<IBookGetter> DLC03FarHarborAveryNote => Construct(0x4fb9b);
        public static FormLink<IBookGetter> DLC03FarHarborAllenNote => Construct(0x4fb99);
        public static FormLink<IBookGetter> DLC03FarHarborTeddyNote => Construct(0x4fb97);
        public static FormLink<IBookGetter> DLC03FarHarborBerthaNote => Construct(0x4fb95);
        public static FormLink<IBookGetter> DLC03POI04_ElizaFamilyNote => Construct(0x4faea);
        public static FormLink<IBookGetter> DLC03POI04_ElizaJournal07 => Construct(0x4fae8);
        public static FormLink<IBookGetter> DLC03_PerkMagIslandersAlmanac05 => Construct(0x4ef94);
        public static FormLink<IBookGetter> DLC03_PerkMagIslandersAlmanac04 => Construct(0x4ef92);
        public static FormLink<IBookGetter> DLC03_PerkMagIslandersAlmanac03 => Construct(0x4ef8f);
        public static FormLink<IBookGetter> DLC03_PerkMagIslandersAlmanac02 => Construct(0x4ef8d);
        public static FormLink<IBookGetter> DLC03_PerkMagIslandersAlmanac01 => Construct(0x4ef8b);
        public static FormLink<IBookGetter> DLC03_POI_Note => Construct(0x4eb5d);
        public static FormLink<IBookGetter> DLC03POI04_ElizaJournal06 => Construct(0x4e983);
        public static FormLink<IBookGetter> DLC03POI04_ElizaJournal05 => Construct(0x4e982);
        public static FormLink<IBookGetter> DLC03POI04_ElizaJournal04 => Construct(0x4e981);
        public static FormLink<IBookGetter> DLC03POI04_ElizaJournal03 => Construct(0x4e980);
        public static FormLink<IBookGetter> DLC03POI04_ElizaJournal02 => Construct(0x4e97f);
        public static FormLink<IBookGetter> DLC03POI04_ElizaJournal01 => Construct(0x4e97e);
        public static FormLink<IBookGetter> DLC03AtomM01_MotherPuzzleNote => Construct(0x4e0b4);
        public static FormLink<IBookGetter> DLC03CoA_Devin_Diary => Construct(0x4dfe5);
        public static FormLink<IBookGetter> DLC03CoA_MaiNote_ThanksSister => Construct(0x4dfd2);
        public static FormLink<IBookGetter> DLC03CoA_HCNote_Unfinished => Construct(0x4dfcd);
        public static FormLink<IBookGetter> DLC03CoA_HCNote_ToRichter => Construct(0x4dfcb);
        public static FormLink<IBookGetter> DLC03POI04_ElizaMapNote => Construct(0x4dbc0);
        public static FormLink<IBookGetter> DLC03POI04_KeyNote => Construct(0x4d21b);
        public static FormLink<IBookGetter> DLC03FarHarborS01_FireBellyRecipe => Construct(0x4b9b4);
        public static FormLink<IBookGetter> DLC03CoA_FFNucleus02_AubertsFarewell => Construct(0x4b347);
        public static FormLink<IBookGetter> DLC03_V118_Part2Note => Construct(0x4b188);
        public static FormLink<IBookGetter> DLC03_V118_KeithsNote => Construct(0x49663);
        public static FormLink<IBookGetter> DLC03_V118_PearlNote => Construct(0x48a2d);
        public static FormLink<IBookGetter> DLC03MarinerWillNote => Construct(0x486c6);
        public static FormLink<IBookGetter> DLC03MarinerSailingGoodbyeNote => Construct(0x486c4);
        public static FormLink<IBookGetter> DLC03_ADV011_Note02 => Construct(0x427cf);
        public static FormLink<IBookGetter> DLC03_ADV011_Note01 => Construct(0x427ce);
        public static FormLink<IBookGetter> DLC03CoA_FFNucleus01_WareBrewRecipe => Construct(0x3e12d);
        public static FormLink<IBookGetter> DLC03MQ03StorageRoomNote => Construct(0x38ed8);
        public static FormLink<IBookGetter> DLC03MQ03CogsNote => Construct(0x38ed5);
        public static FormLink<IBookGetter> DLC03MQ06a_MartinDiary01 => Construct(0x37487);
        public static FormLink<IBookGetter> DLC03MQ06_WindFarmCode => Construct(0x34df6);
        public static FormLink<IBookGetter> DLC03CoA_FFNucleus02_AubertsNote => Construct(0x2c900);
        public static FormLink<IBookGetter> DLC03CoA_FFNucleus02_EdgarsNote => Construct(0x2c8ff);
        public static FormLink<IBookGetter> DLC03CoA_FFNucleus02_HCNote => Construct(0x2c8fe);
        public static FormLink<IBookGetter> DLC03POI10_MotherNote04 => Construct(0x2941b);
        public static FormLink<IBookGetter> DLC03POI10_MotherNote03 => Construct(0x2941a);
        public static FormLink<IBookGetter> DLC03POI10_MotherNote02 => Construct(0x29419);
        public static FormLink<IBookGetter> DLC03POI10_MotherNote01 => Construct(0x29418);
        public static FormLink<IBookGetter> DLC03AtomM01_MotherShrineNote => Construct(0x269c4);
        public static FormLink<IBookGetter> DLC03AtomM01_MotherNote => Construct(0x269aa);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap4Inv => Construct(0x1bc88);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap3Inv => Construct(0x1bc87);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap2Inv => Construct(0x1bc86);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap1Inv => Construct(0x1bc85);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerAssembled => Construct(0x1bc84);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap4 => Construct(0x1bc83);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap3 => Construct(0x1bc82);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap2 => Construct(0x1bc7d);
        public static FormLink<IBookGetter> DLC03_AtomM02_FlyerScrap1 => Construct(0x1bc7c);
        public static FormLink<IBookGetter> ADV012SkeletonsNote => Construct(0x1b79d);
        public static FormLink<IBookGetter> DLC03MQ01KasumiJournal => Construct(0x17e8b);
        public static FormLink<IBookGetter> DLC03MQ01GrandfatherNote => Construct(0x17e85);
        public static FormLink<IBookGetter> DLC03__7_15ShipNote => Construct(0x1087e);
        public static FormLink<IBookGetter> DLC03_9_12Poem => Construct(0xd802);
        public static FormLink<IBookGetter> DLC03MQ01NakanoCase => Construct(0x4f48);
    }
}
