// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static partial class Door
    {
        private static FormLink<IDoorGetter> Construct(uint id) => new FormLink<IDoorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDoorGetter> RoadManholeDoor01NONAME => Construct(0x5d895);
        public static FormLink<IDoorGetter> LadderMetalTall01NONAME => Construct(0x5d894);
        public static FormLink<IDoorGetter> DLC03_AutoloadDoorMinUse => Construct(0x5707e);
        public static FormLink<IDoorGetter> Dlc03BarnDoorSm02 => Construct(0x566c3);
        public static FormLink<IDoorGetter> Dlc03BarnDoorSm01 => Construct(0x566c2);
        public static FormLink<IDoorGetter> Dlc03BarnOuthouseDoor01 => Construct(0x545a3);
        public static FormLink<IDoorGetter> Dlc03BarnOuthouseDoor02 => Construct(0x545a2);
        public static FormLink<IDoorGetter> Dlc03BarnDoorMed02alt => Construct(0x5455b);
        public static FormLink<IDoorGetter> Dlc03BarnDoorMed02 => Construct(0x5455a);
        public static FormLink<IDoorGetter> Dlc03BarnDoorMed01alt => Construct(0x54559);
        public static FormLink<IDoorGetter> Dlc03BarnDoorMed01 => Construct(0x54558);
        public static FormLink<IDoorGetter> DLC03InvisibleLoad01HiddenForQTs => Construct(0x53d20);
        public static FormLink<IDoorGetter> DLC03POI04PowerBoxLidNONAME => Construct(0x4fe17);
        public static FormLink<IDoorGetter> DLC03V118_ElevatorDoorOutPublic => Construct(0x4f3e6);
        public static FormLink<IDoorGetter> VltDoorRes01B_DLC03 => Construct(0x496c1);
        public static FormLink<IDoorGetter> NucleusSubLadder01LoadDoor => Construct(0x3fa1c);
        public static FormLink<IDoorGetter> DLC03_EchoLakeTrapDoorNoName => Construct(0x2bfe8);
        public static FormLink<IDoorGetter> IndMetalDoorHugeRight01a => Construct(0x2880a);
        public static FormLink<IDoorGetter> IndMetalDoorHugeLeft01a => Construct(0x28809);
        public static FormLink<IDoorGetter> BunExtDoor01Load => Construct(0x28808);
        public static FormLink<IDoorGetter> DLC03Vim_IndMetalDoorHugeLeft01 => Construct(0x1fc89);
        public static FormLink<IDoorGetter> DLC03MQ01_SafeDoor01 => Construct(0x17e79);
        public static FormLink<IDoorGetter> BarnDoorMedL02 => Construct(0xe286);
        public static FormLink<IDoorGetter> BarnDoorMedR02 => Construct(0xe285);
        public static FormLink<IDoorGetter> PaintedWoodDoorDouble02_DLC03 => Construct(0xd813);
        public static FormLink<IDoorGetter> PaintedWoodDoorBrokenA02_DLC03 => Construct(0xd810);
        public static FormLink<IDoorGetter> PaintedWoodDoorWinBrokenA02_DLC03 => Construct(0xd80f);
        public static FormLink<IDoorGetter> PaintedWoodDoorBrokenA01_DLC03 => Construct(0xd80e);
        public static FormLink<IDoorGetter> BarnOuthouseDoor02 => Construct(0x9895);
        public static FormLink<IDoorGetter> BarnOuthouseDoor01 => Construct(0x41b5);
        public static FormLink<IDoorGetter> DLC03VRDoor => Construct(0x3af2);
        public static FormLink<IDoorGetter> BarnDoorMedL01 => Construct(0x3a5f);
        public static FormLink<IDoorGetter> BarnDoorMedR01 => Construct(0x3a5d);
        public static FormLink<IDoorGetter> BarnDoorSmR01 => Construct(0x3a5b);
        public static FormLink<IDoorGetter> BarnDoorSmL01 => Construct(0x3a59);
    }
}
