// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static partial class EffectShader
    {
        private static FormLink<IEffectShaderGetter> Construct(uint id) => new FormLink<IEffectShaderGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IEffectShaderGetter> DLC03VRRetrieverFXS => Construct(0x44c85);
        public static FormLink<IEffectShaderGetter> DLC03VRRetriever02FXS => Construct(0x44c84);
        public static FormLink<IEffectShaderGetter> DLC03FogMotherFXS => Construct(0x1563d);
    }
}
