// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static partial class Impact
    {
        private static FormLink<IImpactGetter> Construct(uint id) => new FormLink<IImpactGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IImpactGetter> DLC03NPCFogCrawlerFootRunRImpact => Construct(0x5d9ee);
        public static FormLink<IImpactGetter> DLC03NPCFogCrawlerFootRunLImpact => Construct(0x5d9ed);
        public static FormLink<IImpactGetter> DLC03NPCRadRabbitFootFrontImpact => Construct(0x5d7e4);
        public static FormLink<IImpactGetter> DLC03NPCRadRabbitFootBackImpact => Construct(0x5d7e3);
        public static FormLink<IImpactGetter> DLC03NPCHermitCrabFootWalkCarUpImpact => Construct(0x5d3d4);
        public static FormLink<IImpactGetter> DLC03NPCHermitCrabFootWalkCarDownImpact => Construct(0x5d3d3);
        public static FormLink<IImpactGetter> DLC03NPCHermitCrabFootWalkFrontImpact => Construct(0x5d3d2);
        public static FormLink<IImpactGetter> DLC03NPCHermitCrabFootWalkBackImpact => Construct(0x5d3d1);
        public static FormLink<IImpactGetter> DLC03WPNFatManBowlingBallVsMetalImpact => Construct(0x5d3bb);
        public static FormLink<IImpactGetter> DLC03NPCAnglerFootWalkFrontImpact => Construct(0x5d383);
        public static FormLink<IImpactGetter> DLC03NPCAnglerFootRunBackImpact => Construct(0x5d382);
        public static FormLink<IImpactGetter> DLC03NPCAnglerFootRunFrontImpact => Construct(0x5d381);
        public static FormLink<IImpactGetter> DLC03NPCAnglerFootWalkBackImpact => Construct(0x5d380);
        public static FormLink<IImpactGetter> DLC03NPCDataRetrieverFootRightImpact => Construct(0x5d125);
        public static FormLink<IImpactGetter> DLC03NPCDataRetrieverFootLeftImpact => Construct(0x5d124);
        public static FormLink<IImpactGetter> DLC03PHYMetalBearTrapImpact => Construct(0x5777b);
        public static FormLink<IImpactGetter> DLC03WPNFatManBowlingBallVsWoodImpact => Construct(0x57165);
        public static FormLink<IImpactGetter> DLC03WPNFatManBowlingBallVsFleshImpact => Construct(0x57164);
        public static FormLink<IImpactGetter> DLC03WPNFatManBowlingBallVsDefaultImpact => Construct(0x57163);
        public static FormLink<IImpactGetter> DLC03WPNFatManBowlingBallVsConcreteImpact => Construct(0x57162);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletMetalGasLineSm => Construct(0x5698b);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletInsectFloorImpact => Construct(0x5698a);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletSandbagImpact_noParallax => Construct(0x56989);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletWingImpact => Construct(0x56988);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletConcreteImpact_noParallax => Construct(0x56987);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletDirtImpact_noParallax => Construct(0x56986);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletBloodHeavyImpact => Construct(0x56985);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletBloodClearImpact => Construct(0x56984);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletBlood01GlowImpact => Construct(0x56983);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletImpactFlesh => Construct(0x56628);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletImpactWood => Construct(0x56627);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletImpactMetalPowerArmor => Construct(0x56626);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletImpactMetal => Construct(0x56625);
        public static FormLink<IImpactGetter> DLC03HarpoonBulletImpactGeneric => Construct(0x56624);
        public static FormLink<IImpactGetter> DLC03NPCGulperFootWalkRImpact => Construct(0x4f572);
        public static FormLink<IImpactGetter> DLC03NPCGulperFootSprintRImpact => Construct(0x4f571);
        public static FormLink<IImpactGetter> DLC03NPCGulperFootRunRImpact => Construct(0x4f570);
        public static FormLink<IImpactGetter> DLC03NPCGulperFootWalkLImpact => Construct(0x4f56f);
        public static FormLink<IImpactGetter> DLC03NPCGulperFootSprintLImpact => Construct(0x4f56e);
        public static FormLink<IImpactGetter> DLC03NPCGulperFootRunLImpact => Construct(0x4f56d);
        public static FormLink<IImpactGetter> DLC03PaintballMetalImpact => Construct(0x4da94);
        public static FormLink<IImpactGetter> DLC03PaintballFleshImpact => Construct(0x4da82);
        public static FormLink<IImpactGetter> DLC03EXPPaintballProjectileWhite => Construct(0x4c053);
        public static FormLink<IImpactGetter> DLC03EXPPaintballProjectileOrange => Construct(0x4c052);
        public static FormLink<IImpactGetter> DLC03EXPPaintballProjectileRed => Construct(0x4c051);
        public static FormLink<IImpactGetter> DLC03EXPPaintballProjectileYellow => Construct(0x4c04d);
        public static FormLink<IImpactGetter> DLC03EXPPaintballProjectileGreen => Construct(0x4c049);
        public static FormLink<IImpactGetter> DLC03EXPPaintballProjectileBlue => Construct(0x4c048);
        public static FormLink<IImpactGetter> DLC03NPCChickenFootRWalkImpact => Construct(0x4b9c7);
        public static FormLink<IImpactGetter> DLC03NPCChickenFootLWalkImpact => Construct(0x4b9c6);
        public static FormLink<IImpactGetter> DLC03AnglerSpitImpact => Construct(0x49ba8);
        public static FormLink<IImpactGetter> DLC03NPCFogCrawlerFootWalkRImpact => Construct(0x48719);
        public static FormLink<IImpactGetter> DLC03NPCFogCrawlerFootWalkLImpact => Construct(0x48718);
    }
}
