// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static partial class LeveledNpc
    {
        private static FormLink<ILeveledNpcGetter> Construct(uint id) => new FormLink<ILeveledNpcGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILeveledNpcGetter> DLC03MQ06_LCharGulper => Construct(0x5727d);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharHermitCrab => Construct(0x4b34e);
        public static FormLink<ILeveledNpcGetter> DLC03MQ02_LCharMirelurkHunter => Construct(0x48c07);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharTrapperLegendary => Construct(0x48bb4);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharGulperAmbushLegendary => Construct(0x3fe2d);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharGulperLegendary => Construct(0x3d477);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharTrapper_Boss => Construct(0x27940);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharGulper => Construct(0x2793e);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharMirelurkCrabBoss => Construct(0x23ac7);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharMirelurkCrabAmbushLegendary => Construct(0x23ac6);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharMirelurkCrabLegendary => Construct(0x23ac5);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharMirelurkCrab => Construct(0x23ac2);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharYaoGuaiLegendary => Construct(0x21761);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharYaoGuai => Construct(0x2175e);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharFeralGhoulBoss => Construct(0x1fa99);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharFeralGhoulLegendary => Construct(0x1fa98);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharFeralGhoulAmbushLegendary => Construct(0x1fa97);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharFeralGhoul => Construct(0x1fa96);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharWolfLegendary => Construct(0x140f7);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharWolf => Construct(0x140f6);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharRadStag_Legendary => Construct(0x13f7b);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharRadStag => Construct(0x13f73);
        public static FormLink<ILeveledNpcGetter> DLC03LCharWorkshopNPC => Construct(0x10550);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharFogCrawlerLegendary => Construct(0xa2d3);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharFogCrawler => Construct(0xa2d2);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharAnglerLegendary => Construct(0x958f);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharAngler => Construct(0x9587);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharTrapper => Construct(0x2db8);
        public static FormLink<ILeveledNpcGetter> DLC03_LCharTrapperFace => Construct(0x2dab);
    }
}
