// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class LoadScreen
    {
        private static FormLink<ILoadScreenGetter> Construct(uint id) => new FormLink<ILoadScreenGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILoadScreenGetter> DLC03Armor02MarineWetsuit => Construct(0x4fa80);
        public static FormLink<ILoadScreenGetter> DLC03MQ04VRLoadScreen => Construct(0x37c96);
        public static FormLink<ILoadScreenGetter> DLC03SettlementNucleus04 => Construct(0x2f1c3);
        public static FormLink<ILoadScreenGetter> DLC03SettlementNucleus03 => Construct(0x2f1c2);
        public static FormLink<ILoadScreenGetter> DLC03SettlementAcadia04 => Construct(0x2f1c1);
        public static FormLink<ILoadScreenGetter> DLC03SettlementFarHarbor06 => Construct(0x2f1c0);
        public static FormLink<ILoadScreenGetter> DLC03SettlementFarHarbor05 => Construct(0x2f1bf);
        public static FormLink<ILoadScreenGetter> DLC03SettlementNucleus02 => Construct(0x2f1be);
        public static FormLink<ILoadScreenGetter> DLC03SettlementNucleus01 => Construct(0x2f1bd);
        public static FormLink<ILoadScreenGetter> DLC03SettlementAcadia03 => Construct(0x2f1bc);
        public static FormLink<ILoadScreenGetter> DLC03SettlementAcadia02 => Construct(0x2f1bb);
        public static FormLink<ILoadScreenGetter> DLC03SettlementAcadia01 => Construct(0x2f1ba);
        public static FormLink<ILoadScreenGetter> DLC03SettlementFarHarbor04 => Construct(0x2f1b9);
        public static FormLink<ILoadScreenGetter> DLC03LoreVim01 => Construct(0x2f1b8);
        public static FormLink<ILoadScreenGetter> DLC03SettlementFarHarbor03 => Construct(0x2f1b7);
        public static FormLink<ILoadScreenGetter> DLC03SettlementFarHarbor02_Approach => Construct(0x2f1b6);
        public static FormLink<ILoadScreenGetter> DLC03SettlementFarHarbor01 => Construct(0x2ee34);
        public static FormLink<ILoadScreenGetter> DLC03CreatureGulper => Construct(0x2ee32);
        public static FormLink<ILoadScreenGetter> DLC03CreatureTrappers => Construct(0x2ee31);
        public static FormLink<ILoadScreenGetter> DLC03CreatureWolves => Construct(0x2ee30);
        public static FormLink<ILoadScreenGetter> DLC03CreatureAngler => Construct(0x2ee2f);
        public static FormLink<ILoadScreenGetter> DLC03CreatureFogCrawler => Construct(0x2ee2e);
        public static FormLink<ILoadScreenGetter> DLC03Weapons04Hooks => Construct(0x2ee2d);
        public static FormLink<ILoadScreenGetter> DLC03Weapons03HarpoonGun => Construct(0x2ee2c);
        public static FormLink<ILoadScreenGetter> DLC03Weapons02GammaRifle => Construct(0x2ee2b);
        public static FormLink<ILoadScreenGetter> DLC03Weapons01LeverActionRifle => Construct(0x2ee2a);
        public static FormLink<ILoadScreenGetter> DLC03Armor01MarineCombat => Construct(0x2ee29);
    }
}
