// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class Location
    {
        private static FormLink<ILocationGetter> Construct(uint id) => new FormLink<ILocationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILocationGetter> DLC03POI45Location => Construct(0x567bc);
        public static FormLink<ILocationGetter> DLC03_ZephyrRidgeLocation => Construct(0x54230);
        public static FormLink<ILocationGetter> DLC03_RockPointCampLocation => Construct(0x5422c);
        public static FormLink<ILocationGetter> DLC03_POI_07_Location => Construct(0x53ff1);
        public static FormLink<ILocationGetter> DLC03RayburnPointLocation => Construct(0x53fd5);
        public static FormLink<ILocationGetter> DLC03REHoldingCellLocation => Construct(0x4b68f);
        public static FormLink<ILocationGetter> DLC03RedDeathIslandLocation => Construct(0x48ac1);
        public static FormLink<ILocationGetter> DLC03WindFarmBuildingInteriorLocation => Construct(0x40af9);
        public static FormLink<ILocationGetter> DLC03_POI_40Interior_Location => Construct(0x3a381);
        public static FormLink<ILocationGetter> DLC03SouthwestHarborLocation => Construct(0x399c8);
        public static FormLink<ILocationGetter> DLC03DaltonFarmLocation => Construct(0x38eae);
        public static FormLink<ILocationGetter> DLC03Vault118Location => Construct(0x38ae6);
        public static FormLink<ILocationGetter> DLC03_POI_40_Location => Construct(0x37498);
        public static FormLink<ILocationGetter> DLC03HaddockCoveLocation => Construct(0x316b7);
        public static FormLink<ILocationGetter> DLC03KitteredgePassLocation => Construct(0x258e0);
        public static FormLink<ILocationGetter> DLC03PineCrestCavernLocation => Construct(0x258df);
        public static FormLink<ILocationGetter> DLC03NationalParkCampgroundLocation => Construct(0x247be);
        public static FormLink<ILocationGetter> DLC03NucleusMemoryBanksLocation => Construct(0x2259f);
        public static FormLink<ILocationGetter> DLC03HarborGrandHotelLocation => Construct(0x217d4);
        public static FormLink<ILocationGetter> DLC03LongfellowsCabinLocation => Construct(0x20649);
        public static FormLink<ILocationGetter> DLC03NorthwoodRidgeQuarryLocation => Construct(0x20648);
        public static FormLink<ILocationGetter> DLC03FarHarborWorldLocation => Construct(0x20168);
        public static FormLink<ILocationGetter> DLC03WindFarmBuildingLocation => Construct(0x1fec4);
        public static FormLink<ILocationGetter> DLC03BarHarbourMuseumLocation => Construct(0x1f9f5);
        public static FormLink<ILocationGetter> DLC03_POI_37_Location => Construct(0x1cbe6);
        public static FormLink<ILocationGetter> DLC03_POI_12_Location => Construct(0x1cbe5);
        public static FormLink<ILocationGetter> DLC03_POI_17_Location => Construct(0x169fe);
        public static FormLink<ILocationGetter> DLC03AlderseaDaySpaLocation => Construct(0x16667);
        public static FormLink<ILocationGetter> DLC03KyeBunkerLocation => Construct(0x14143);
        public static FormLink<ILocationGetter> DLC03EaglesCoveTanneryLocation => Construct(0x140e0);
        public static FormLink<ILocationGetter> DLC03FringeCoveDocksLocation => Construct(0x11a83);
        public static FormLink<ILocationGetter> DLC03NationalParkHQLocation => Construct(0x1049f);
        public static FormLink<ILocationGetter> DLC03EmmetsCausewayLocation => Construct(0xf10e);
        public static FormLink<ILocationGetter> DLC03EchoLakeLumberLocation => Construct(0xf101);
        public static FormLink<ILocationGetter> DLC03HorizonFlight1207Location => Construct(0xf044);
        public static FormLink<ILocationGetter> DLC03VimPopFactoryLocation => Construct(0xf043);
        public static FormLink<ILocationGetter> DLC03BeaverCreekLanesLocation => Construct(0xf042);
        public static FormLink<ILocationGetter> DLC03CliffsEdgeHotelLocation => Construct(0xf041);
        public static FormLink<ILocationGetter> DLC03BrookesHeadLighthouseLocation => Construct(0xed4b);
        public static FormLink<ILocationGetter> DLC03AtomShrineLocation => Construct(0xaff9);
        public static FormLink<ILocationGetter> DLC03AtomsSpringLocation => Construct(0xafe2);
        public static FormLink<ILocationGetter> DLC03MSAzaleaLocation => Construct(0xaf72);
        public static FormLink<ILocationGetter> DLC03NationalParkVisitorsCenterLocation => Construct(0x9353);
        public static FormLink<ILocationGetter> DLC03VRLocation => Construct(0x750e);
        public static FormLink<ILocationGetter> DLC03AcadiaLocation => Construct(0x6126);
        public static FormLink<ILocationGetter> DLC03LastPlankLocation => Construct(0x5cb6);
        public static FormLink<ILocationGetter> DLC03FarHarborSettlementLocation => Construct(0x5c79);
        public static FormLink<ILocationGetter> DLC03EdenMeadowsCinemasLocation => Construct(0x4c7c);
        public static FormLink<ILocationGetter> DLC03NucleusLocation => Construct(0x4477);
        public static FormLink<ILocationGetter> DLC03NakanoResidence => Construct(0x220c);
    }
}
