// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class MovableStatic
    {
        private static FormLink<IMovableStaticGetter> Construct(uint id) => new FormLink<IMovableStaticGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMovableStaticGetter> DLC03DiMAMemoryBanks04NoSGON => Construct(0x4dc91);
        public static FormLink<IMovableStaticGetter> DLC03DiMAMemoryBanks03AllON => Construct(0x4dc90);
        public static FormLink<IMovableStaticGetter> DLC03DiMAMemoryBanks02RearON => Construct(0x4dc8f);
        public static FormLink<IMovableStaticGetter> DLC03DiMAMemoryBanks01FrontON => Construct(0x4dc8e);
        public static FormLink<IMovableStaticGetter> DLC03DiMAMemoryBanks00ExposedON => Construct(0x4dc8d);
        public static FormLink<IMovableStaticGetter> DLC03DriveInFX01TexHolder => Construct(0x4d9cc);
        public static FormLink<IMovableStaticGetter> DLC03DriveInFX02TexHolder => Construct(0x4d9c9);
        public static FormLink<IMovableStaticGetter> DLC03MistFXRadCloud => Construct(0x4d8d5);
        public static FormLink<IMovableStaticGetter> SkeletonClothedVaultsuit118 => Construct(0x43a3c);
        public static FormLink<IMovableStaticGetter> DLC03MistFXExpensiveHeavy => Construct(0x4351a);
        public static FormLink<IMovableStaticGetter> Cube96Dissolve03 => Construct(0x3faf1);
        public static FormLink<IMovableStaticGetter> Cube96Dissolve02 => Construct(0x3faf0);
        public static FormLink<IMovableStaticGetter> DLC03SubBaseBun => Construct(0x3ce3e);
        public static FormLink<IMovableStaticGetter> DLC03SubBaseBunDmg => Construct(0x3ce3d);
        public static FormLink<IMovableStaticGetter> DLC03FXDrdRmLgBayDoorExtDmg => Construct(0x38046);
        public static FormLink<IMovableStaticGetter> DLC03FXDrdRmLgBayDoorExt01 => Construct(0x38045);
        public static FormLink<IMovableStaticGetter> DLC03FXAmbWaterFish01 => Construct(0x365eb);
        public static FormLink<IMovableStaticGetter> DLC03FXAmbWaterFish02 => Construct(0x365ea);
        public static FormLink<IMovableStaticGetter> workshop_DLC03_ShackDoorBarricade01Dest => Construct(0x35572);
        public static FormLink<IMovableStaticGetter> workshop_DLC03_ShackWallOuterCap01Door01Dest => Construct(0x3556f);
        public static FormLink<IMovableStaticGetter> workshop_DLC03_ShackWallOuter03Dest => Construct(0x3556e);
        public static FormLink<IMovableStaticGetter> workshop_DLC03_ShackWallHalfR01Dest => Construct(0x3556d);
        public static FormLink<IMovableStaticGetter> workshop_DLC03_ShackWallOuterCap01BDest => Construct(0x35565);
        public static FormLink<IMovableStaticGetter> workshop_DLC03_ShackWallHalfL01Dest => Construct(0x35564);
        public static FormLink<IMovableStaticGetter> workshop_DLC03_ShackWallOuterCap01ADest => Construct(0x35563);
        public static FormLink<IMovableStaticGetter> VirCubeWallMove04 => Construct(0x35251);
        public static FormLink<IMovableStaticGetter> VirCubeWallMove03 => Construct(0x35250);
        public static FormLink<IMovableStaticGetter> VirCubeWallMove02 => Construct(0x3524f);
        public static FormLink<IMovableStaticGetter> VirCubeWallMove01 => Construct(0x35139);
        public static FormLink<IMovableStaticGetter> DataStreamLarge01 => Construct(0x34e83);
        public static FormLink<IMovableStaticGetter> DLC03WindTurbine01 => Construct(0x33e7b);
        public static FormLink<IMovableStaticGetter> VRSkyPulseGlow02 => Construct(0x31422);
        public static FormLink<IMovableStaticGetter> VRSkyPulseGlow => Construct(0x2f544);
        public static FormLink<IMovableStaticGetter> Cube96Dissolve01 => Construct(0x27b88);
        public static FormLink<IMovableStaticGetter> Cube96Stream01 => Construct(0x27b73);
        public static FormLink<IMovableStaticGetter> DLC03ProjectorLightBeam => Construct(0x20d6f);
        public static FormLink<IMovableStaticGetter> DLC03WaterSmallSplash01 => Construct(0x11b7c);
        public static FormLink<IMovableStaticGetter> DLC03WaterFoam03 => Construct(0x11b63);
        public static FormLink<IMovableStaticGetter> DLC03WaterFoam02 => Construct(0x11b62);
        public static FormLink<IMovableStaticGetter> DLC03WaterFoam01B => Construct(0x11b61);
        public static FormLink<IMovableStaticGetter> DLC03WaterFoam01 => Construct(0x11b60);
        public static FormLink<IMovableStaticGetter> DLC03WaterSplash01B => Construct(0x10f0f);
        public static FormLink<IMovableStaticGetter> DLC03WaterSplash03 => Construct(0x10f0e);
        public static FormLink<IMovableStaticGetter> DLC03WaterSplash02 => Construct(0x10f0d);
        public static FormLink<IMovableStaticGetter> DLC03WaterSplash01 => Construct(0xf7ee);
        public static FormLink<IMovableStaticGetter> DLC03_DebugLightSpheres => Construct(0x74f0);
        public static FormLink<IMovableStaticGetter> DLC03_DebugHDRBrightRange01 => Construct(0x74ef);
        public static FormLink<IMovableStaticGetter> DLC03_DebugExternalEmitSpheres => Construct(0x74ee);
        public static FormLink<IMovableStaticGetter> DLC03MistFX1024 => Construct(0x46b3);
        public static FormLink<IMovableStaticGetter> DLC03MistFX512 => Construct(0x465b);
        public static FormLink<IMovableStaticGetter> OilSlickLarge01 => Construct(0x4658);
        public static FormLink<IMovableStaticGetter> TestOilFireRing => Construct(0x2642);
        public static FormLink<IMovableStaticGetter> FireTest => Construct(0x2639);
    }
}
