// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static partial class MusicType
    {
        private static FormLink<IMusicTypeGetter> Construct(uint id) => new FormLink<IMusicTypeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMusicTypeGetter> DLC03MUSFactionChildrenOfAtomdelete => Construct(0x5d13e);
        public static FormLink<IMusicTypeGetter> DLC03MUSFactionChildrenOfAtomNucleus => Construct(0x5d104);
        public static FormLink<IMusicTypeGetter> DLC03MUSVRWorld => Construct(0x5d0da);
        public static FormLink<IMusicTypeGetter> DLC03MUSSpecialDestroyTheNucleus => Construct(0x5710e);
        public static FormLink<IMusicTypeGetter> DLC03MUSFactionChildrenOfAtom => Construct(0x56654);
        public static FormLink<IMusicTypeGetter> DLC03MUSSpecialVisionQuest => Construct(0x4fbad);
        public static FormLink<IMusicTypeGetter> DLC03MUSExplore => Construct(0x4416f);
        public static FormLink<IMusicTypeGetter> DLC03MUSSpecialBoatArrival => Construct(0x3994c);
    }
}
