// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class SoundOutputModel
    {
        private static FormLink<ISoundOutputModelGetter> Construct(uint id) => new FormLink<ISoundOutputModelGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISoundOutputModelGetter> DLC03SOMMonoBartender02500_verb => Construct(0x5d9ea);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_StereoWorldRadio => Construct(0x5d9d2);
        public static FormLink<ISoundOutputModelGetter> DLC03SOMDialogue3D_Sermon_4000_verb => Construct(0x5d775);
        public static FormLink<ISoundOutputModelGetter> DLC03SOMDialogue3D_Sermon_7000_verb => Construct(0x5d774);
        public static FormLink<ISoundOutputModelGetter> DLC03SOMDialogue_FX_INTERCOM_3000 => Construct(0x5d76b);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_NPCGulper_D_Mono10000 => Construct(0x57736);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_NPCGulper_C_Mono05000 => Construct(0x57735);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_NPCGulper_B_Mono02500 => Construct(0x57734);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_NPCGulper_A_Mono01500 => Construct(0x57733);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_WindMountainAcadia_C_StereoRad11000 => Construct(0x4e6a2);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_WindMountainAcadia_B_StereoRad07500 => Construct(0x4e6a1);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_WindMountainAcadia_A_StereoRad02500 => Construct(0x4e6a0);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_WaterCoastWaves_D_Mono15000 => Construct(0x49b90);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_WaterCoastWaves_C_Mono04000 => Construct(0x49b8f);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_WaterCoastWaves_B_Mono03750 => Construct(0x49b8e);
        public static FormLink<ISoundOutputModelGetter> DLC03SOM_WaterCoastWaves_A_StereoRad00900 => Construct(0x49b8d);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC03FogCondenser_Mono_B_00001x03500 => Construct(0x48e04);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC03FogCondenser_Mono_A_00300x02000 => Construct(0x48e03);
        public static FormLink<ISoundOutputModelGetter> SOMDialogue3D3000_DLC03 => Construct(0x481e7);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_FireOilSlick_Mono_D_04000x11000 => Construct(0x2b1e);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_FireOilSlick_Mono_C_01250x07500 => Construct(0x2b1d);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_FireOilSlick_Mono_B_00300x03500 => Construct(0x2b1c);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_FireOilSlick_Mono_A_00000x01200 => Construct(0x2b1b);
    }
}
