// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static partial class Terminal
    {
        private static FormLink<ITerminalGetter> Construct(uint id) => new FormLink<ITerminalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_RD_SubLogs => Construct(0x54270);
        public static FormLink<ITerminalGetter> ADV08_AttackersTerminal_SubPlans => Construct(0x5426f);
        public static FormLink<ITerminalGetter> ADV08_AttackersTerminal_SubLogs => Construct(0x5426e);
        public static FormLink<ITerminalGetter> ADV08_AttackersTerminal => Construct(0x5426d);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Marketing_SubPlans => Construct(0x54267);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_BrewingProtectron_SubMail => Construct(0x54261);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Marketing_SubMail => Construct(0x54260);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_RD_SubMail => Construct(0x5425e);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_CEO_SubMail => Construct(0x5425d);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Legal_SubMail => Construct(0x5425c);
        public static FormLink<ITerminalGetter> DLC03CoA_SubInteriorMemorial01 => Construct(0x54256);
        public static FormLink<ITerminalGetter> DLC03CoA_SubInteriorMemorial => Construct(0x54255);
        public static FormLink<ITerminalGetter> DLC03_V118_ExteriorTerminalSubAttract => Construct(0x53edf);
        public static FormLink<ITerminalGetter> DLC03_WindFarmTerminalDeskCorded => Construct(0x5157e);
        public static FormLink<ITerminalGetter> DLC03_V118_ExteriorTerminal => Construct(0x509f1);
        public static FormLink<ITerminalGetter> DLC03AcadiaLabTerminalSub02 => Construct(0x5004a);
        public static FormLink<ITerminalGetter> DLC03AcadiaLabTerminalSub01 => Construct(0x50049);
        public static FormLink<ITerminalGetter> DLC03AcadiaLabTerminal => Construct(0x50048);
        public static FormLink<ITerminalGetter> DLC03Nucleus_CommandEntranceTerminalWallShort => Construct(0x4fd0e);
        public static FormLink<ITerminalGetter> DLC03NucleusCCenter_DefaultTerminalConsoleOn => Construct(0x4fd0d);
        public static FormLink<ITerminalGetter> DLC03Nucleus_CommandEntranceTerminalWall => Construct(0x4dfc9);
        public static FormLink<ITerminalGetter> DLC03_v118_EzrasHolotapeTerminal => Construct(0x4b1b6);
        public static FormLink<ITerminalGetter> DLC03_V118_TerminalBert => Construct(0x49667);
        public static FormLink<ITerminalGetter> DLC03_V118_TerminalOverseer => Construct(0x48a41);
        public static FormLink<ITerminalGetter> DLC03_V118_TerminalOverseer_SubLogs => Construct(0x48a3f);
        public static FormLink<ITerminalGetter> DLC03_V118_TerminalOverseer_SubOperations => Construct(0x48a3e);
        public static FormLink<ITerminalGetter> DLC03MQ06_WindFarmTerminalConsoleTallOn02 => Construct(0x40afc);
        public static FormLink<ITerminalGetter> DLC03MQ06_WindFarmTerminalConsoleTallOn01 => Construct(0x40afb);
        public static FormLink<ITerminalGetter> DLC03MQ06_NukeKeyTerminal => Construct(0x32c51);
        public static FormLink<ITerminalGetter> DLC03_ADV017_TerminalErikson => Construct(0x2f123);
        public static FormLink<ITerminalGetter> ADV002_MovieSubTerminalReleases => Construct(0x2d3f6);
        public static FormLink<ITerminalGetter> ADV002_MovieTerminal => Construct(0x2c858);
        public static FormLink<ITerminalGetter> DLC03_ADV019_BeaverCreekLanesTerminalFrontDeskSubMemos => Construct(0x2c2d9);
        public static FormLink<ITerminalGetter> DLC03_ADV019_BeaverCreekLanesTerminalFrontDeskSubLeagues => Construct(0x2c2d8);
        public static FormLink<ITerminalGetter> DLC03_ADV019_BeaverCreekLanesTerminalOffice => Construct(0x2c22e);
        public static FormLink<ITerminalGetter> DLC03_ADV019_BeaverCreekLanesTerminalFrontDesk => Construct(0x2c0ec);
        public static FormLink<ITerminalGetter> DLC03_ADV014_EchoLakeLumberTerminal => Construct(0x2bf35);
        public static FormLink<ITerminalGetter> DLC03MQ03FaradayTerminal => Construct(0x2958f);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_RD => Construct(0x2706d);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Tour => Construct(0x2706a);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Legal => Construct(0x2705c);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_CEO => Construct(0x27052);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Marketing => Construct(0x27050);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Manufacturing => Construct(0x27014);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_Behemoth => Construct(0x27013);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_TasteTest => Construct(0x27012);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_BrewingProtectron => Construct(0x27010);
        public static FormLink<ITerminalGetter> ADV08_Vim_Terminal_PAStation => Construct(0x2700f);
        public static FormLink<ITerminalGetter> ADV016_journalTerminal => Construct(0x2458f);
        public static FormLink<ITerminalGetter> ADV018_BHMTerminalMain => Construct(0x22c54);
        public static FormLink<ITerminalGetter> DLC03MQ06_WindFarmTerminalConsoleTallOn => Construct(0x1fec5);
        public static FormLink<ITerminalGetter> DLC03Nucleus_TerminalConsoleTallOn => Construct(0x18049);
        public static FormLink<ITerminalGetter> DLC03AtomM01_TerminalWall => Construct(0xb012);
        public static FormLink<ITerminalGetter> DLC03MQ04VREnterTerminal => Construct(0x7520);
    }
}
