// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Coast
{
    public static class Worldspace
    {
        private static FormLink<IWorldspaceGetter> Construct(uint id) => new FormLink<IWorldspaceGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWorldspaceGetter> TestClaraCoast => Construct(0x810);
        public static FormLink<IWorldspaceGetter> DLC03FarHarbor => Construct(0xb0f);
        public static FormLink<IWorldspaceGetter> TestMadCoast => Construct(0x14f4);
        public static FormLink<IWorldspaceGetter> DLC03VRWorldspace => Construct(0x4ea4);
    }
}
