// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class OldMars
{
    public static partial class ConstructibleObject
    {
        private static FormLink<IConstructibleObjectGetter> Construct(uint id) => new FormLink<IConstructibleObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IConstructibleObjectGetter> co_mod_AVM_Cutter_Cutter_Preorder => Construct(0x4);
        public static FormLink<IConstructibleObjectGetter> co_mod_AVM_Spacesuit_Miner_Backpack_OldMars => Construct(0x5);
        public static FormLink<IConstructibleObjectGetter> co_mod_AVM_Spacesuit_Miner_Helmet_OldMars => Construct(0x6);
    }
}
