// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE;

public static partial class HearthFires
{
    public static partial class Impact
    {
        private static FormLink<IImpactGetter> Construct(uint id) => new FormLink<IImpactGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IImpactGetter> WPNWoodSwordBluntGenericImpact => Construct(0x14c29);
        public static FormLink<IImpactGetter> WPNWoodSwordvsDummyImpact => Construct(0x8992);
    }
}
