// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE
{
    public static partial class HearthFires
    {
        public static class TextureSet
        {
            private static FormLink<ITextureSetGetter> Construct(uint id) => new FormLink<ITextureSetGetter>(ModKey.MakeFormKey(id));
            public static FormLink<ITextureSetGetter> BYOHTextureSetClayDepositRiverMud01 => Construct(0xa13);
            public static FormLink<ITextureSetGetter> BYOHTextureSetClayDepositReachDirt01 => Construct(0x9f1);
            public static FormLink<ITextureSetGetter> BYOHTextureSetClayDepositFallForestDirt01 => Construct(0x9f0);
            public static FormLink<ITextureSetGetter> BYOHTextureSetHawksNest01 => Construct(0xf1cd);
            public static FormLink<ITextureSetGetter> BYOHTextureSetClayDepositDirt01 => Construct(0xa510);
            public static FormLink<ITextureSetGetter> BYOHTextureSetOreStone01 => Construct(0x884a);
            public static FormLink<ITextureSetGetter> BYOHTextureSetSalmonSteak02 => Construct(0x3554);
            public static FormLink<ITextureSetGetter> BYOHTextureSetClamChowder => Construct(0x3553);
            public static FormLink<ITextureSetGetter> BYOHTextureSetTomatoSoup => Construct(0x3552);
            public static FormLink<ITextureSetGetter> BYOHTextureSetPotatoSoup => Construct(0x3551);
            public static FormLink<ITextureSetGetter> BYOHTextureSetElsweyrFondue => Construct(0x3550);
            public static FormLink<ITextureSetGetter> BYOHTextureSetAppleCabbageStew => Construct(0x354f);
            public static FormLink<ITextureSetGetter> BYOHTextureSetButter => Construct(0x354e);
            public static FormLink<ITextureSetGetter> BYOHTextureSetCabbagePotatoSoup => Construct(0x354d);
            public static FormLink<ITextureSetGetter> BYOHTextureSetHorkerStew => Construct(0x354c);
            public static FormLink<ITextureSetGetter> BYOHTextureSetBeefStew => Construct(0x354b);
            public static FormLink<ITextureSetGetter> BYOHTextureSetVenisonStew => Construct(0x354a);
            public static FormLink<ITextureSetGetter> BYOHTextureSetVegetableSoup => Construct(0x3549);
            public static FormLink<ITextureSetGetter> BYOHTextureSetJazBayTart => Construct(0x3548);
            public static FormLink<ITextureSetGetter> BYOHTextureSetJuniperBerryTart => Construct(0x3547);
            public static FormLink<ITextureSetGetter> BYOHTextureSetPotatoBread => Construct(0x3546);
        }
    }
}
