// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop03
{
    public static class ActorValueInformation
    {
        private static FormLink<IActorValueInformationGetter> Construct(uint id) => new FormLink<IActorValueInformationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IActorValueInformationGetter> DLC06WorkshopReadyToKill => Construct(0x1f01);
        public static FormLink<IActorValueInformationGetter> DLC06WorkshopItemWantsAcousticSpaceAV => Construct(0x137b);
        public static FormLink<IActorValueInformationGetter> DLC06WorkshopRatingMortalityChanceLastCheck => Construct(0x11f9);
        public static FormLink<IActorValueInformationGetter> DLC06WorkshopRatingMortalityChance => Construct(0x11f8);
        public static FormLink<IActorValueInformationGetter> DLC06WorkshopRatingOverseerDesk => Construct(0x497a);
        public static FormLink<IActorValueInformationGetter> DLC06VaultDoorTrigger => Construct(0x42ba);
    }
}
