// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop03
{
    public static partial class AStoryManagerNode
    {
        private static FormLink<IAStoryManagerNodeGetter> Construct(uint id) => new FormLink<IAStoryManagerNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAStoryManagerNodeGetter> DLC06VaultWorkshopAttackBranch => Construct(0x12b0);
        public static FormLink<IAStoryManagerNodeGetter> DLC06WorkshopAttackBlockerNode => Construct(0x12af);
        public static FormLink<IAStoryManagerNodeGetter> DLC06VaultWorkshopAttackNode => Construct(0x11fe);
        public static FormLink<IAStoryManagerNodeGetter> DLC06WorkshopIdleObjectNode => Construct(0x5614);
        public static FormLink<IAStoryManagerNodeGetter> DLC06VaultWorkshopConversations => Construct(0x4c23);
    }
}
