// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop03
{
    public static partial class Container
    {
        private static FormLink<IContainerGetter> Construct(uint id) => new FormLink<IContainerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IContainerGetter> DLC06ScrapHighTechFilingCabinet01AWeatheredTall => Construct(0x2081);
        public static FormLink<IContainerGetter> Loot_Trunk_DLC06Vault88PreWarREFILL => Construct(0x588c);
        public static FormLink<IContainerGetter> DLC06HighTechFilingCabinet01BCleanTall => Construct(0x53ad);
        public static FormLink<IContainerGetter> DLC06HighTechFilingCabinet01BCleanShort => Construct(0x53ab);
        public static FormLink<IContainerGetter> DLC06HighTechFilingCabinet01ACleanTall => Construct(0x53a8);
        public static FormLink<IContainerGetter> DLC06HighTechFilingCabinet01ACleanShort => Construct(0x53a7);
        public static FormLink<IContainerGetter> DLC06HighTechDesk02 => Construct(0x539d);
        public static FormLink<IContainerGetter> DLC06HighTechDesk01 => Construct(0x539c);
        public static FormLink<IContainerGetter> DLC06ModernDomesticSideTableSm01 => Construct(0x5393);
        public static FormLink<IContainerGetter> DLC06ModernDomesticSideTableLrg01 => Construct(0x5392);
        public static FormLink<IContainerGetter> DLC06HighTechTrashCan01Clean => Construct(0x5390);
        public static FormLink<IContainerGetter> DLC06PlayerHouse_Clean_WetBar01 => Construct(0x536c);
        public static FormLink<IContainerGetter> DLC06WorkshopHamper => Construct(0x534c);
        public static FormLink<IContainerGetter> Loot_Trunk_DLC06Vault88 => Construct(0x4d32);
        public static FormLink<IContainerGetter> Loot_Trunk_DLC06Vault88PreWar => Construct(0x4d31);
        public static FormLink<IContainerGetter> DLC06WorkshopVault_Locker_01 => Construct(0x4988);
        public static FormLink<IContainerGetter> DLC06WorkshopVault_Desk_01 => Construct(0x4987);
        public static FormLink<IContainerGetter> DLC06WorkshopVault_Dresser_01 => Construct(0x4986);
        public static FormLink<IContainerGetter> DLC06VaultWorkshopResourceContainer => Construct(0x3b0e);
        public static FormLink<IContainerGetter> DLC06WorkshopWorkbench => Construct(0x819);
    }
}
