// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop03
{
    public static partial class MiscItem
    {
        private static FormLink<IMiscItemGetter> Construct(uint id) => new FormLink<IMiscItemGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMiscItemGetter> DLC06Typewriter => Construct(0x1be5);
        public static FormLink<IMiscItemGetter> DLC06WorkshopControlBoard04 => Construct(0x50f1);
        public static FormLink<IMiscItemGetter> DLC06WorkshopControlBoard03 => Construct(0x50f0);
        public static FormLink<IMiscItemGetter> DLC06WorkshopControlBoard02 => Construct(0x50ef);
        public static FormLink<IMiscItemGetter> DLC06VaultSuitPackage88 => Construct(0x5065);
        public static FormLink<IMiscItemGetter> DLC06PipboyMisc => Construct(0x4bd3);
        public static FormLink<IMiscItemGetter> DLC06WorkshopControlBoard01 => Construct(0x4825);
    }
}
