// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop03
{
    public static partial class Outfit
    {
        private static FormLink<IOutfitGetter> Construct(uint id) => new FormLink<IOutfitGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IOutfitGetter> DLC06Vault88OutfitOverseer => Construct(0x42b3);
        public static FormLink<IOutfitGetter> DLC06Vault88Outfit => Construct(0x42b0);
    }
}
