// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop03
{
    public static partial class PlacedObject
    {
        private static FormLink<IPlacedObjectGetter> Construct(uint id) => new FormLink<IPlacedObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopEdgeMarkerGearDoor001 => Construct(0x2517);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopEdgeMarkerGearDoor => Construct(0x2072);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopFastTravelMarkerMoveTo => Construct(0x1be4);
        public static FormLink<IPlacedObjectGetter> DLC06RubbleDoorREF => Construct(0xf73);
        public static FormLink<IPlacedObjectGetter> DLC06VaultLightsOff => Construct(0x131a);
        public static FormLink<IPlacedObjectGetter> DLC06RaiderOpenDoorPatrol01Start002 => Construct(0x12b7);
        public static FormLink<IPlacedObjectGetter> DLC06RaiderOpenDoorPatrol01Start001 => Construct(0x12b6);
        public static FormLink<IPlacedObjectGetter> DLC06RaiderOpenDoorPatrol01Start => Construct(0x12b4);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopEdgeMarker02 => Construct(0x1200);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopEdgeMarker01 => Construct(0x11ff);
        public static FormLink<IPlacedObjectGetter> DLC06MQ03OverseerStartMarker => Construct(0x1083);
        public static FormLink<IPlacedObjectGetter> DLC06E03UraniumOreTargetMarker => Construct(0x54f2);
        public static FormLink<IPlacedObjectGetter> DLC06MQ03MarkerInterview => Construct(0x53e5);
        public static FormLink<IPlacedObjectGetter> DLC06MQ03MarkerOverseer => Construct(0x53e3);
        public static FormLink<IPlacedObjectGetter> DLC06MQ03MarkerClem => Construct(0x53e2);
        public static FormLink<IPlacedObjectGetter> DLC06MQ03MarkerCandyTwo => Construct(0x53e1);
        public static FormLink<IPlacedObjectGetter> DLC06MQ03MarkerCandyOne => Construct(0x53e0);
        public static FormLink<IPlacedObjectGetter> OverseerHomeMarker => Construct(0x514a);
        public static FormLink<IPlacedObjectGetter> DLC06WorkshopControlBoard04Ref => Construct(0x496f);
        public static FormLink<IPlacedObjectGetter> DLC06WorkshopControlBoard03Ref => Construct(0x496e);
        public static FormLink<IPlacedObjectGetter> DLC06WorkshopControlBoard02Ref => Construct(0x496d);
        public static FormLink<IPlacedObjectGetter> DLC06WorkshopControlBoardREF => Construct(0x4827);
        public static FormLink<IPlacedObjectGetter> DLC06SecurityTerminalREF => Construct(0x46f2);
        public static FormLink<IPlacedObjectGetter> DLC06OverseerPA => Construct(0x4826);
        public static FormLink<IPlacedObjectGetter> DLC06VaultDoorConsoleOUTSIDE => Construct(0x1001);
        public static FormLink<IPlacedObjectGetter> DLC06SecurityDoorREF => Construct(0x46f3);
        public static FormLink<IPlacedObjectGetter> Vault88Temp => Construct(0x46ef);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopFastTravelMarker => Construct(0x43fc);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopRadioTransmitterRef => Construct(0x42b6);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopVaultDoorTriggerRef => Construct(0x42bb);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea04Child01 => Construct(0x42a0);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea03Child01 => Construct(0x429f);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea01 => Construct(0x135c);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea04EdgeMarkerAdjacent02 => Construct(0x3cf1);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea04EdgeMarkerAdjacent01 => Construct(0x3cf0);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea04EdgeMarkerInactive => Construct(0x3cef);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea04EdgeMarker => Construct(0x3cee);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea03EdgeMarkerAdjacent01 => Construct(0x3ced);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea03EdgeMarkerInactive => Construct(0x3cec);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea03EdgeMarker => Construct(0x3ceb);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea02EdgeMarkerAdjacent01 => Construct(0x3ce6);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea02EdgeMarkerInactive => Construct(0x3ce4);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea02EdgeMarker => Construct(0x3ce2);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea01EdgeMarker => Construct(0x3ce0);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea03Activator => Construct(0x3b12);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea04Activator => Construct(0x3b11);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea02Activator => Construct(0x3b10);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea04 => Construct(0x3b0c);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea03 => Construct(0x3b0b);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea02 => Construct(0x3b0a);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopConsoleActivateOUTSIDE => Construct(0x1002);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopGearDoorRef => Construct(0xffd);
        public static FormLink<IPlacedObjectGetter> DLC06VaultDoorConsoleINSIDE => Construct(0xff5);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopConsoleActivateINSIDE => Construct(0xff4);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopCenterMarker => Construct(0xff0);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopRef => Construct(0xfef);
        public static FormLink<IPlacedObjectGetter> DLC06MQ02SetStage500 => Construct(0x1440);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOn05 => Construct(0x12fd);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOn04 => Construct(0x12fc);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOn03 => Construct(0x12fb);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOn02 => Construct(0x12fa);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOn => Construct(0x12f9);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOff05 => Construct(0x12f8);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOff04 => Construct(0x12f7);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOff03 => Construct(0x12f6);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOff02 => Construct(0x12f5);
        public static FormLink<IPlacedObjectGetter> KlaxonStartOff => Construct(0x12f4);
        public static FormLink<IPlacedObjectGetter> DLC06MQ01PASceneTrigger => Construct(0x5145);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea01Child02 => Construct(0x4d4c);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea01Child01 => Construct(0x42a1);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopBuildArea02Child01 => Construct(0x3b0d);
        public static FormLink<IPlacedObjectGetter> DLC06LeaveVaultMarker => Construct(0x1221);
        public static FormLink<IPlacedObjectGetter> DLC06MQ01EmergencyBroadcastREF => Construct(0x4fbe);
        public static FormLink<IPlacedObjectGetter> DLC06WorkshopRadioRef => Construct(0x4fbd);
        public static FormLink<IPlacedObjectGetter> DLC06VaultWorkshopCaravanTargetMarker => Construct(0x4ace);
        public static FormLink<IPlacedObjectGetter> DLC06Vault88MapMarker => Construct(0x43fb);
    }
}
