// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop03
{
    public static partial class Scene
    {
        private static FormLink<ISceneGetter> Construct(uint id) => new FormLink<ISceneGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISceneGetter> DLC06WorkshopGenericBarberSurgeryScene => Construct(0x2564);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopRadioBeacon => Construct(0x4aca);
        public static FormLink<ISceneGetter> DLC06WorkshopBarberScene => Construct(0x5451);
        public static FormLink<ISceneGetter> DLC06WorkshopSurgeryScene => Construct(0x5454);
        public static FormLink<ISceneGetter> DLC06MQ01_Intercom => Construct(0x5144);
        public static FormLink<ISceneGetter> DLC06MQ02_100a_IntercomIntro => Construct(0x4828);
        public static FormLink<ISceneGetter> DLC06MQ02_100b_MoreIntercom => Construct(0x4829);
        public static FormLink<ISceneGetter> DLC06MQ02_200_SecurityLifted => Construct(0x482a);
        public static FormLink<ISceneGetter> DLC06MQ03_100_MeetOverseer => Construct(0x493c);
        public static FormLink<ISceneGetter> DLC06MQ03_300_NeedTestSubjects => Construct(0x493d);
        public static FormLink<ISceneGetter> DLC06MQ03_500_CandidateOne => Construct(0x493e);
        public static FormLink<ISceneGetter> DLC06MQ03_600_CandidateTwo => Construct(0x493f);
        public static FormLink<ISceneGetter> DLC06MQ03_700_Clem => Construct(0x4940);
        public static FormLink<ISceneGetter> DLC06MQ03_150b_HateVaultTec => Construct(0x495d);
        public static FormLink<ISceneGetter> DLC06MQ03_150_AtValeryArea => Construct(0x5146);
        public static FormLink<ISceneGetter> DLC06MQ03_125a_WalkNTalk => Construct(0x5147);
        public static FormLink<ISceneGetter> DLC06MQ03_125b_WalkNTalk02 => Construct(0x5148);
        public static FormLink<ISceneGetter> DLC06MQ03_125c_WalkNTalk03 => Construct(0x5149);
        public static FormLink<ISceneGetter> DLC06MQ03_ReactDesk => Construct(0x5e90);
        public static FormLink<ISceneGetter> DLC06MQ03_ReactCandidates => Construct(0x5e91);
        public static FormLink<ISceneGetter> DLC06E01_150_Intro => Construct(0x4aac);
        public static FormLink<ISceneGetter> DLC06E01_550_ClemReactsToExperiment => Construct(0x4af1);
        public static FormLink<ISceneGetter> DLC06E01_700_ClemSetBack => Construct(0x4af2);
        public static FormLink<ISceneGetter> DLC06E01_100_GetClemOutfitted => Construct(0x53f3);
        public static FormLink<ISceneGetter> DLC06E02_600_FirstDrink => Construct(0x1191);
        public static FormLink<ISceneGetter> DLC06E02_100_QuestAccepted => Construct(0x4af3);
        public static FormLink<ISceneGetter> DLC06E02_300_FormulasHandedOff => Construct(0x4bcb);
        public static FormLink<ISceneGetter> DLC06E02_500_SodaFountainBuilt => Construct(0x4bcc);
        public static FormLink<ISceneGetter> DLC06E02_700_CheckInWithClem => Construct(0x4bcd);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations02Scene => Construct(0x4c21);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations01Scene => Construct(0x4c20);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations03Scene => Construct(0x4c22);
        public static FormLink<ISceneGetter> DLC06E03_100_QuestAccepted => Construct(0x4fac);
        public static FormLink<ISceneGetter> DLC06E03_400_PhoropterExperiment => Construct(0x50e9);
        public static FormLink<ISceneGetter> DLC06E03_400a_Subliminal => Construct(0x50ea);
        public static FormLink<ISceneGetter> DLC06E03_400b_Monitoring => Construct(0x50eb);
        public static FormLink<ISceneGetter> DLC06E03_400c_EyeExam => Construct(0x50ec);
        public static FormLink<ISceneGetter> DLC06E03_500a_CandyOneAngry => Construct(0x50ed);
        public static FormLink<ISceneGetter> DLC06E03_500b_CandyOneHappy => Construct(0x50ee);
        public static FormLink<ISceneGetter> DLC06MQ01RadioBeaconScene => Construct(0x4fc0);
        public static FormLink<ISceneGetter> DLC06E04_300_ClemGambling => Construct(0x1220);
        public static FormLink<ISceneGetter> DLC06E04_400_ClemAfterwards => Construct(0x1222);
        public static FormLink<ISceneGetter> DLC06E04_100a_CandyOneLeaves => Construct(0x5143);
        public static FormLink<ISceneGetter> DLC06E04_100b_CandyOneStays => Construct(0x52b2);
        public static FormLink<ISceneGetter> DLC06E04_100c_QuestAccept => Construct(0x52b3);
        public static FormLink<ISceneGetter> DLC06E04_500a_EndDebrief => Construct(0x54b6);
        public static FormLink<ISceneGetter> DLC06E04_500b_HappyOverseer => Construct(0x54b7);
        public static FormLink<ISceneGetter> DLC06E04_500c_SadOverseer => Construct(0x54b8);
        public static FormLink<ISceneGetter> DLC06DialogueVault88_PostQuestClem => Construct(0x5ec2);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations15Scene => Construct(0x5260);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations13Scene => Construct(0x525e);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations11Scene => Construct(0x525c);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations09Scene => Construct(0x525a);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations07Scene => Construct(0x5258);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations05Scene => Construct(0x5256);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations04Scene => Construct(0x5255);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations06Scene => Construct(0x5257);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations08Scene => Construct(0x5259);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations10Scene => Construct(0x525b);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations12Scene => Construct(0x525d);
        public static FormLink<ISceneGetter> DLC06VaultWorkshopConversations14Scene => Construct(0x525f);
        public static FormLink<ISceneGetter> DLC06WorkshopSlotMachineHandlerScene => Construct(0x5616);
        public static FormLink<ISceneGetter> DLC06WorkshopSodaFountainHandlerScene => Construct(0x5610);
        public static FormLink<ISceneGetter> DLC06WorkshopPhoropterHandlerScene => Construct(0x573b);
    }
}
