// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE
{
    public static partial class Skyrim
    {
        public static class Ammunition
        {
            private static FormLink<IAmmunitionGetter> Construct(uint id) => new FormLink<IAmmunitionGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IAmmunitionGetter> DwarvenSphereBolt02 => Construct(0x10ec8c);
            public static FormLink<IAmmunitionGetter> FollowerIronArrow => Construct(0x10e2de);
            public static FormLink<IAmmunitionGetter> boundArrow => Construct(0x10b0a7);
            public static FormLink<IAmmunitionGetter> TrapDweBallistaBoltAmmo05 => Construct(0x109ab7);
            public static FormLink<IAmmunitionGetter> TrapDweBallistaBoltAmmo06 => Construct(0x109ab6);
            public static FormLink<IAmmunitionGetter> TrapDweBallistaBoltAmmo04 => Construct(0x109ab5);
            public static FormLink<IAmmunitionGetter> TrapDweBallistaBoltAmmo03 => Construct(0x109ab4);
            public static FormLink<IAmmunitionGetter> TrapDweBallistaBoltAmmo02 => Construct(0x109ab3);
            public static FormLink<IAmmunitionGetter> MQ101SteelArrow => Construct(0x105ee7);
            public static FormLink<IAmmunitionGetter> NordHeroArrow => Construct(0xeafdf);
            public static FormLink<IAmmunitionGetter> dunGeirmundSigdisArrowsIllusion => Construct(0xe738a);
            public static FormLink<IAmmunitionGetter> ForswornArrow => Construct(0xcee9e);
            public static FormLink<IAmmunitionGetter> dunArcherPracticeArrow => Construct(0xcab52);
            public static FormLink<IAmmunitionGetter> dunJaphetsFollyCWCatapultAmmo => Construct(0x961d6);
            public static FormLink<IAmmunitionGetter> DwarvenSphereBolt01 => Construct(0x7b935);
            public static FormLink<IAmmunitionGetter> DwarvenSphereArrow => Construct(0x7b932);
            public static FormLink<IAmmunitionGetter> CWArrowShort => Construct(0x20f02);
            public static FormLink<IAmmunitionGetter> CWArrow => Construct(0x20ddf);
            public static FormLink<IAmmunitionGetter> CWCatapultAmmo => Construct(0x73fe6);
            public static FormLink<IAmmunitionGetter> TrapDweBallistaBoltAmmo01 => Construct(0x6da4f);
            public static FormLink<IAmmunitionGetter> DummyArrow => Construct(0x6a0bf);
            public static FormLink<IAmmunitionGetter> FXDustDropAmmoTiny => Construct(0x52e99);
            public static FormLink<IAmmunitionGetter> FXDustDropAmmoSm => Construct(0x52e97);
            public static FormLink<IAmmunitionGetter> FXDustDropAmmoMed => Construct(0x3bdf7);
            public static FormLink<IAmmunitionGetter> TrapDart => Construct(0x236dd);
            public static FormLink<IAmmunitionGetter> FalmerArrow => Construct(0x38341);
            public static FormLink<IAmmunitionGetter> DraugrArrow => Construct(0x34182);
            public static FormLink<IAmmunitionGetter> DaedricArrow => Construct(0x139c0);
            public static FormLink<IAmmunitionGetter> EbonyArrow => Construct(0x139bf);
            public static FormLink<IAmmunitionGetter> GlassArrow => Construct(0x139be);
            public static FormLink<IAmmunitionGetter> ElvenArrow => Construct(0x139bd);
            public static FormLink<IAmmunitionGetter> DwarvenArrow => Construct(0x139bc);
            public static FormLink<IAmmunitionGetter> OrcishArrow => Construct(0x139bb);
            public static FormLink<IAmmunitionGetter> SteelArrow => Construct(0x1397f);
            public static FormLink<IAmmunitionGetter> IronArrow => Construct(0x1397d);
        }
    }
}
