using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE
{
    public static partial class Skyrim
    {
        public static class VisualEffect
        {
            private readonly static ModKey ModKey = ModKey.FromNameAndExtension("Skyrim.esm");
            private static FormLink<IVisualEffectGetter> Construct(uint id) => new FormLink<IVisualEffectGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IVisualEffectGetter> MGTeleportOutEffectNoRefraction => Construct(0x1733c);
            public static FormLink<IVisualEffectGetter> NightingaleStrifeAbsorbTargetVFX => Construct(0x10f506);
            public static FormLink<IVisualEffectGetter> FXDraugrMagicBowStreakEffect => Construct(0x10e73c);
            public static FormLink<IVisualEffectGetter> FXDraugrMagicAxeStreakEffect => Construct(0x10e73a);
            public static FormLink<IVisualEffectGetter> HircineTotemPVFX02 => Construct(0x10c433);
            public static FormLink<IVisualEffectGetter> HircineTotemPVFX01 => Construct(0x10c432);
            public static FormLink<IVisualEffectGetter> FXSovengardeGlowEffect => Construct(0x10b2dc);
            public static FormLink<IVisualEffectGetter> DA10SummonValorTargetFX => Construct(0x10b1fa);
            public static FormLink<IVisualEffectGetter> DA02SummonValorTargetFX => Construct(0x10ab4c);
            public static FormLink<IVisualEffectGetter> FXSprigganAttachmentsMatronEffect => Construct(0x1090f5);
            public static FormLink<IVisualEffectGetter> DA10ReanimateTargetFX => Construct(0x107d9b);
            public static FormLink<IVisualEffectGetter> DA07SummonTargetFX => Construct(0x107d96);
            public static FormLink<IVisualEffectGetter> DA14TransformVFX => Construct(0x106ade);
            public static FormLink<IVisualEffectGetter> MS04MemoryFXBody01VFX => Construct(0x106adc);
            public static FormLink<IVisualEffectGetter> MGTeleportOutEffect => Construct(0x102731);
            public static FormLink<IVisualEffectGetter> MGTeleportInEffect => Construct(0x102730);
            public static FormLink<IVisualEffectGetter> FXFootstepsAttachSnowEffect => Construct(0x101cfc);
            public static FormLink<IVisualEffectGetter> FXCameraAttachEmbersSnowEffect => Construct(0x101cfa);
            public static FormLink<IVisualEffectGetter> FXCameraAttachEmbersHeavyEffects => Construct(0x1019ab);
            public static FormLink<IVisualEffectGetter> FXTimeWarpCamAttachEffect => Construct(0x101967);
            public static FormLink<IVisualEffectGetter> WerewolfExtractVFX => Construct(0xfd7d8);
            public static FormLink<IVisualEffectGetter> FXMG07DogDarkeningEffect => Construct(0xf906a);
            public static FormLink<IVisualEffectGetter> FXMG07DogEyeGlowEffect => Construct(0xf9065);
            public static FormLink<IVisualEffectGetter> FXMagicDraugrDarkeningEffect => Construct(0xf71e3);
            public static FormLink<IVisualEffectGetter> FXDraugrMagicSwordStreakEffect => Construct(0xf71e1);
            public static FormLink<IVisualEffectGetter> BloodSprayWereWolfEatEffect => Construct(0xf3a8b);
            public static FormLink<IVisualEffectGetter> FXSkeletonNecroPriestEyeGlowEffect => Construct(0xebe9e);
            public static FormLink<IVisualEffectGetter> FXNecroSkeletonPriestMultiEffect => Construct(0xebe9a);
            public static FormLink<IVisualEffectGetter> FXSkeletonNecroEyeGlowEffect => Construct(0xeb87a);
            public static FormLink<IVisualEffectGetter> FXNecroSkeletonMultiEffect => Construct(0xeb86d);
            public static FormLink<IVisualEffectGetter> FXCameraAttachEmbersEffect => Construct(0xeee12);
            public static FormLink<IVisualEffectGetter> FXCameraAttachSnowFallingEffect => Construct(0xee323);
            public static FormLink<IVisualEffectGetter> FXIceWraith2ndFormEffect => Construct(0xed39a);
            public static FormLink<IVisualEffectGetter> FXfallingSandDragonPriestEffect => Construct(0xebb72);
            public static FormLink<IVisualEffectGetter> FXCameraAttachSmokeHeavyEffect => Construct(0xebb6b);
            public static FormLink<IVisualEffectGetter> FXNocturnalBirdR => Construct(0xcc80f);
            public static FormLink<IVisualEffectGetter> FXNocturnalBirdL => Construct(0xcc80d);
            public static FormLink<IVisualEffectGetter> FXCameraAttachFogWispyEffect => Construct(0xb9700);
            public static FormLink<IVisualEffectGetter> FXCameraAttachDustFineEffect => Construct(0xb96ca);
            public static FormLink<IVisualEffectGetter> FXCameraAttachFineMistEffect => Construct(0xb96c1);
            public static FormLink<IVisualEffectGetter> FXCameraAttachDripsEffect => Construct(0xb9571);
            public static FormLink<IVisualEffectGetter> FXCameraAttachNeedlesWindyDryUpEffect => Construct(0xb9569);
            public static FormLink<IVisualEffectGetter> FXCameraAttachNeedlesWindyUpEffect => Construct(0xb9515);
            public static FormLink<IVisualEffectGetter> FXCameraAttachLeavesWindyUpEffect => Construct(0xb9514);
            public static FormLink<IVisualEffectGetter> FXCameraAttachLeavesWindyEffect => Construct(0xb94fd);
            public static FormLink<IVisualEffectGetter> FXCameraAttachNeedlesWindyEffect => Construct(0xb94fc);
            public static FormLink<IVisualEffectGetter> FXCameraAttachLeavesEffect => Construct(0xb94f8);
            public static FormLink<IVisualEffectGetter> FXCameraAttachNeedlesEffect => Construct(0xb94f5);
            public static FormLink<IVisualEffectGetter> FXCameraAttachFluffEffect => Construct(0xb94ed);
            public static FormLink<IVisualEffectGetter> FXCameraAttachFalmerDustEffect => Construct(0xb94eb);
            public static FormLink<IVisualEffectGetter> FXCameraAttachDustEffect => Construct(0xb94e5);
            public static FormLink<IVisualEffectGetter> FXCameraAttachTurbulentFogEffect => Construct(0xb94d1);
            public static FormLink<IVisualEffectGetter> FXCameraAttachFogEffect => Construct(0xb94cd);
            public static FormLink<IVisualEffectGetter> FXGreybeardAbsorbEffect => Construct(0x9186e);
            public static FormLink<IVisualEffectGetter> FXAlduinTimRiftEffect => Construct(0x5b800);
            public static FormLink<IVisualEffectGetter> FXTimeTravelCamAttachEffect => Construct(0x44f3a);
            public static FormLink<IVisualEffectGetter> FXReadElderScrollEffect => Construct(0x44f20);
            public static FormLink<IVisualEffectGetter> FXAlduinSoulEscapeEffect => Construct(0x154be);
            public static FormLink<IVisualEffectGetter> FXDragonResurStreaksEffect => Construct(0xcee0e);
            public static FormLink<IVisualEffectGetter> IceWraithMultiParticlesEffect => Construct(0xcaf89);
            public static FormLink<IVisualEffectGetter> TFXfogVT => Construct(0x998c6);
            public static FormLink<IVisualEffectGetter> TFX03 => Construct(0x94064);
            public static FormLink<IVisualEffectGetter> TFX02 => Construct(0x94063);
            public static FormLink<IVisualEffectGetter> TFX01 => Construct(0x94060);
            public static FormLink<IVisualEffectGetter> FXDwarvenSpiderEffect => Construct(0x4efb6);
            public static FormLink<IVisualEffectGetter> FXDwarvenCenturionArm02Effect => Construct(0x4bb51);
            public static FormLink<IVisualEffectGetter> FXDwarvenCenturionArm01Effect => Construct(0x4bb4e);
            public static FormLink<IVisualEffectGetter> FXDwarvenSphereEffect => Construct(0x4bb4b);
            public static FormLink<IVisualEffectGetter> FXDwarvenCenturionEffect => Construct(0x30b3b);
            public static FormLink<IVisualEffectGetter> AbsorbGreenTargetVFX01 => Construct(0xabf16);
            public static FormLink<IVisualEffectGetter> AbsorbGreenCastVFX01 => Construct(0xabf15);
            public static FormLink<IVisualEffectGetter> AbsorbBlueTargetVFX01 => Construct(0xabf14);
            public static FormLink<IVisualEffectGetter> AbsorbBlueCastVFX01 => Construct(0xabf13);
            public static FormLink<IVisualEffectGetter> AbsorbCastVFX01 => Construct(0xabefc);
            public static FormLink<IVisualEffectGetter> AbsorbTargetVFX01 => Construct(0xabefb);
            public static FormLink<IVisualEffectGetter> FXDraugrMaleEyeEffect => Construct(0xabee8);
            public static FormLink<IVisualEffectGetter> FXDragonPreistEyeGlowEffect => Construct(0xaa856);
            public static FormLink<IVisualEffectGetter> FXDragonPriestParticlesEffect => Construct(0xaa854);
            public static FormLink<IVisualEffectGetter> FXDraugrFemaleEyeEffect => Construct(0xa8527);
            public static FormLink<IVisualEffectGetter> FXSpriggenSwarmEffect => Construct(0x9aa43);
            public static FormLink<IVisualEffectGetter> FXSprigganFX01Effect => Construct(0x9aa3a);
            public static FormLink<IVisualEffectGetter> FXWitchlightMeshEffect => Construct(0x8cdcf);
            public static FormLink<IVisualEffectGetter> FXWispAttachEffect => Construct(0x8cc8a);
            public static FormLink<IVisualEffectGetter> FXCameraAttachUpSnowEffect => Construct(0x8941a);
            public static FormLink<IVisualEffectGetter> FXAtronachStormCloakEffect => Construct(0x6d520);
            public static FormLink<IVisualEffectGetter> FXAtronachFireTrailEffect => Construct(0x60d9d);
            public static FormLink<IVisualEffectGetter> TrapRocksDustVEffect => Construct(0x877fc);
            public static FormLink<IVisualEffectGetter> FXDragonDeathLHandFireEffect => Construct(0x86819);
            public static FormLink<IVisualEffectGetter> FXDragonDeathLHandBitsEffect => Construct(0x86818);
            public static FormLink<IVisualEffectGetter> FXDragonDeathRHandFireEffect => Construct(0x86815);
            public static FormLink<IVisualEffectGetter> FXDragonDeathRHandBitsEffect => Construct(0x86813);
            public static FormLink<IVisualEffectGetter> DA09Vision => Construct(0x85200);
            public static FormLink<IVisualEffectGetter> DisguiseCastVFX01 => Construct(0x78765);
            public static FormLink<IVisualEffectGetter> DisguiseTargetVFX01 => Construct(0x78764);
            public static FormLink<IVisualEffectGetter> FXDragonBiteEffect => Construct(0x4efbe);
            public static FormLink<IVisualEffectGetter> IceWraithExplosion02Effect => Construct(0x5e993);
            public static FormLink<IVisualEffectGetter> IceWraithExplosion01Effect => Construct(0x5e991);
            public static FormLink<IVisualEffectGetter> INTSkillsToPerkTransitionEffect => Construct(0x5d47b);
            public static FormLink<IVisualEffectGetter> FXCameraAttachBlowingFogEffect => Construct(0x5592d);
            public static FormLink<IVisualEffectGetter> SoulTrapPVFX02 => Construct(0x531b1);
            public static FormLink<IVisualEffectGetter> SoulTrapPVFX01 => Construct(0x531af);
            public static FormLink<IVisualEffectGetter> MAGDragonPowerAbsorbManEffect => Construct(0x2e6ad);
            public static FormLink<IVisualEffectGetter> MAGDragonPowerAbsorbEffect => Construct(0x2e6ab);
        }
    }
}
