// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class AddonNode
    {
        private static FormLink<IAddonNodeGetter> Construct(uint id) => new FormLink<IAddonNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAddonNodeGetter> DLC05ConduitRadiatorLight => Construct(0xe1a);
        public static FormLink<IAddonNodeGetter> DLC05FireworkTrailGold => Construct(0xdd9);
        public static FormLink<IAddonNodeGetter> DLC05FireworkPalmTrailGold => Construct(0xdd6);
        public static FormLink<IAddonNodeGetter> DLC05FireworkPalmTrailSilver => Construct(0xdd5);
        public static FormLink<IAddonNodeGetter> DLC05FireworkTrailSilver => Construct(0xd4c);
        public static FormLink<IAddonNodeGetter> DLC05FireworkTrailYellow => Construct(0xd4b);
        public static FormLink<IAddonNodeGetter> DLC05FireworkTrailBlue => Construct(0xd4a);
        public static FormLink<IAddonNodeGetter> DLC05FireworkTrailPink => Construct(0xd49);
        public static FormLink<IAddonNodeGetter> DLC05FireworkTrailGreen => Construct(0xd48);
        public static FormLink<IAddonNodeGetter> DLC05FireworkTrailRed => Construct(0xd47);
        public static FormLink<IAddonNodeGetter> DLC05LightNodeWorkshopMarqueeSign01 => Construct(0xb9c);
        public static FormLink<IAddonNodeGetter> DLC05LightNodeWorkshopMarqueeArrow01 => Construct(0xb9b);
        public static FormLink<IAddonNodeGetter> DLC05ConduitLight => Construct(0xb53);
        public static FormLink<IAddonNodeGetter> DLC05PowerArmorDisplay03 => Construct(0xb4f);
        public static FormLink<IAddonNodeGetter> DLC05PowerArmorDisplay02 => Construct(0xb28);
        public static FormLink<IAddonNodeGetter> DLC05PowerArmorDisplay01 => Construct(0xb27);
    }
}
