// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class Container
    {
        private static FormLink<IContainerGetter> Construct(uint id) => new FormLink<IContainerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IContainerGetter> DLC05WorkshopHopper03 => Construct(0xed8);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift08 => Construct(0xdef);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift07 => Construct(0xdee);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift06 => Construct(0xded);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift05 => Construct(0xdec);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderAmmo01 => Construct(0xd38);
        public static FormLink<IContainerGetter> DLC05WorkshopSorter02 => Construct(0xc30);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderClothing01 => Construct(0xc2d);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift04 => Construct(0xc23);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift03 => Construct(0xc22);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift02 => Construct(0xc21);
        public static FormLink<IContainerGetter> DLC05WorkshopConveyorLift01 => Construct(0xbfc);
        public static FormLink<IContainerGetter> DLC05WorkshopWeaponRackLong01 => Construct(0xbc6);
        public static FormLink<IContainerGetter> DLC05WorkshopWeaponRackShort01 => Construct(0xbc5);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderArmor01 => Construct(0xacb);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderExplosives02 => Construct(0xabe);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderExplosives01 => Construct(0xaa9);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderFood01 => Construct(0xaa5);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderWeapon03 => Construct(0xa6a);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderWeapon02 => Construct(0xa69);
        public static FormLink<IContainerGetter> DLC05WorkshopSorter01 => Construct(0xa5e);
        public static FormLink<IContainerGetter> DLC05WorkshopHopper02 => Construct(0xa5c);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilderWeapon01 => Construct(0xa50);
        public static FormLink<IContainerGetter> DLC05WorkshopFireworkMortar02 => Construct(0xa48);
        public static FormLink<IContainerGetter> DLC05WorkshopBuilder01 => Construct(0xa36);
        public static FormLink<IContainerGetter> DLC05WorkshopPitchingMachine01 => Construct(0xa1e);
        public static FormLink<IContainerGetter> DLC05WorkshopHopper01 => Construct(0x99e);
        public static FormLink<IContainerGetter> DLC05WorkshopWeaponStand01 => Construct(0x99b);
        public static FormLink<IContainerGetter> DLC05WorkshopWeaponRack02 => Construct(0x99a);
        public static FormLink<IContainerGetter> DLC05WorkshopPistolRack02 => Construct(0x999);
        public static FormLink<IContainerGetter> DLC05WorkshopPistolRack01 => Construct(0x997);
        public static FormLink<IContainerGetter> DLC05WorkshopFireworkMortar01 => Construct(0x8ce);
        public static FormLink<IContainerGetter> DLC05WorkshopWeaponRack01 => Construct(0x8a9);
    }
}
