// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class FormList
    {
        private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFormListGetter> DLC05_HeadPartsMannequin => Construct(0xee9);
        public static FormLink<IFormListGetter> DLC05WorkshopPoweredSpeakersEffects => Construct(0xee5);
        public static FormLink<IFormListGetter> DLC05WorkshopPoweredSpeakersMusic => Construct(0xee4);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Walls02 => Construct(0xe30);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_RoofsPlatforms => Construct(0xe2c);
        public static FormLink<IFormListGetter> DLC05WeaponsRackKeywordList => Construct(0xe26);
        public static FormLink<IFormListGetter> DLC05PitchingMachineWeaponList => Construct(0xddb);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_GreenhousePrefabs => Construct(0xd8e);
        public static FormLink<IFormListGetter> DLC05WorkshopArmorRackListFemale => Construct(0xd8b);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_GreenhouseDoors => Construct(0xd73);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_GreenhouseRoofs => Construct(0xd70);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_GreenhouseWalls => Construct(0xd6f);
        public static FormLink<IFormListGetter> DLC05MarqueeLetters_Red => Construct(0xc3d);
        public static FormLink<IFormListGetter> DLC05MarqueeLetters_Black => Construct(0xc3c);
        public static FormLink<IFormListGetter> DLC05ComponentSorterList => Construct(0xc31);
        public static FormLink<IFormListGetter> DLC05WorkshopConveyorBeltsLifts => Construct(0xc24);
        public static FormLink<IFormListGetter> DLC05PitchingMachineList => Construct(0xc1d);
        public static FormLink<IFormListGetter> DLC05WorkshopBallTrackStraight => Construct(0xc13);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_MiscCupola => Construct(0xc12);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_RoofsMetal => Construct(0xc11);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_RoofsCap02 => Construct(0xc0e);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_WallsGlass => Construct(0xc0c);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_PrefabsGlass => Construct(0xc0a);
        public static FormLink<IFormListGetter> DLC05HopperLargeItems => Construct(0xbfb);
        public static FormLink<IFormListGetter> DLC05WeaponsLongRackKeywordList => Construct(0xbca);
        public static FormLink<IFormListGetter> DLC05WeaponsShortRackKeywordList => Construct(0xbc9);
        public static FormLink<IFormListGetter> DLC05MarqueeArrows => Construct(0xba2);
        public static FormLink<IFormListGetter> DLC05WeaponsHeavyKeywordList => Construct(0xb9a);
        public static FormLink<IFormListGetter> DLC05WorkshopScaffoldKit_StairsWood => Construct(0xb4d);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_DoorsMetal => Construct(0xb4b);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_FloorsWood => Construct(0xb4a);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_FloorsSlate => Construct(0xb47);
        public static FormLink<IFormListGetter> DLC05ConveyorBeltsRollers => Construct(0xb43);
        public static FormLink<IFormListGetter> DLC05_modScrapRecipe_NullMelee_Cloth => Construct(0xb41);
        public static FormLink<IFormListGetter> DLC05Conduits => Construct(0xb1b);
        public static FormLink<IFormListGetter> DLC05WorkshopHopperContainerTypes => Construct(0xa5b);
        public static FormLink<IFormListGetter> DLC05WorkshopHopperContainerKeywords => Construct(0xa5a);
        public static FormLink<IFormListGetter> DLC05WorkshopWksDisplayCase => Construct(0xa3e);
        public static FormLink<IFormListGetter> DLC05ConveyorBelts => Construct(0xa2a);
        public static FormLink<IFormListGetter> DLC05PistolRackList => Construct(0xa0a);
        public static FormLink<IFormListGetter> DLC05WeaponRackList => Construct(0xa08);
        public static FormLink<IFormListGetter> DLC05WorkshopMenu01Decor02DisplayCases => Construct(0xa05);
        public static FormLink<IFormListGetter> DLC05PowerArmorDisplayList => Construct(0xa01);
        public static FormLink<IFormListGetter> DLC05WorkshopBoxCarOrange => Construct(0x9fd);
        public static FormLink<IFormListGetter> DLC05WorkshopMenu01Build02Boxcars => Construct(0x9f9);
        public static FormLink<IFormListGetter> DLC05WorkshopScaffold_Prefabs => Construct(0x9f3);
        public static FormLink<IFormListGetter> DLC05PoweredPosterFrame => Construct(0x9a1);
        public static FormLink<IFormListGetter> DLC05WorkshopBallTrackCurves => Construct(0x995);
        public static FormLink<IFormListGetter> DLC05WorkshopWksBallTrackWood => Construct(0x992);
        public static FormLink<IFormListGetter> DLC05WorkshopBoxCarBlue => Construct(0x947);
        public static FormLink<IFormListGetter> DLC05WorkshopMenu01Build02Scaffolding => Construct(0x919);
        public static FormLink<IFormListGetter> DLC05WorkshopScaffoldKit_Railings => Construct(0x8f8);
        public static FormLink<IFormListGetter> DLC05WorkshopScaffoldKit_Frames => Construct(0x8f7);
        public static FormLink<IFormListGetter> DLC05WorkshopScaffoldKit_Stairs => Construct(0x8f6);
        public static FormLink<IFormListGetter> DLC05WorkshopScaffoldKit_Floors => Construct(0x8f5);
        public static FormLink<IFormListGetter> DLC05WorkshopScaffoldKit => Construct(0x8f4);
        public static FormLink<IFormListGetter> DLC05FireworkShellKeywordList => Construct(0x8d4);
        public static FormLink<IFormListGetter> DLC05WeaponsPistolKeywordList => Construct(0x8cd);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Prefabs => Construct(0x8ca);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Misc => Construct(0x8c9);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Stairs => Construct(0x8c8);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Floors => Construct(0x8c7);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Doors => Construct(0x8c6);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Roofs => Construct(0x8c5);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit_Walls => Construct(0x8c4);
        public static FormLink<IFormListGetter> DLC05WorkshopMenu01Build02Warehouse => Construct(0x8b5);
        public static FormLink<IFormListGetter> DLC05WorkshopArmorRackListMale => Construct(0x8b4);
        public static FormLink<IFormListGetter> DLC05WeaponsAllKeywordList => Construct(0x8a2);
        public static FormLink<IFormListGetter> DLC05WorkshopWarehouseKit => Construct(0x80e);
    }
}
