// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static partial class Light
    {
        private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILightGetter> DLC05WorkshopConduitRadiatorLight01 => Construct(0xe1b);
        public static FormLink<ILightGetter> DLC05FireworkExplosionGreenLightDestruction => Construct(0xdcc);
        public static FormLink<ILightGetter> DLC05WorkshopMarqueeSignOmni01 => Construct(0xbac);
        public static FormLink<ILightGetter> DLC05WorkshopMarqueeArrowOmni01 => Construct(0xbab);
        public static FormLink<ILightGetter> DLC05WorkshopConduitLight => Construct(0xb52);
        public static FormLink<ILightGetter> DLC05PowerArmorDisplayLight03 => Construct(0xb50);
        public static FormLink<ILightGetter> DLC05PowerArmorDisplayLight02 => Construct(0xb26);
        public static FormLink<ILightGetter> DLC05PowerArmorDisplayLight01 => Construct(0xb25);
        public static FormLink<ILightGetter> DLC05FireworkPeony01Light => Construct(0xa4a);
        public static FormLink<ILightGetter> DLC05FireworkWeatherClearLight01 => Construct(0xa26);
    }
}
