// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class Projectile
    {
        private static FormLink<IProjectileGetter> Construct(uint id) => new FormLink<IProjectileGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePalmGoldTrail => Construct(0xdd8);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePalmSilverTrail => Construct(0xdd7);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePalmGold => Construct(0xd80);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePalmSilver => Construct(0xd22);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectileCrackle => Construct(0xd21);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePeonyYellow => Construct(0xd1d);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePeonyPink => Construct(0xd1b);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePeonyBlue => Construct(0xd1a);
        public static FormLink<IProjectileGetter> DLC05PaintballProjectileGreen => Construct(0xd06);
        public static FormLink<IProjectileGetter> DLC05PaintballProjectileGlow => Construct(0xd05);
        public static FormLink<IProjectileGetter> DLC05PaintballProjectileYellow => Construct(0xd04);
        public static FormLink<IProjectileGetter> DLC05PaintballProjectileWhite => Construct(0xd03);
        public static FormLink<IProjectileGetter> DLC05PaintballProjectileOrange => Construct(0xd02);
        public static FormLink<IProjectileGetter> DLC05PaintballProjectileRed => Construct(0xd01);
        public static FormLink<IProjectileGetter> DLC05PaintballProjectileBlue => Construct(0xd00);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePeonyRed => Construct(0xa4c);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectileMinutemenFlare => Construct(0x92d);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectileWeatherRadstorm => Construct(0x905);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectileWeatherRain => Construct(0x8fe);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectileWeatherClear => Construct(0x8fa);
        public static FormLink<IProjectileGetter> DLC05FireworkProjectilePeonyGreen => Construct(0x8a7);
    }
}
