// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class Quest
    {
        private static FormLink<IQuestGetter> Construct(uint id) => new FormLink<IQuestGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IQuestGetter> GameJamQuest => Construct(0x800);
        public static FormLink<IQuestGetter> DLC05Init => Construct(0x8a1);
    }
}
