// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class SoundOutputModel
    {
        private static FormLink<ISoundOutputModelGetter> Construct(uint id) => new FormLink<ISoundOutputModelGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISoundOutputModelGetter> DLC05SOMCompound_Paintball_Mono_C_01400x10000 => Construct(0xf12);
        public static FormLink<ISoundOutputModelGetter> DLC05SOMCompound_Paintball_Mono_B_00001x05000 => Construct(0xf11);
        public static FormLink<ISoundOutputModelGetter> DLC05SOMCompound_Paintball_Mono_A_00000x01750 => Construct(0xf10);
        public static FormLink<ISoundOutputModelGetter> DLC05SOMCompound_BallTrackGate_Mono_C_01400x09000 => Construct(0xf00);
        public static FormLink<ISoundOutputModelGetter> DLC05SOMCompound_BallTrackGate_Mono_B_00001x03500 => Construct(0xeff);
        public static FormLink<ISoundOutputModelGetter> DLC05SOMCompound_BallTrackGate_Mono_A_00000x01500 => Construct(0xefe);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05JunkMortarFire_Mono_D_05000x12000 => Construct(0xde8);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05JunkMortarFire_Mono_C_02200x09500 => Construct(0xde7);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05JunkMortarFire_Mono_B_00001x07000 => Construct(0xde6);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05JunkMortarFire_Stereo_A_00000x02800 => Construct(0xde5);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05MortarFireworkEcho_Stereo_B_06000x12000 => Construct(0xdbe);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05MortarFireworkEcho_Stereo_A_00001x09000 => Construct(0xdbd);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05MortarFirework_Mono_E_01800x18000 => Construct(0xc08);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05MortarFirework_Mono_D_05000x12000 => Construct(0xc07);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05MortarFirework_Mono_C_02200x09500 => Construct(0xc06);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05MortarFirework_Mono_B_00001x07000 => Construct(0xc05);
        public static FormLink<ISoundOutputModelGetter> SOMCompound_DLC05MortarFirework_Mono_A_00000x02800 => Construct(0xc04);
    }
}
