// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class TextureSet
    {
        private static FormLink<ITextureSetGetter> Construct(uint id) => new FormLink<ITextureSetGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITextureSetGetter> DLC05_SkinHandMale_Mannequin => Construct(0xe33);
        public static FormLink<ITextureSetGetter> DLC05_SkinBodyFemale_Mannequin => Construct(0xe32);
        public static FormLink<ITextureSetGetter> DLC05_SkinBodyMale_Mannequin => Construct(0xe31);
        public static FormLink<ITextureSetGetter> DLC05DecalPaintHit01White => Construct(0xe0e);
        public static FormLink<ITextureSetGetter> DLC05DecalPaintHit01Yellow => Construct(0xe0d);
        public static FormLink<ITextureSetGetter> DLC05DecalPaintHit01Red => Construct(0xe0c);
        public static FormLink<ITextureSetGetter> DLC05DecalPaintHit01Glow => Construct(0xe0b);
        public static FormLink<ITextureSetGetter> DLC05DecalPaintHit01Orange => Construct(0xe0a);
        public static FormLink<ITextureSetGetter> DLC05DecalPaintHit01Green => Construct(0xe09);
        public static FormLink<ITextureSetGetter> DLC05DecalPaintHit01Blue => Construct(0xe08);
        public static FormLink<ITextureSetGetter> DLC05ImpactDecalPaintSplatter01Glow => Construct(0xcef);
        public static FormLink<ITextureSetGetter> DLC05ImpactDecalPaintSplatter01White => Construct(0xcee);
        public static FormLink<ITextureSetGetter> DLC05ImpactDecalPaintSplatter01Red => Construct(0xced);
        public static FormLink<ITextureSetGetter> DLC05ImpactDecalPaintSplatter01Orange => Construct(0xcec);
        public static FormLink<ITextureSetGetter> DLC05ImpactDecalPaintSplatter01Yellow => Construct(0xceb);
        public static FormLink<ITextureSetGetter> DLC05ImpactDecalPaintSplatter01Green => Construct(0xcea);
        public static FormLink<ITextureSetGetter> DLC05ImpactDecalPaintSplatter01Blue => Construct(0xce9);
    }
}
