// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Workshop02
{
    public static class Transform
    {
        private static FormLink<ITransformGetter> Construct(uint id) => new FormLink<ITransformGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITransformGetter> DLC05FireworkFlareTransform => Construct(0xf34);
        public static FormLink<ITransformGetter> DLC05_workshop_Builder01 => Construct(0xda4);
        public static FormLink<ITransformGetter> DLC05FireworkTransform => Construct(0xd8f);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsPrefab01 => Construct(0xd25);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsGarageDoor01 => Construct(0xd09);
        public static FormLink<ITransformGetter> DLC05WorkshopMarqueeLetter => Construct(0xce0);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsPost02 => Construct(0xc3a);
        public static FormLink<ITransformGetter> DLC05_workshop_JunkMortar01 => Construct(0xc27);
        public static FormLink<ITransformGetter> DLC05_workshop_WorkshopBuildingWarehouseIcon => Construct(0xbfa);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrackSplit01 => Construct(0xbf9);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrackFloorFunnelEdge01 => Construct(0xbf8);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrackCurve03 => Construct(0xbf7);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrackCurve02 => Construct(0xbf6);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrackCurve01 => Construct(0xbf5);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrackSupport01 => Construct(0xbf4);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrack02 => Construct(0xbf3);
        public static FormLink<ITransformGetter> DLC05_workshop_ConveyorDiverter01 => Construct(0xbf1);
        public static FormLink<ITransformGetter> DLC05_workshop_ConveyorYSplit01 => Construct(0xbf0);
        public static FormLink<ITransformGetter> DLC05_workshop_ConveyorRamp01 => Construct(0xbef);
        public static FormLink<ITransformGetter> DLC05_workshop_ConveyorRollersStr01 => Construct(0xbee);
        public static FormLink<ITransformGetter> DLC05_workshop_ConveyorRollers01 => Construct(0xbed);
        public static FormLink<ITransformGetter> DLC05_workshop_ConveyorLTurn01 => Construct(0xbec);
        public static FormLink<ITransformGetter> DLC05_workshop_BoxcarKit02 => Construct(0xbea);
        public static FormLink<ITransformGetter> DLC05_workshop_BoxcarDoor => Construct(0xbe9);
        public static FormLink<ITransformGetter> DLC05_workshop_Elevator4Floor => Construct(0xbe8);
        public static FormLink<ITransformGetter> DLC05_workshop_Elevator3Floor => Construct(0xbe7);
        public static FormLink<ITransformGetter> DLC05_workshop_Elevator2Floor => Construct(0xbe6);
        public static FormLink<ITransformGetter> DLC05_workshop_FiringTarget01 => Construct(0xbdd);
        public static FormLink<ITransformGetter> DLC05_workshop_StationaryGun => Construct(0xbdc);
        public static FormLink<ITransformGetter> DLC05_workshop_WorkshopRifleRackSmall => Construct(0xbc8);
        public static FormLink<ITransformGetter> DLC05_workshop_WorkshopPistolRackSmall => Construct(0xbc7);
        public static FormLink<ITransformGetter> DLC05_workshop_ConduitSwitch01 => Construct(0xb58);
        public static FormLink<ITransformGetter> DLC05_workshop_ConduitFloorToCeil02 => Construct(0xb57);
        public static FormLink<ITransformGetter> DLC05_workshop_ConduitFloorToCeil01 => Construct(0xb56);
        public static FormLink<ITransformGetter> DLC05_workshop_ConduitBox01 => Construct(0xb1e);
        public static FormLink<ITransformGetter> DLC05_workshop_Conduit01 => Construct(0xb1d);
        public static FormLink<ITransformGetter> DLC05_workshop_ConveyorStr01 => Construct(0xb0b);
        public static FormLink<ITransformGetter> DLC05_workshop_FireworkMortar01 => Construct(0xa46);
        public static FormLink<ITransformGetter> DLC05_workshop_PitchingMachine01 => Construct(0xa45);
        public static FormLink<ITransformGetter> DLC05_workshop_Hopper01 => Construct(0xa44);
        public static FormLink<ITransformGetter> DLC05_workshop_WksDisplayCase01 => Construct(0xa40);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsWallHalfCorPref02 => Construct(0xa34);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsWallHalfCorPref01 => Construct(0xa33);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsWallCorPref01 => Construct(0xa32);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsRoofPrefB01 => Construct(0xa31);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsRoofPrefA01 => Construct(0xa30);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsRoofPref01 => Construct(0xa2f);
        public static FormLink<ITransformGetter> DLC05_workshop_ArmorRack01 => Construct(0xa2c);
        public static FormLink<ITransformGetter> DLC05_workshop_WeaponStand01 => Construct(0xa2b);
        public static FormLink<ITransformGetter> DLC05_workshop_PowerArmorDisplay01 => Construct(0xa28);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrackBall01 => Construct(0xa1d);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffWatchtowerB => Construct(0xa1c);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffWatchtowerA => Construct(0xa1b);
        public static FormLink<ITransformGetter> DLC05_workshop_PosterBFrame => Construct(0x9f8);
        public static FormLink<ITransformGetter> DLC05_workshop_PosterAFrame => Construct(0x9f7);
        public static FormLink<ITransformGetter> DLC05_workshop_ClockNuka => Construct(0x9f6);
        public static FormLink<ITransformGetter> DLC05_workshop_WksBallTrack01 => Construct(0x993);
        public static FormLink<ITransformGetter> DLC05_workshop_BoxcarKit01 => Construct(0x949);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffStairHalf => Construct(0x918);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffStairAB => Construct(0x917);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffRamp => Construct(0x916);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffRailx2 => Construct(0x915);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffRailx1 => Construct(0x914);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffPlatform2x2 => Construct(0x913);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffPlatform1x2 => Construct(0x912);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffPlatform1x1 => Construct(0x911);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffFrame2x2x1 => Construct(0x910);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffFrame2x1x1 => Construct(0x90f);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffFrame2x2x2 => Construct(0x90e);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffFrame1x2x2 => Construct(0x90d);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffFrame1x2x1 => Construct(0x90c);
        public static FormLink<ITransformGetter> DLC05_workshop_ScaffFrame1x1x1 => Construct(0x90b);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsRoofCupola01 => Construct(0x8cb);
        public static FormLink<ITransformGetter> DLC05_workshop_WorkshopPistolRack => Construct(0x8aa);
        public static FormLink<ITransformGetter> DLC05_workshop_WorkshopWeaponRack => Construct(0x8a0);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsPost01 => Construct(0x89d);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsDoor01 => Construct(0x853);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsStairs02 => Construct(0x852);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsStairs01 => Construct(0x851);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsWallTop02 => Construct(0x850);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsWallTop01 => Construct(0x84f);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsWall01 => Construct(0x84e);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsRoof01 => Construct(0x84d);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsFloor02 => Construct(0x84c);
        public static FormLink<ITransformGetter> DLC05_workshop_WrhsFloor01 => Construct(0x84b);
    }
}
