// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class CombatStyle
    {
        private static FormLink<ICombatStyleGetter> Construct(uint id) => new FormLink<ICombatStyleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ICombatStyleGetter> DLC04_csOswald => Construct(0x4a6c1);
        public static FormLink<ICombatStyleGetter> DLC04csNukatron => Construct(0x2136f);
        public static FormLink<ICombatStyleGetter> DLC04csMrHandyMister => Construct(0x1fafe);
        public static FormLink<ICombatStyleGetter> DLC04_csRadRat => Construct(0x138f8);
        public static FormLink<ICombatStyleGetter> DLC04_csRadAnt => Construct(0x138f1);
        public static FormLink<ICombatStyleGetter> DLC04_csSwarm => Construct(0x138b5);
        public static FormLink<ICombatStyleGetter> DLC04_csCaveCricket => Construct(0x138b4);
        public static FormLink<ICombatStyleGetter> DLC04_csBloodworm => Construct(0x138b3);
        public static FormLink<ICombatStyleGetter> DLC04RaiderOverboss_csRangedFullOffense => Construct(0xa572);
        public static FormLink<ICombatStyleGetter> DLC04RaiderOverboss_csRangedDefensive => Construct(0xa532);
        public static FormLink<ICombatStyleGetter> DLC04RaiderOverboss_csMeleeFullOffense => Construct(0xa531);
    }
}
