// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class DialogBranch
    {
        private static FormLink<IDialogBranchGetter> Construct(uint id) => new FormLink<IDialogBranchGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDialogBranchGetter> DLC04MQ04Branch => Construct(0x143d2);
        public static FormLink<IDialogBranchGetter> DLC04RaidWipeOutBranch => Construct(0xdbd2);
        public static FormLink<IDialogBranchGetter> DLC04RaidChaseOffBranch => Construct(0x143ce);
        public static FormLink<IDialogBranchGetter> DLC04RaidSubdueBranch => Construct(0x16e6e);
        public static FormLink<IDialogBranchGetter> DLC04_RQ_KillRivalBoss_Branch => Construct(0x1804b);
        public static FormLink<IDialogBranchGetter> DLC04_RQ_DialogueBranch => Construct(0x18049);
        public static FormLink<IDialogBranchGetter> DLC04RaidCoerceBranch => Construct(0x190ee);
        public static FormLink<IDialogBranchGetter> DLC04RaidCoerceBrawlPlayerWins => Construct(0x192f0);
        public static FormLink<IDialogBranchGetter> DLC04RaidCoerceBrawlPlayerLoses => Construct(0x192f1);
        public static FormLink<IDialogBranchGetter> DLC04SelectRaidQuestBranch => Construct(0x1b030);
        public static FormLink<IDialogBranchGetter> DLC04_RQ_StealCache_Branch => Construct(0x1b1b4);
        public static FormLink<IDialogBranchGetter> DLC04_RQ_DefendCache_Branch => Construct(0x2198a);
        public static FormLink<IDialogBranchGetter> DLC04COMGageBranch => Construct(0x2aef0);
        public static FormLink<IDialogBranchGetter> DLC04_RQ_KillTroubleMaker_Branch => Construct(0x3234d);
        public static FormLink<IDialogBranchGetter> DLC04_RQ_CollarTroubleMaker_Branch => Construct(0x32ae5);
        public static FormLink<IDialogBranchGetter> DLC04_AO_Comment_Dialogue_Branch => Construct(0x4a5bf);
        public static FormLink<IDialogBranchGetter> DLC04_RQ_CollarRivalBoss_Branch => Construct(0x4bda6);
    }
}
