// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static class Door
    {
        private static FormLink<IDoorGetter> Construct(uint id) => new FormLink<IDoorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDoorGetter> DLC04ShackDoor02 => Construct(0x555f0);
        public static FormLink<IDoorGetter> DLC04ShackDoor01 => Construct(0x555ef);
        public static FormLink<IDoorGetter> DLC04_BottlingPlantGrate => Construct(0x54164);
        public static FormLink<IDoorGetter> DLC04JunkWallDoor01 => Construct(0x53655);
        public static FormLink<IDoorGetter> BLDGMetalGarageDoorComA_NoName => Construct(0x500b7);
        public static FormLink<IDoorGetter> DLC04_DRG_SafeDoor => Construct(0x44991);
        public static FormLink<IDoorGetter> BarnOuthouseDoor01 => Construct(0x44629);
        public static FormLink<IDoorGetter> DLC04_WWPaintedWoodDoorLoadD01 => Construct(0x40b0c);
        public static FormLink<IDoorGetter> DLC04_WWPaintedWoodDoorDoubleLoadD01 => Construct(0x3b11b);
        public static FormLink<IDoorGetter> DLC04SpaceNeedleCageDoor01Door => Construct(0x38a33);
        public static FormLink<IDoorGetter> DLC04SpaceNeedleDoor01 => Construct(0x38a31);
        public static FormLink<IDoorGetter> DLC04GZ_StarportNukaElevatorOuterDoor => Construct(0x32777);
        public static FormLink<IDoorGetter> DLC04GZ_StarportNukaElevatorDoor => Construct(0x32776);
        public static FormLink<IDoorGetter> DLC04UFORideLoadDoor01 => Construct(0x31f98);
        public static FormLink<IDoorGetter> DLC04TransitionDoor_InvisibleDoor02 => Construct(0x25513);
        public static FormLink<IDoorGetter> DLC04TransitionDoor_InvisibleDoor01 => Construct(0x25511);
        public static FormLink<IDoorGetter> DoorGarageDeco01_DLC04 => Construct(0x1ed0f);
        public static FormLink<IDoorGetter> DLC04ZooCageWallTallDoorSingle02 => Construct(0x138d2);
        public static FormLink<IDoorGetter> DLC04ZooCageWallTallDoorSingle01 => Construct(0x138d1);
        public static FormLink<IDoorGetter> FederalistBookcaseDoor01_NoName => Construct(0xd04d);
    }
}
