// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class Explosion
    {
        private static FormLink<IExplosionGetter> Construct(uint id) => new FormLink<IExplosionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IExplosionGetter> DLC04_ThirstZapperQuantumExplosion => Construct(0x5710d);
        public static FormLink<IExplosionGetter> DLC04MisterStreamEnchExplosion => Construct(0x53f8a);
        public static FormLink<IExplosionGetter> DLC04TrapFakeForceExplosion => Construct(0x517bb);
        public static FormLink<IExplosionGetter> DLC04SentryShoulderCherryExplosion => Construct(0x505ea);
        public static FormLink<IExplosionGetter> DLC04PaddleballQuantumExplosion_Radiation => Construct(0x4ea3d);
        public static FormLink<IExplosionGetter> DLC04PaddleballColaExplosion_Radiation => Construct(0x4ea3c);
        public static FormLink<IExplosionGetter> DLC04PaddleballCherryExplosion_Radiation => Construct(0x4ea3b);
        public static FormLink<IExplosionGetter> DLC04RaiderOverboss_FragGrenadeSingleExplosion => Construct(0x4a61b);
        public static FormLink<IExplosionGetter> BloatedBrahminExplosion => Construct(0x489cf);
        public static FormLink<IExplosionGetter> DLC04PaddleballQuantumExplosion => Construct(0x44e94);
        public static FormLink<IExplosionGetter> DLC04PaddleballCherryExplosion => Construct(0x44e93);
        public static FormLink<IExplosionGetter> DLC04PaddleballColaExplosion => Construct(0x44e92);
        public static FormLink<IExplosionGetter> DLC04NukatronColaExplosion => Construct(0x439f8);
        public static FormLink<IExplosionGetter> DLC04_KK_OswaldTeleportExplosion => Construct(0x4239b);
        public static FormLink<IExplosionGetter> DLC04NukaQuantumGrenadeExplosion => Construct(0x40ce1);
        public static FormLink<IExplosionGetter> DLC04NukaCherryGrenadeExplosion => Construct(0x40cdf);
        public static FormLink<IExplosionGetter> DLC04_ThirstZapperExplosionThatPlacesHazard => Construct(0x39540);
        public static FormLink<IExplosionGetter> DLC04_LuckyRabbitsFootExplosion2 => Construct(0x35e77);
        public static FormLink<IExplosionGetter> DLC04_LuckyRabbitsFootExplosion => Construct(0x35e73);
        public static FormLink<IExplosionGetter> DLC04_NukalurkSpawnHatchQueenExpl => Construct(0x34630);
        public static FormLink<IExplosionGetter> DLC04NukalurkSpawnHatchExpl => Construct(0x344fa);
        public static FormLink<IExplosionGetter> DLC04_FragGrenadeMIRVExplosion => Construct(0x33904);
        public static FormLink<IExplosionGetter> DLC04_FragGrenadeMIRVExplosionPack => Construct(0x33902);
        public static FormLink<IExplosionGetter> DLC04NukatronQuantumExplosion => Construct(0x32f5b);
        public static FormLink<IExplosionGetter> DLC04NukatronCherryExplosion => Construct(0x32f5a);
        public static FormLink<IExplosionGetter> DLC04AcidSoakerExplosion => Construct(0x2c81b);
        public static FormLink<IExplosionGetter> DLC04_ThirstZapperSquirtGunExplosion => Construct(0x2bdc5);
        public static FormLink<IExplosionGetter> DLC04_ThirstZapperColaSprayExplosion => Construct(0x2bdc4);
        public static FormLink<IExplosionGetter> DLC04NukaColaMisterExplosion => Construct(0x2bdc0);
        public static FormLink<IExplosionGetter> DLC04DisciplesFrenzyGrenadeExplosion => Construct(0x2618d);
        public static FormLink<IExplosionGetter> DLC04PackScentGrenadeExplosion => Construct(0x25b0c);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionYellow => Construct(0x243ad);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionSilver => Construct(0x243ac);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionRed => Construct(0x243ab);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionPink => Construct(0x243aa);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionGreen => Construct(0x243a9);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionGold => Construct(0x243a8);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionCrackle => Construct(0x243a7);
        public static FormLink<IExplosionGetter> DLC04FireworkExplosionBlue => Construct(0x243a6);
        public static FormLink<IExplosionGetter> DLC04IntimidateGrenadeExplosion => Construct(0x23e64);
        public static FormLink<IExplosionGetter> DLC04SentryShoulderClusterExplosionChild => Construct(0x213a9);
        public static FormLink<IExplosionGetter> DLC04MisterStreamExplosionFX => Construct(0x213a4);
        public static FormLink<IExplosionGetter> DLC04NukaNukeExplosion => Construct(0x19418);
        public static FormLink<IExplosionGetter> DLC04RaiderOverboss_ExplosionDischargeSmall => Construct(0xa554);
        public static FormLink<IExplosionGetter> DLC04RaiderOverboss_ExplosionDischargeLarge => Construct(0xa553);
        public static FormLink<IExplosionGetter> DLC04RaiderOverboss_ExplosionDischargeMAX => Construct(0xa552);
    }
}
