// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class GodRays
    {
        private static FormLink<IGodRaysGetter> Construct(uint id) => new FormLink<IGodRaysGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGodRaysGetter> TestTrailerRays => Construct(0x3969f);
        public static FormLink<IGodRaysGetter> DLC04DustDayRays => Construct(0x30ac9);
    }
}
