// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class HeadPart
    {
        private static FormLink<IHeadPartGetter> Construct(uint id) => new FormLink<IHeadPartGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IHeadPartGetter> DLC04MaleHeadGhoulRearGlowing => Construct(0x383ab);
        public static FormLink<IHeadPartGetter> DLC04GhoulMaleMouthGlowing => Construct(0x383a9);
        public static FormLink<IHeadPartGetter> DLC04MaleHeadGhoulGlowing => Construct(0x383a8);
        public static FormLink<IHeadPartGetter> DLC04MaleEyesGhoulGlowing => Construct(0x383a6);
        public static FormLink<IHeadPartGetter> DLC04HairFemale39_Hairline => Construct(0x1a282);
        public static FormLink<IHeadPartGetter> DLC04HairFemale39 => Construct(0x1a281);
        public static FormLink<IHeadPartGetter> DLC04HairFemale38 => Construct(0x1a280);
        public static FormLink<IHeadPartGetter> DLC04HairFemale38_Hairline2 => Construct(0x1a27f);
        public static FormLink<IHeadPartGetter> DLC04HairFemale38_Hairline1 => Construct(0x1a27e);
        public static FormLink<IHeadPartGetter> DLC04HairMale48_Hairline2 => Construct(0x1a27d);
        public static FormLink<IHeadPartGetter> DLC04HairMale48_Hairline1 => Construct(0x1a27c);
        public static FormLink<IHeadPartGetter> DLC04HairMale48 => Construct(0x1a27b);
        public static FormLink<IHeadPartGetter> DLC04HairFemale40_Scarf => Construct(0x1951b);
        public static FormLink<IHeadPartGetter> DLC04HairFemale40 => Construct(0x1951a);
        public static FormLink<IHeadPartGetter> DLC04HairFemale40_Hairline => Construct(0x19519);
    }
}
