// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static class Location
    {
        private static FormLink<ILocationGetter> Construct(uint id) => new FormLink<ILocationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILocationGetter> DLC04TheParlorLocation => Construct(0x56db3);
        public static FormLink<ILocationGetter> DLC04FizztopMountainLocation => Construct(0x56db2);
        public static FormLink<ILocationGetter> DLC04BradbertonAmphitheaterLocation => Construct(0x55a05);
        public static FormLink<ILocationGetter> DLC04WorkshopHoldingCellLocation => Construct(0x51bad);
        public static FormLink<ILocationGetter> DLC04NukaWorldAirfieldLocation => Construct(0x503bd);
        public static FormLink<ILocationGetter> DLC04BradbertonReservoirLocation => Construct(0x503bc);
        public static FormLink<ILocationGetter> DLC04BradbertonOverpassLocation => Construct(0x503b3);
        public static FormLink<ILocationGetter> DLC04BradbertonLocation => Construct(0x4e130);
        public static FormLink<ILocationGetter> DLC04GalacticZone_StarportNukaLocation => Construct(0x4abae);
        public static FormLink<ILocationGetter> DLC04WildWestMineCartLocation => Construct(0x43958);
        public static FormLink<ILocationGetter> DLC04POISC07Location => Construct(0x42b5a);
        public static FormLink<ILocationGetter> DLC04SafariAdventure_PrimateHouseLocation => Construct(0x337a3);
        public static FormLink<ILocationGetter> DLC04SafariAdventure_BearCaveLocation => Construct(0x337a2);
        public static FormLink<ILocationGetter> DLC04SafariAdventure_WelcomeCenterLocation => Construct(0x337a1);
        public static FormLink<ILocationGetter> DLC04SafariAdventure_ReptileHouseLocation => Construct(0x337a0);
        public static FormLink<ILocationGetter> DLC04CappysCafeLocation => Construct(0x21370);
        public static FormLink<ILocationGetter> DLC04NukaTownUSALocation => Construct(0x1fcec);
        public static FormLink<ILocationGetter> DLC04NukaWorldPowerPlantLocation => Construct(0x1fc81);
        public static FormLink<ILocationGetter> DLC04SafariAdventureLocation => Construct(0x1fc7f);
        public static FormLink<ILocationGetter> DLC04WildWestLocation => Construct(0x1fb1c);
        public static FormLink<ILocationGetter> DLC04GrandchesterMansionLocation => Construct(0x1eb9b);
        public static FormLink<ILocationGetter> DLC04HubologistCampLocation => Construct(0x1ce0c);
        public static FormLink<ILocationGetter> DLC04FunhouseLocation => Construct(0x19559);
        public static FormLink<ILocationGetter> DLC04KiddieKingdomTunnelsLocation => Construct(0x17646);
        public static FormLink<ILocationGetter> DLC04KiddieKingdomLocation => Construct(0x17645);
        public static FormLink<ILocationGetter> DLC04NukacadeLocation => Construct(0x17644);
        public static FormLink<ILocationGetter> DLC04BottlingPlantLocation => Construct(0x17643);
        public static FormLink<ILocationGetter> DLC04JunkyardLocation => Construct(0x1763e);
        public static FormLink<ILocationGetter> DLC04GalacticZone_VaultTecAmongTheStarsLocation => Construct(0x10ca4);
        public static FormLink<ILocationGetter> DLC04GalacticZone_StarlightInterstellarTheaterLocation => Construct(0x10ca3);
        public static FormLink<ILocationGetter> DLC04GalacticZone_RobCoBattlezoneLocation => Construct(0x10ca2);
        public static FormLink<ILocationGetter> DLC04GalacticZone_NukaGalaxyLocation => Construct(0x10c9f);
        public static FormLink<ILocationGetter> DLC04GalacticZoneLocation => Construct(0xe765);
        public static FormLink<ILocationGetter> DLC04GauntletLocation => Construct(0xbd04);
        public static FormLink<ILocationGetter> DLC04NukaWorldWorkshopLocation => Construct(0xbced);
        public static FormLink<ILocationGetter> DLC04NukaStationLocation => Construct(0xb8e5);
        public static FormLink<ILocationGetter> DLC04NukaWorldLocation => Construct(0x8060);
        public static FormLink<ILocationGetter> DLC04ColaCarsLocation => Construct(0x805d);
        public static FormLink<ILocationGetter> DLC04TransitCenterLocation => Construct(0x7ec4);
    }
}
