// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class MagicEffect
    {
        private static FormLink<IMagicEffectGetter> Construct(uint id) => new FormLink<IMagicEffectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMagicEffectGetter> DLC04OswaldInvisibilityEffect => Construct(0x56bf7);
        public static FormLink<IMagicEffectGetter> DLC04EnchMisterStreamEffect => Construct(0x53f8c);
        public static FormLink<IMagicEffectGetter> DLC04NukaKillTrackerDrinkEFFECT => Construct(0x51579);
        public static FormLink<IMagicEffectGetter> DLC04NukaKillTrackerEFFECT => Construct(0x51578);
        public static FormLink<IMagicEffectGetter> DLC04mod_Lining_FieldGen_EMP_MagicEffect => Construct(0x490c6);
        public static FormLink<IMagicEffectGetter> DLC04pa_mod_Lining_FieldGen_Radiation_CloakEffect => Construct(0x4703d);
        public static FormLink<IMagicEffectGetter> DLC04_HC_MysteryMeat_CannibalEffect => Construct(0x46e34);
        public static FormLink<IMagicEffectGetter> DLC04Bot_ReduceCarryWeightEffect => Construct(0x44b39);
        public static FormLink<IMagicEffectGetter> DLC04Bot_FortifyMeleeDamageEffect => Construct(0x44b36);
        public static FormLink<IMagicEffectGetter> DLC04Bot_FortifyCarryWeightEffect => Construct(0x44b35);
        public static FormLink<IMagicEffectGetter> DLC04Bot_FortifyResistEnergyEffect => Construct(0x44b30);
        public static FormLink<IMagicEffectGetter> DLC04Bot_FortifyResistDamageEffect => Construct(0x44b2f);
        public static FormLink<IMagicEffectGetter> DLC04Bot_FortifyRadHealthMaxEffect => Construct(0x44b2e);
        public static FormLink<IMagicEffectGetter> DLC04Bot_FortifyHealthEffect => Construct(0x44b2d);
        public static FormLink<IMagicEffectGetter> DLC04_FortifyLuckCalmex => Construct(0x418d3);
        public static FormLink<IMagicEffectGetter> DLC04GZVaultTec_ExperimentThetaRadsEffect => Construct(0x40ed7);
        public static FormLink<IMagicEffectGetter> DLC04GZVaultTec_ExperimentSubliminalsEffect => Construct(0x40ed6);
        public static FormLink<IMagicEffectGetter> DLC04GZVaultTec_ExperimentAromaEffect => Construct(0x40ed5);
        public static FormLink<IMagicEffectGetter> DLC04GZVaultTec_ExperimentBrainwaveEffect => Construct(0x40ed0);
        public static FormLink<IMagicEffectGetter> DLC04Gauntlet_GasHazardSubsequentEffect => Construct(0x3db50);
        public static FormLink<IMagicEffectGetter> DLC04_PaddleBall_ChanceToDismember => Construct(0x396af);
        public static FormLink<IMagicEffectGetter> DLC04_ReducePerceptionAlcohol => Construct(0x3721e);
        public static FormLink<IMagicEffectGetter> DLC04_AbSwarmRaceEffect => Construct(0x36f79);
        public static FormLink<IMagicEffectGetter> DLC04_NukalurkSpawnMagicEffect => Construct(0x3462f);
        public static FormLink<IMagicEffectGetter> DLC04_PaddleBall_Disarm => Construct(0x2f42d);
        public static FormLink<IMagicEffectGetter> DLC04_PaddleBall_OnHitEffect_Stagger => Construct(0x2f42b);
        public static FormLink<IMagicEffectGetter> DLC04Gauntlet_GasHazardInitialEffect => Construct(0x2d828);
        public static FormLink<IMagicEffectGetter> DLC04ReduceDamageResistEffect => Construct(0x2c81e);
        public static FormLink<IMagicEffectGetter> DLC04_DamageRadiationSelf => Construct(0x2af2a);
        public static FormLink<IMagicEffectGetter> DLC04_AbPerkGhoulish04Effect => Construct(0x28a26);
        public static FormLink<IMagicEffectGetter> DLC04_PerkRaiderDisciplesEffect => Construct(0x2649a);
        public static FormLink<IMagicEffectGetter> DLC04DisciplesFrenzyGrenadeEffect => Construct(0x2618f);
        public static FormLink<IMagicEffectGetter> DLC04IntimidationGrenadeEffect => Construct(0x23e5e);
        public static FormLink<IMagicEffectGetter> DLC04abAnimatronicAlienRaceEffect => Construct(0x1fa9b);
    }
}
