// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static class MovableStatic
    {
        private static FormLink<IMovableStaticGetter> Construct(uint id) => new FormLink<IMovableStaticGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMovableStaticGetter> NukaColaMachineCommercialFxDLC04 => Construct(0x55a4d);
        public static FormLink<IMovableStaticGetter> WaterSplashStream_dlc04NukaQuantumExt => Construct(0x542af);
        public static FormLink<IMovableStaticGetter> WaterStreamMed_nukaDLC04ext => Construct(0x542ae);
        public static FormLink<IMovableStaticGetter> WaterSplashStream_dlc04DirtyWater => Construct(0x542a9);
        public static FormLink<IMovableStaticGetter> WaterStreamSm_dirtyWaterDLC04 => Construct(0x542a8);
        public static FormLink<IMovableStaticGetter> WaterSplashDrips_dlc04NukaQuantum => Construct(0x5429a);
        public static FormLink<IMovableStaticGetter> WaterSplashStream_dlc04NukaQuantumNoRipple => Construct(0x54292);
        public static FormLink<IMovableStaticGetter> WaterDripsSmall_nukaDLC04 => Construct(0x5428f);
        public static FormLink<IMovableStaticGetter> WaterDripsMed_nukaDLC04 => Construct(0x5428e);
        public static FormLink<IMovableStaticGetter> WaterStreamSm_nukaDLC04 => Construct(0x5428b);
        public static FormLink<IMovableStaticGetter> WaterSplashStream_dlc04NukaQuantum => Construct(0x54288);
        public static FormLink<IMovableStaticGetter> WaterStreamMed_nukaDLC04 => Construct(0x54287);
        public static FormLink<IMovableStaticGetter> DLC04GZVaultTecMisters => Construct(0x51e5f);
        public static FormLink<IMovableStaticGetter> DLC04LODlightFX_FireworksDisplayMS => Construct(0x51765);
        public static FormLink<IMovableStaticGetter> DLC04_BarrelTankFlammable_NoDebris => Construct(0x5164e);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_Alien01 => Construct(0x4f348);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_NukaCola => Construct(0x4f347);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_Cappy => Construct(0x4f346);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_Bottle => Construct(0x4f345);
        public static FormLink<IMovableStaticGetter> DLC04_Sign_NukaGirl01 => Construct(0x4b066);
        public static FormLink<IMovableStaticGetter> DLC04PipeGasLeak01 => Construct(0x49516);
        public static FormLink<IMovableStaticGetter> DLC04LightBeamThin01Red => Construct(0x4948c);
        public static FormLink<IMovableStaticGetter> DLC04LightBeamThin01Blue => Construct(0x4948b);
        public static FormLink<IMovableStaticGetter> DLC04BloatedBrahminCorpse02 => Construct(0x489d4);
        public static FormLink<IMovableStaticGetter> DLC04BloatedBrahminCorpse01 => Construct(0x489d3);
        public static FormLink<IMovableStaticGetter> DLC04BloatedBrahmiluffCorpse02 => Construct(0x489d2);
        public static FormLink<IMovableStaticGetter> DLC04BloatedBrahmiluffCorpse01 => Construct(0x489d1);
        public static FormLink<IMovableStaticGetter> DLC04BloatedBrahminCorpse03 => Construct(0x489d0);
        public static FormLink<IMovableStaticGetter> DLC04_FlagWaving_ZooGang02 => Construct(0x46cbf);
        public static FormLink<IMovableStaticGetter> DLC04WW_WindMill01Anim => Construct(0x42e02);
        public static FormLink<IMovableStaticGetter> DLC04FireAlarmLight01 => Construct(0x40cc4);
        public static FormLink<IMovableStaticGetter> DLC04CappyWavingRuinedAnim => Construct(0x401ed);
        public static FormLink<IMovableStaticGetter> DLC04CappyWavingPoseCleanAnim => Construct(0x401ec);
        public static FormLink<IMovableStaticGetter> DLC04BottleWavingPoseCleanAnim => Construct(0x401eb);
        public static FormLink<IMovableStaticGetter> DLC04BottleWavingPoseAnim => Construct(0x401ea);
        public static FormLink<IMovableStaticGetter> DLC04CappyWavingPoseAnim => Construct(0x401e9);
        public static FormLink<IMovableStaticGetter> DLC04BottleWavingPoseRuinedAnim => Construct(0x401e8);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_SherrifBruce => Construct(0x3f67e);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_MissTrixie => Construct(0x3f67c);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_MadMulligan => Construct(0x3f67a);
        public static FormLink<IMovableStaticGetter> DLC04_CutOut_DocPhosphate => Construct(0x3f678);
        public static FormLink<IMovableStaticGetter> AlienTorso => Construct(0x3c111);
        public static FormLink<IMovableStaticGetter> AlienLegs => Construct(0x3c110);
        public static FormLink<IMovableStaticGetter> AlienHead => Construct(0x3c10f);
        public static FormLink<IMovableStaticGetter> AlienArmR => Construct(0x3c10e);
        public static FormLink<IMovableStaticGetter> AlienArmL => Construct(0x3c10d);
        public static FormLink<IMovableStaticGetter> DLC04_GameStand_DuckFiringRange_Ducks => Construct(0x3b8ef);
        public static FormLink<IMovableStaticGetter> DLC04_GameStand_DownACola01_ThreeTargets01 => Construct(0x3b8eb);
        public static FormLink<IMovableStaticGetter> DLC04_GameStand_DownACola01_TwoTargets01 => Construct(0x3b8e9);
        public static FormLink<IMovableStaticGetter> DLC04_KK_Mister01FX => Construct(0x35f22);
        public static FormLink<IMovableStaticGetter> DLC04SplashParkColaStream01 => Construct(0x35f21);
        public static FormLink<IMovableStaticGetter> DLC04_Sign_KingColaCutoutMoveable => Construct(0x3365e);
        public static FormLink<IMovableStaticGetter> DLC04_Sign_MustbethistallMoveable => Construct(0x3365d);
        public static FormLink<IMovableStaticGetter> DLC04_Sign_Mustbethistall_ShortMoveable => Construct(0x3365c);
        public static FormLink<IMovableStaticGetter> DLC04MannequinMaleSpacesuitBase => Construct(0x294ad);
        public static FormLink<IMovableStaticGetter> DLC04PackScentGrenadeSpawnedObject => Construct(0x25b0d);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowEdn01_ValleyDirt_WetMud_FX => Construct(0x10f20);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowCurve02_ValleyDirt_WetMud_FX => Construct(0x10f1f);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowCurve01_ValleyDirt_WetMud_FX => Construct(0x10f1e);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowStr03_ValleyDirt_WetMud_FX => Construct(0x10f1d);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowFork02_ValleyDirt_WetMud_FX => Construct(0x10f1c);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowFork01_ValleyDirt_WetMud_FX => Construct(0x10f18);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowStr02_ValleyDirt_WetMud_FX => Construct(0x10f17);
        public static FormLink<IMovableStaticGetter> ShaderTest => Construct(0x10f15);
        public static FormLink<IMovableStaticGetter> DLC04_DrainageFlowStr01_ValleyDirt_WetMud_FX => Construct(0x10f13);
        public static FormLink<IMovableStaticGetter> WaterRisingTest => Construct(0xd35d);
        public static FormLink<IMovableStaticGetter> DLC04_FlagWaving_ZooGang => Construct(0xae69);
        public static FormLink<IMovableStaticGetter> DLC04_FlagWaving_Operators => Construct(0xae67);
        public static FormLink<IMovableStaticGetter> DLC04_FlagWaving_Disciples => Construct(0xae65);
    }
}
