// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class PackIn
    {
        private static FormLink<IPackInGetter> Construct(uint id) => new FormLink<IPackInGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPackInGetter> DLC04_KK_GhoulAmbushPackin => Construct(0x55ea4);
        public static FormLink<IPackInGetter> DLC04RideConsolePackin => Construct(0x5389f);
        public static FormLink<IPackInGetter> DLC04_NukaColaMachine => Construct(0x51005);
        public static FormLink<IPackInGetter> DLC04_Dummy_NukaCola => Construct(0x50ffc);
        public static FormLink<IPackInGetter> DLC04HighTechTableLamp => Construct(0x49f53);
        public static FormLink<IPackInGetter> DLC04RedRoundLight => Construct(0x49517);
        public static FormLink<IPackInGetter> DLC04BlueRoundLight => Construct(0x49511);
        public static FormLink<IPackInGetter> DLC04StreetLampOn02PackIn => Construct(0x47826);
        public static FormLink<IPackInGetter> DLC04StreetLampOn01PackIn => Construct(0x47825);
        public static FormLink<IPackInGetter> DLC04HighCeilingLight => Construct(0x46e4f);
        public static FormLink<IPackInGetter> DLC04IndCatLightPackIn => Construct(0x46ddb);
        public static FormLink<IPackInGetter> DLC04OilLampPackInNS => Construct(0x46bed);
        public static FormLink<IPackInGetter> DLC04_FireAlarm03_SC01PackIn => Construct(0x43150);
        public static FormLink<IPackInGetter> DLC04_FireAlarm02_SC01PackIn => Construct(0x43142);
        public static FormLink<IPackInGetter> DLC04_FireAlarm01_SC01PackIn => Construct(0x43135);
        public static FormLink<IPackInGetter> DLC04_PosterFramePackIn => Construct(0x4055e);
        public static FormLink<IPackInGetter> DLC04_KK_RadMisterPackinNEW => Construct(0x3e511);
        public static FormLink<IPackInGetter> LvlStingwingAmbushNestGroundPackin => Construct(0x3da59);
        public static FormLink<IPackInGetter> LvlStingwingAmbushNestCeilingPackin => Construct(0x3da53);
        public static FormLink<IPackInGetter> LvlStingwingAmbushNestWallPackin => Construct(0x3da45);
        public static FormLink<IPackInGetter> DLC04_Sign_MustbethistallShort => Construct(0x33669);
        public static FormLink<IPackInGetter> DLC04_Sign_Mustbethistall01 => Construct(0x33666);
        public static FormLink<IPackInGetter> DLC04RobotLiftPackIn => Construct(0x32f7d);
        public static FormLink<IPackInGetter> FloraFeverBlossom02PackIn => Construct(0x25510);
        public static FormLink<IPackInGetter> FloraFeverBlossom01PackIn => Construct(0x2550d);
        public static FormLink<IPackInGetter> DLC04_BottlingPlantBuilding01 => Construct(0x24f22);
        public static FormLink<IPackInGetter> DLC04_BottlingPlantBuilding => Construct(0x24edb);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_Sm_06 => Construct(0x241a2);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_Sm_05 => Construct(0x24199);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_Sm_04 => Construct(0x24191);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_Sm_03 => Construct(0x24187);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_Sm_02 => Construct(0x2417c);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_Sm_01 => Construct(0x24172);
        public static FormLink<IPackInGetter> DLC04LvlBloodwormAmbushPackin => Construct(0x1e856);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_10 => Construct(0x1dd88);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_09 => Construct(0x1dd78);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_08 => Construct(0x1dd69);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_07 => Construct(0x1dd64);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_06 => Construct(0x1dd56);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_05 => Construct(0x1dd4a);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_04 => Construct(0x1dd3c);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_03 => Construct(0x1dd36);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_020 => Construct(0x1dd29);
        public static FormLink<IPackInGetter> DLC04_TrashLoot_01 => Construct(0x1dd1a);
        public static FormLink<IPackInGetter> DLC04_NUK001_ColaCarsRafterSegment2 => Construct(0x9025);
        public static FormLink<IPackInGetter> DLC04_NUK001_ColaCarsRafterSegment => Construct(0x9018);
    }
}
