// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static class Race
    {
        private static FormLink<IRaceGetter> Construct(uint id) => new FormLink<IRaceGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IRaceGetter> DLC04GorillaRace => Construct(0x4cbce);
        public static FormLink<IRaceGetter> DLC04_DeathclawAdditiveSupgraphRace => Construct(0x3e565);
        public static FormLink<IRaceGetter> DeathclawRaceCOPY0000 => Construct(0x3e562);
        public static FormLink<IRaceGetter> DLC04_GatorclawRace => Construct(0x3637a);
        public static FormLink<IRaceGetter> DLC04_StingwingRace => Construct(0x33169);
        public static FormLink<IRaceGetter> DLC04_BrahmiluffRace => Construct(0x23435);
        public static FormLink<IRaceGetter> DLC04PowerArmorRaceAdditiveSubGraphData => Construct(0x1a283);
        public static FormLink<IRaceGetter> DLC04_AnimatronicAlienRace => Construct(0x19126);
        public static FormLink<IRaceGetter> TestDLC04AnimatronicHumanRace => Construct(0xeff4);
        public static FormLink<IRaceGetter> DLC04DeathclawRaceQuantum => Construct(0xd329);
        public static FormLink<IRaceGetter> DLC04_RadAntRace => Construct(0xce5e);
        public static FormLink<IRaceGetter> DLC04_RadRatRace => Construct(0xc606);
        public static FormLink<IRaceGetter> DLC04_SwarmRace => Construct(0xb028);
        public static FormLink<IRaceGetter> DLC04_CaveCricketRace => Construct(0xaafe);
        public static FormLink<IRaceGetter> DLC04_HumanRaceSubgraphDataAdditive => Construct(0xa6c3);
        public static FormLink<IRaceGetter> DLC04_BloodwormRace => Construct(0xa1a6);
    }
}
