// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class Region
    {
        private static FormLink<IRegionGetter> Construct(uint id) => new FormLink<IRegionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IRegionGetter> DLC04AudioNukaWorldMarket => Construct(0x57127);
        public static FormLink<IRegionGetter> DLC04AudioNukaWorldAmpitheater => Construct(0x57124);
        public static FormLink<IRegionGetter> DLC04MarketBorder => Construct(0x551e3);
        public static FormLink<IRegionGetter> DLC04AmphitheaterBorder => Construct(0x54151);
        public static FormLink<IRegionGetter> DLC04TransitStationRegion => Construct(0x53bcc);
        public static FormLink<IRegionGetter> DLC04AudioIntJunkyardUFO => Construct(0x51c85);
        public static FormLink<IRegionGetter> DLC04CommonwealthNukaTransitCenter => Construct(0x4f5ed);
        public static FormLink<IRegionGetter> DLC04POILD01 => Construct(0x4b751);
        public static FormLink<IRegionGetter> DLC04ParkShared07 => Construct(0x488b6);
        public static FormLink<IRegionGetter> DLC04ParkShared06 => Construct(0x4704b);
        public static FormLink<IRegionGetter> DLC04ParkShared05 => Construct(0x44fe1);
        public static FormLink<IRegionGetter> Region123 => Construct(0x43b74);
        public static FormLink<IRegionGetter> NukaTransit => Construct(0x43b73);
        public static FormLink<IRegionGetter> DLC04AudioExtNukaWorldInnerNukaTown => Construct(0x40d50);
        public static FormLink<IRegionGetter> DLC04HubRegion => Construct(0x3f700);
        public static FormLink<IRegionGetter> DLC04AudioExtNukaWorldInnerKiddie => Construct(0x3b51a);
        public static FormLink<IRegionGetter> DLC04AudioExtNukaWorldInnerSafari => Construct(0x378b7);
        public static FormLink<IRegionGetter> DLC04AudioExtNukaWorldInnerGalactic => Construct(0x32965);
        public static FormLink<IRegionGetter> DLC04AudioExtNukaWorldInnerWestern => Construct(0x30ee6);
        public static FormLink<IRegionGetter> DLC04AudioExtNukaWorldInner => Construct(0x28a28);
        public static FormLink<IRegionGetter> DLC04AudioExtNukaWorldOuter => Construct(0x28a27);
        public static FormLink<IRegionGetter> NukaWorldJunkyard => Construct(0x26227);
        public static FormLink<IRegionGetter> DLC04ParkShared04 => Construct(0x23e8c);
        public static FormLink<IRegionGetter> DLC04ParkShared03 => Construct(0x23e8b);
        public static FormLink<IRegionGetter> DLC04ParkShared02 => Construct(0x23e8a);
        public static FormLink<IRegionGetter> DLC04ParkShared01 => Construct(0x23e89);
        public static FormLink<IRegionGetter> DLC04NukaBorderDUPLICATE000 => Construct(0xb907);
        public static FormLink<IRegionGetter> DLC04NukaBorder => Construct(0xa6dc);
    }
}
