// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class NukaWorld
{
    public static partial class SoundMarker
    {
        private static FormLink<ISoundMarkerGetter> Construct(uint id) => new FormLink<ISoundMarkerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersIdleLowOneShotmarker => Construct(0x5711f);
        public static FormLink<ISoundMarkerGetter> DLC04OBJArcadePrizeDispenserActiveMusicLPmarker => Construct(0x56fb5);
        public static FormLink<ISoundMarkerGetter> DLC04MUSJingleAmbienceSpotBInstrLPmarker => Construct(0x56f31);
        public static FormLink<ISoundMarkerGetter> DLC04MUSJingleAmbienceSpotAFullLPmarker => Construct(0x56f2f);
        public static FormLink<ISoundMarkerGetter> DLC04OBJNukaPowerPlantPowerOnmarker => Construct(0x56ea7);
        public static FormLink<ISoundMarkerGetter> DLC04AMBIntKiddieGeneratorTunnelALPmarker => Construct(0x56e20);
        public static FormLink<ISoundMarkerGetter> DLC04AMBMonorailStationPAMuzakNukaWorldLPmarker => Construct(0x56d3f);
        public static FormLink<ISoundMarkerGetter> DLC04AMBMonorailStationPAMuzakLPmarker => Construct(0x56d3c);
        public static FormLink<ISoundMarkerGetter> DLC04AMBInteriorJunkyardUFOSpotRSpaceMarker => Construct(0x56cb1);
        public static FormLink<ISoundMarkerGetter> DLC04AMBInteriorJunkyardUFOSpotRHighMarker => Construct(0x56cb0);
        public static FormLink<ISoundMarkerGetter> DLC04OBJWorkshopGeneratorSmallLPMmarker => Construct(0x56c5d);
        public static FormLink<ISoundMarkerGetter> DLC04AMBArcadeRoomtoneMusicLPmarker => Construct(0x56b85);
        public static FormLink<ISoundMarkerGetter> DLC04AMBFunHousePlatform02LPmarker => Construct(0x53519);
        public static FormLink<ISoundMarkerGetter> DLC04AMBFunHousePlatform01LPmarker => Construct(0x53516);
        public static FormLink<ISoundMarkerGetter> DLC04AMBFunHouseFloorSpiralLPmarker => Construct(0x53512);
        public static FormLink<ISoundMarkerGetter> DLC04AMBFunHouseTunnelLPmarker => Construct(0x534fe);
        public static FormLink<ISoundMarkerGetter> DLC04AMBWaterfallSplatterLargeLPmarker => Construct(0x528cf);
        public static FormLink<ISoundMarkerGetter> DLC04AMBExtWindFerrisWheelTopLPmarker => Construct(0x5204c);
        public static FormLink<ISoundMarkerGetter> DLC04OBJRideActiveE2DLPmarker => Construct(0x52042);
        public static FormLink<ISoundMarkerGetter> DLC04OBJRideActiveDLPMmarker => Construct(0x52039);
        public static FormLink<ISoundMarkerGetter> DLC04OBJRideActiveC2DLPMmarker => Construct(0x52038);
        public static FormLink<ISoundMarkerGetter> DLC04OBJRideActiveB2DLPMmarker => Construct(0x52037);
        public static FormLink<ISoundMarkerGetter> DLC04OBJRideJunkyardUFOExteriorALPMmarker => Construct(0x51656);
        public static FormLink<ISoundMarkerGetter> DLC04OBJRideSpotRCreakAmarker => Construct(0x5100b);
        public static FormLink<ISoundMarkerGetter> DLC04OBJRideActiveALPMmarker => Construct(0x51009);
        public static FormLink<ISoundMarkerGetter> DLC04AMBExtMetalCreakingWindmillmarker => Construct(0x50356);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecReactorHumInteriorLPmarker => Construct(0x4d473);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecScannerRadiationVaultDLPmarker => Construct(0x4d40b);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecScannerRadiationVaultCLPmarker => Construct(0x4d40a);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecScannerRadiationVaultBLPmarker => Construct(0x4d409);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecScannerRadiationVaultALPmarker => Construct(0x4d408);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecSubliminalMessageCmarker => Construct(0x4cbb3);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecSubliminalMessageBmarker => Construct(0x4cbb2);
        public static FormLink<ISoundMarkerGetter> DLC04QSTGZVaultTecSubliminalMessageAmarker => Construct(0x4cbb1);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersMockingLPMmarker => Construct(0x46b37);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersSurpriseSmallmarker => Construct(0x46b36);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersCheerTriumphmarker => Construct(0x46b35);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersCheerSmallmarker => Construct(0x46b34);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersBooSmallmarker => Construct(0x46b33);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersCheerMediummarker => Construct(0x46b32);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersBooMediummarker => Construct(0x46b31);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersSpotAnimalAmarker => Construct(0x4342b);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersSpotBirdEmarker => Construct(0x43429);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersSpotBirdDmarker => Construct(0x43428);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersSpotBirdCmarker => Construct(0x43427);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersSpotBirdBmarker => Construct(0x43426);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersSpotBirdAmarker => Construct(0x43425);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersLoopBirdDLPmarker => Construct(0x43424);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersLoopBirdCLPmarker => Construct(0x43423);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersLoopBirdBLPmarker => Construct(0x43422);
        public static FormLink<ISoundMarkerGetter> DLC04AMBSafariSpeakersLoopBirdALPmarker => Construct(0x43421);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersIdleLowLPMmarker => Construct(0x42b79);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersIdleHighLPMmarker => Construct(0x42b78);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersWildCheeringmarker => Construct(0x42b6e);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersUncertainMurmurmarker => Construct(0x42b6c);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersShockedGaspsmarker => Construct(0x42b6a);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersHesitantCheeringmarker => Construct(0x42b68);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersHalfheartedApplausemarker => Construct(0x42b66);
        public static FormLink<ISoundMarkerGetter> DLC04GauntletRaidersChantDeathmarker => Construct(0x42b64);
        public static FormLink<ISoundMarkerGetter> DLC04AMBDiamondCityCanvasSheetingmarker => Construct(0x40d51);
        public static FormLink<ISoundMarkerGetter> DLC04OBJAlarmFire2DLPmarkerExterior => Construct(0x407cb);
        public static FormLink<ISoundMarkerGetter> AMBWaterfallSplatterSmallLPmarker => Construct(0x3da97);
        public static FormLink<ISoundMarkerGetter> DLC04OBJAlarmFireSingle2Dmarker => Construct(0x3c5ce);
        public static FormLink<ISoundMarkerGetter> DLC04OBJAlarmFire2DLPmarker => Construct(0x3c5cd);
        public static FormLink<ISoundMarkerGetter> DLC04OBJStarStreakCoasterActive2DLPMmarker => Construct(0x3c109);
        public static FormLink<ISoundMarkerGetter> DLC04OBJStarStreakActive2DLPMmarker => Construct(0x3c105);
        public static FormLink<ISoundMarkerGetter> DLC04AMBExtMetalCreakingmarker => Construct(0x3b58c);
        public static FormLink<ISoundMarkerGetter> DLC04AMBIntAlarmRobotLift2DLPMmarker => Construct(0x32f8d);
        public static FormLink<ISoundMarkerGetter> DLC04AMBIntSpotSodaFizzALPMarker => Construct(0x32a65);
    }
}
