// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static class AimModel
    {
        private static FormLink<IAimModelGetter> Construct(uint id) => new FormLink<IAimModelGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAimModelGetter> DLC01AssaultronHeadCharging_AM => Construct(0x1155);
        public static FormLink<IAimModelGetter> DLC01LightningLobber_AM => Construct(0xfe5);
    }
}
