// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static partial class ArmorAddon
    {
        private static FormLink<IArmorAddonGetter> Construct(uint id) => new FormLink<IArmorAddonGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IArmorAddonGetter> DLC01_TurretSpotlightWorkshopLightLongAA => Construct(0x10a5e);
        public static FormLink<IArmorAddonGetter> DLC01_EyeBotWholeAA_Mechanist => Construct(0xf8e5);
        public static FormLink<IArmorAddonGetter> DLC01_AA_Power_T60_Tesla_Arm_Left => Construct(0xc57e);
        public static FormLink<IArmorAddonGetter> DLC01_AA_Power_T60_Tesla_Arm_Right => Construct(0xc57d);
        public static FormLink<IArmorAddonGetter> DLC01_AA_Power_T60_Tesla_Torso => Construct(0xc57c);
        public static FormLink<IArmorAddonGetter> DLC01_AA_MechanistHelmet => Construct(0x8bc2);
        public static FormLink<IArmorAddonGetter> DLC01_AA_ClothesMechanistArmor => Construct(0x8bc0);
        public static FormLink<IArmorAddonGetter> RoboBrainWhole => Construct(0x8bba);
        public static FormLink<IArmorAddonGetter> AA_Robot_Torso_Medium => Construct(0x8659);
        public static FormLink<IArmorAddonGetter> AA_Robot_Torso_Light => Construct(0x8658);
        public static FormLink<IArmorAddonGetter> AA_Robot_Torso_Heavy => Construct(0x8657);
        public static FormLink<IArmorAddonGetter> AA_Robot_Leg_Right_1_Heavy => Construct(0x8656);
        public static FormLink<IArmorAddonGetter> AA_Robot_Leg_Right_1_Medium => Construct(0x8655);
        public static FormLink<IArmorAddonGetter> AA_Robot_Leg_Left_1_Heavy => Construct(0x8654);
        public static FormLink<IArmorAddonGetter> AA_Robot_Leg_Left_1_Medium => Construct(0x8653);
        public static FormLink<IArmorAddonGetter> AA_Robot_Arm_Right_1_Heavy => Construct(0x8652);
        public static FormLink<IArmorAddonGetter> AA_Robot_Arm_Right_1_Medium => Construct(0x8651);
        public static FormLink<IArmorAddonGetter> AA_Robot_Arm_Left_1_Heavy => Construct(0x8650);
        public static FormLink<IArmorAddonGetter> AA_Robot_Arm_Left_1_Medium => Construct(0x864f);
        public static FormLink<IArmorAddonGetter> AA_Robot_Helmet_Sentrybot => Construct(0x864d);
        public static FormLink<IArmorAddonGetter> AA_Robot_Helmet_Eyebot => Construct(0x864b);
        public static FormLink<IArmorAddonGetter> AA_Robot_Helmet_Assaultron => Construct(0x8649);
        public static FormLink<IArmorAddonGetter> AA_Robot_Leg_Left_1_Lite => Construct(0x8647);
        public static FormLink<IArmorAddonGetter> AA_Robot_Leg_Right_1_Lite => Construct(0x8645);
        public static FormLink<IArmorAddonGetter> AA_Robot_Arm_Left_1_Lite => Construct(0x8643);
        public static FormLink<IArmorAddonGetter> AA_Robot_Arm_Right_1_Lite => Construct(0x8641);
        public static FormLink<IArmorAddonGetter> AA_Robot_Torso_01 => Construct(0x8640);
        public static FormLink<IArmorAddonGetter> DLC01_TurretSpotlightWorkshopLightAA => Construct(0x263f);
        public static FormLink<IArmorAddonGetter> DLC01_TurretSpotlightWorkshopAA => Construct(0x263e);
    }
}
