// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static class BodyPartData
    {
        private static FormLink<IBodyPartDataGetter> Construct(uint id) => new FormLink<IBodyPartDataGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBodyPartDataGetter> MrHandyCreateABotBodyPartData => Construct(0x9a19);
        public static FormLink<IBodyPartDataGetter> RoboBrainBodyPartData => Construct(0x3dea);
        public static FormLink<IBodyPartDataGetter> DLC01_TurretBubbleBodyPartData => Construct(0x287c);
    }
}
