// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static partial class CombatStyle
    {
        private static FormLink<ICombatStyleGetter> Construct(uint id) => new FormLink<ICombatStyleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ICombatStyleGetter> DLC01csRobobrain => Construct(0x87b4);
        public static FormLink<ICombatStyleGetter> DLC01MBattle_csMechTrashbot => Construct(0x7885);
        public static FormLink<ICombatStyleGetter> DLC01MBattle_csMechSentryMelee => Construct(0x7846);
        public static FormLink<ICombatStyleGetter> DLC01MBattle_csMechSentryTurret => Construct(0x7845);
        public static FormLink<ICombatStyleGetter> DLC01csWorkbenchBot => Construct(0x3e0e);
        public static FormLink<ICombatStyleGetter> DLC01csWorkbenchBotMrHandy => Construct(0x3e0d);
        public static FormLink<ICombatStyleGetter> DLC01csWorkbenchBotSentry => Construct(0x3e0c);
        public static FormLink<ICombatStyleGetter> DLC01csWorkbenchBotRoboBrain => Construct(0x3e0b);
        public static FormLink<ICombatStyleGetter> DLC01csWorkbenchBotProtectron => Construct(0x3e0a);
        public static FormLink<ICombatStyleGetter> DLC01csWorkbenchBotAssaultron => Construct(0x3e09);
        public static FormLink<ICombatStyleGetter> DLC01csSparks_Suicide => Construct(0x2106);
        public static FormLink<ICombatStyleGetter> DLC01csSparks => Construct(0x1f05);
        public static FormLink<ICombatStyleGetter> DLC01csMechBot => Construct(0x1a84);
        public static FormLink<ICombatStyleGetter> DLC01csMechanist => Construct(0x8b9);
    }
}
