// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static class InstanceNamingRules
    {
        private static FormLink<IInstanceNamingRulesGetter> Construct(uint id) => new FormLink<IInstanceNamingRulesGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IInstanceNamingRulesGetter> DLC01dn_LightningGun => Construct(0xf5a5);
        public static FormLink<IInstanceNamingRulesGetter> DLC01dn_PowerArmor => Construct(0xe6f9);
    }
}
