// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static partial class MaterialSwap
    {
        private static FormLink<IMaterialSwapGetter> Construct(uint id) => new FormLink<IMaterialSwapGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMaterialSwapGetter> DLC01GlassTileForDark => Construct(0x1250);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BasePink => Construct(0x103ca);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseUnpainted => Construct(0xfe64);
        public static FormLink<IMaterialSwapGetter> DLC01BldBrickIndFloorMedicalTile02Swap => Construct(0xfa07);
        public static FormLink<IMaterialSwapGetter> DLC01ProtectronPodDarkGlass01 => Construct(0xf90c);
        public static FormLink<IMaterialSwapGetter> GreyBrainSwap01 => Construct(0xc0c4);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseYellow => Construct(0xae37);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseBlue => Construct(0xae36);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseRed => Construct(0xae35);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseOrange => Construct(0xae34);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseAqua => Construct(0xae33);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseBlueDk => Construct(0xae32);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseManilla => Construct(0xae31);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseGrey => Construct(0xae30);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseBlueLt => Construct(0xae2f);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseGreenLtOlive => Construct(0xae2e);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseGreyDk => Construct(0xae2d);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseBrown => Construct(0xae2c);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseBlack => Construct(0xae2b);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseWhite => Construct(0xae29);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseGreenLt => Construct(0xae28);
        public static FormLink<IMaterialSwapGetter> DLC01Robot_BaseGreenDk => Construct(0xae27);
        public static FormLink<IMaterialSwapGetter> DLC01Protectron_BaseYellow => Construct(0xae25);
        public static FormLink<IMaterialSwapGetter> DLC01Protectron_BaseGrey => Construct(0xae24);
        public static FormLink<IMaterialSwapGetter> DLC01Protectron_BaseBlue => Construct(0xae23);
        public static FormLink<IMaterialSwapGetter> DLC01Protectron_BaseGreen => Construct(0xae22);
        public static FormLink<IMaterialSwapGetter> DLC01DirtyTOCleanGlass01 => Construct(0xa760);
        public static FormLink<IMaterialSwapGetter> IndFloorMedicalTile02 => Construct(0x9d88);
        public static FormLink<IMaterialSwapGetter> IndFloorMedicalTile01 => Construct(0x9d87);
        public static FormLink<IMaterialSwapGetter> IndFloorMetalRibs01 => Construct(0x9d86);
        public static FormLink<IMaterialSwapGetter> DLC01HitGlassExteriorGlassSwap => Construct(0x4135);
        public static FormLink<IMaterialSwapGetter> TrashtoRobot02 => Construct(0x1f18);
        public static FormLink<IMaterialSwapGetter> TrashtoRobot01 => Construct(0x1f17);
    }
}
