// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static class PackIn
    {
        private static FormLink<IPackInGetter> Construct(uint id) => new FormLink<IPackInGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPackInGetter> DLC01_Lair_ConsolesA_001 => Construct(0xe530);
        public static FormLink<IPackInGetter> DLC01_Lair_DebrisPile_001 => Construct(0xe4f9);
        public static FormLink<IPackInGetter> Clutter_DLC01_IndTables_01 => Construct(0xd5d5);
        public static FormLink<IPackInGetter> DLC01_Clutter_CeilingBroke001 => Construct(0xc3e7);
        public static FormLink<IPackInGetter> DLC01_Clutter_LgShelves_RW02 => Construct(0xc199);
        public static FormLink<IPackInGetter> DLC01_Clutter_LgShelves_RW01 => Construct(0xc183);
        public static FormLink<IPackInGetter> DLC01_Clutter_Boxes_RW01 => Construct(0xc13b);
        public static FormLink<IPackInGetter> DLC01_Clutter_LgShelves_RW01delete => Construct(0xc12f);
        public static FormLink<IPackInGetter> DLC01_KlaxonNBDestPackIn => Construct(0xa5cb);
        public static FormLink<IPackInGetter> DLC01_KlaxonDestPackIn => Construct(0xa5c6);
        public static FormLink<IPackInGetter> DLC01LvlMechAssaultronAmbushPackIn => Construct(0xa170);
        public static FormLink<IPackInGetter> DLC01TrackSystem_PackIn => Construct(0x7933);
        public static FormLink<IPackInGetter> DLC01MechDoor_Group07 => Construct(0x4c81);
        public static FormLink<IPackInGetter> DLC01MechDoor_Group06 => Construct(0x4c79);
        public static FormLink<IPackInGetter> DLC01MechDoor_Group05 => Construct(0x4c6f);
        public static FormLink<IPackInGetter> DLC01MechDoor_Group04 => Construct(0x4c64);
        public static FormLink<IPackInGetter> DLC01MechDoor_Group03 => Construct(0x4c5a);
        public static FormLink<IPackInGetter> DLC01MechDoor_Group02 => Construct(0x4c51);
        public static FormLink<IPackInGetter> DLC01MechDoor_Group01 => Construct(0x4c47);
        public static FormLink<IPackInGetter> DLC01EyebotPipePackIn => Construct(0x2724);
        public static FormLink<IPackInGetter> DLC01RobotLiftPackIn => Construct(0x26d2);
    }
}
