// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static class Perk
    {
        private static FormLink<IPerkGetter> Construct(uint id) => new FormLink<IPerkGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPerkGetter> DLC01Bot_CommonArmorPerk_Unstable => Construct(0x29c5);
        public static FormLink<IPerkGetter> DLC01Bot_FortifyExplosionLimbConditionPerk => Construct(0x2985);
        public static FormLink<IPerkGetter> DLC01Bot_FortifyLimbConditionPerk => Construct(0x2984);
        public static FormLink<IPerkGetter> DLC01Bot_FortifyMesmetronPerk => Construct(0x297f);
        public static FormLink<IPerkGetter> DLC01Bot_FortifyAssaultronHeadLaserPerk => Construct(0x2969);
        public static FormLink<IPerkGetter> DLC01Bot_EnergyDamagePerk => Construct(0x1291);
        public static FormLink<IPerkGetter> DLC01Bot_CommonArmorPerk => Construct(0x128c);
        public static FormLink<IPerkGetter> DLC01MQ01Caravan_MutualInvulnerabilityPerk => Construct(0xfff7);
        public static FormLink<IPerkGetter> DLC01_SpawnedEyebotPerk => Construct(0x271f);
        public static FormLink<IPerkGetter> DLC01MBattle_EnchBot_TrashbotPerk => Construct(0x21bf);
        public static FormLink<IPerkGetter> ImmuneToElectricity => Construct(0x2102);
    }
}
