// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Robot
{
    public static partial class PlacedNpc
    {
        private static FormLink<IPlacedNpcGetter> Construct(uint id) => new FormLink<IPlacedNpcGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPlacedNpcGetter> DLC01MechanistRef => Construct(0x97c);
        public static FormLink<IPlacedNpcGetter> DLC01SparksRef => Construct(0x1dad);
        public static FormLink<IPlacedNpcGetter> DLC01_Lair_RoboMedREF => Construct(0xd5e1);
        public static FormLink<IPlacedNpcGetter> DLC01MQ04SentryBot => Construct(0x7525);
        public static FormLink<IPlacedNpcGetter> DLC01AdaRef => Construct(0xff12);
        public static FormLink<IPlacedNpcGetter> DLC01CaravanPorterRef => Construct(0xff83);
        public static FormLink<IPlacedNpcGetter> DLC01CaravanHurtzRef => Construct(0xff0f);
        public static FormLink<IPlacedNpcGetter> DLC01CaravanTuringRef => Construct(0xff0b);
        public static FormLink<IPlacedNpcGetter> DLC01CaravanZoeRef => Construct(0xff03);
    }
}
