// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class DamageType
    {
        private static FormLink<IDamageTypeGetter> Construct(uint id) => new FormLink<IDamageTypeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDamageTypeGetter> dtToxic => Construct(0xb79);
        public static FormLink<IDamageTypeGetter> dtShield => Construct(0x1ede8);
        public static FormLink<IDamageTypeGetter> dtElectromagnetic => Construct(0x23190);
        public static FormLink<IDamageTypeGetter> dtEnergy => Construct(0x60a81);
        public static FormLink<IDamageTypeGetter> dtFire_DONOTUSE => Construct(0x60a82);
        public static FormLink<IDamageTypeGetter> Stim_dt_Physical => Construct(0x60a87);
        public static FormLink<IDamageTypeGetter> Stim_dt_structural => Construct(0x1497af);
        public static FormLink<IDamageTypeGetter> Stim_dt_shocking => Construct(0x1e08bb);
        public static FormLink<IDamageTypeGetter> Stim_dt_freezing => Construct(0x1e08bc);
        public static FormLink<IDamageTypeGetter> Stim_dt_flame => Construct(0x1e08ea);
        public static FormLink<IDamageTypeGetter> Stim_dt_piercing => Construct(0x208dcd);
    }
}
