// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Debris
    {
        private static FormLink<IDebrisGetter> Construct(uint id) => new FormLink<IDebrisGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDebrisGetter> RobotDebris => Construct(0xc1c12);
        public static FormLink<IDebrisGetter> RobotDebrisSmall => Construct(0xc1c13);
    }
}
