// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class SurfacePatternStyle
    {
        private static FormLink<ISurfacePatternStyleGetter> Construct(uint id) => new FormLink<ISurfacePatternStyleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleDunesRockyHillsRounded => Construct(0xdb32);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleCanyonsErodedLargeFieldsPlateaus => Construct(0x307ea);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsRoundedFieldsFlat => Construct(0x37936);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsPoolsFieldsMixed => Construct(0xb2634);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsFlatMountainsRidged => Construct(0xb6b96);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleCratersSharpHillsRough => Construct(0xc5712);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleCratersSharpFieldsDunes => Construct(0xc7abb);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleCratersSharpHillsMesasSharp => Construct(0xc7abc);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsFlatFieldsSlotCanyonsEroded => Construct(0xee910);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsMixed => Construct(0xeea98);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsArchipelagoMountainsSharp => Construct(0xf1f0a);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsArchipelagoPoolsDeep => Construct(0x120c77);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsHillsDunesPoolsFractured => Construct(0x122683);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsRoughCratersSharpSparse => Construct(0x12268c);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsSharpFieldsDeltas => Construct(0x1d1d8e);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsSharpFieldsRocky => Construct(0x212e1b);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsErodedFieldsPlateaus => Construct(0x21480f);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsRidgedFieldsFlat => Construct(0x21fd0f);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleTestBlocks => Construct(0x233c05);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleCanyonsSharpLargeFieldsWarped => Construct(0x23ddf8);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsWarpedFieldsCrevasses => Construct(0x23de52);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleCratersSharpFieldsRocky => Construct(0x23de77);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsRockyFieldsRocky => Construct(0x23de7e);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsDunesFieldsWarped => Construct(0x23de86);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsSharpHillsRough => Construct(0x23de92);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsRoughFieldsFlat => Construct(0x23de98);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsPoolsFieldsCrevasses => Construct(0x23de9f);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleVolcanoesErodedFieldsMounds => Construct(0x23deaf);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsSmoothFieldsHills => Construct(0x23deb1);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsErodedFieldsFlat => Construct(0x23deb9);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsAngledFieldsFractured => Construct(0x23debf);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsTerracedFieldsFlat => Construct(0x23dec6);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsHillsFieldsFlat => Construct(0x23dece);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsFlatMountainsSharp => Construct(0x23ded5);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsSharpFieldsFlat => Construct(0x23dedb);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsRockyFieldsPools => Construct(0x23dee3);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsDunesFieldsCrevasses => Construct(0x23f74d);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsSharpFieldsPlateaus => Construct(0x23f752);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMountainsSharpFieldsHills => Construct(0x23f753);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleHillsRoundedFieldsMounds => Construct(0x2406a6);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsWarpedCratersSharp => Construct(0x2406a7);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleTestZane => Construct(0x251531);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldDunesRockyMesasEroded => Construct(0x2dcdd5);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleFieldsPoolsFieldsDeltas => Construct(0x2e57e9);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleCanyonsSharpMesasSharp => Construct(0x3ffd4a);
        public static FormLink<ISurfacePatternStyleGetter> PatternStyleMesasRockyMediumFieldsDunes => Construct(0x3ffd4c);
    }
}
