// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Weather
    {
        private static FormLink<IWeatherGetter> Construct(uint id) => new FormLink<IWeatherGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWeatherGetter> DefaultWeather => Construct(0x15e);
        public static FormLink<IWeatherGetter> SpaceWeather => Construct(0x249fa6);
        public static FormLink<IWeatherGetter> NewAtlantisWeather50 => Construct(0x27cf9b);
    }
}
