// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE;

public static partial class Dawnguard
{
    public static partial class Book
    {
        private static FormLink<IBookGetter> Construct(uint id) => new FormLink<IBookGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBookGetter> DLC1VQ03MalkusNote => Construct(0x126c5);
        public static FormLink<IBookGetter> DLC1RecipeFrenzy1 => Construct(0xf39c);
        public static FormLink<IBookGetter> DLC1SpellTomeHealUndead => Construct(0xe8d6);
        public static FormLink<IBookGetter> DLC1SpellTomeNecromanticHealing => Construct(0xe8d5);
        public static FormLink<IBookGetter> DLC1Book3ValuableSultryArgonianBardVol01 => Construct(0x6925);
        public static FormLink<IBookGetter> DLC1SpellTomeConjureWrathman => Construct(0x45b2);
        public static FormLink<IBookGetter> DLC1SpellTomeConjureMistman => Construct(0x45b1);
        public static FormLink<IBookGetter> DLC1SpellTomeConjureBoneman => Construct(0x45b0);
        public static FormLink<IBookGetter> DLC1VQSaintFinalBook => Construct(0x3f79);
        public static FormLink<IBookGetter> DLC1SpellTomeSunFire => Construct(0x3f51);
        public static FormLink<IBookGetter> DLC1SpellTomeStendarrsAura => Construct(0x3f4e);
        public static FormLink<IBookGetter> DLC1SpellTomeVampiresBane => Construct(0x3f4d);
        public static FormLink<IBookGetter> DLC1_WESC04Note => Construct(0x1aa22);
        public static FormLink<IBookGetter> DLC1LD_ArkngthamzPuzzleScrap => Construct(0x1a436);
        public static FormLink<IBookGetter> DLC1FVBook04English => Construct(0x1a3e8);
        public static FormLink<IBookGetter> DLC1FVBook03English => Construct(0x1a3e7);
        public static FormLink<IBookGetter> DLC1FVBook02English => Construct(0x1a3e6);
        public static FormLink<IBookGetter> DLC1FVBook01English => Construct(0x1a3e5);
        public static FormLink<IBookGetter> DLC1FVBook04Falmer => Construct(0x1a3e3);
        public static FormLink<IBookGetter> DLC1FVBook03Falmer => Construct(0x1a3e2);
        public static FormLink<IBookGetter> DLC1FVBook02Falmer => Construct(0x1a3e1);
        public static FormLink<IBookGetter> DLC1FVBook01Falmer => Construct(0x1a3e0);
        public static FormLink<IBookGetter> DLC1RuunvaldJournal06 => Construct(0x1957e);
        public static FormLink<IBookGetter> DLC1RuunvaldJournal05 => Construct(0x1957c);
        public static FormLink<IBookGetter> DLC1RuunvaldJournal04 => Construct(0x1957a);
        public static FormLink<IBookGetter> DLC1RuunvaldJournal03 => Construct(0x19578);
        public static FormLink<IBookGetter> DLC1RuunvaldJournal02 => Construct(0x192f0);
        public static FormLink<IBookGetter> DLC1VCNote1 => Construct(0x188c8);
        public static FormLink<IBookGetter> DLC1DarkfallPassageNote02 => Construct(0x18645);
        public static FormLink<IBookGetter> DLC1DarkfallPassageNote01 => Construct(0x1860d);
        public static FormLink<IBookGetter> DLC1Book3ValuableFurTrader => Construct(0x16692);
        public static FormLink<IBookGetter> DLC1SoulCairnRJPOI2Note => Construct(0x15d88);
        public static FormLink<IBookGetter> DLC1dunRedwaterDenJournal2 => Construct(0x149a3);
        public static FormLink<IBookGetter> DLC1dunRedwaterDenJournal1 => Construct(0x149a2);
        public static FormLink<IBookGetter> DLC1LD_KatriaJournal => Construct(0x146db);
        public static FormLink<IBookGetter> DLC1VQSaintPage10 => Construct(0x14019);
        public static FormLink<IBookGetter> DLC1VQSaintPage09 => Construct(0x14018);
        public static FormLink<IBookGetter> DLC1VQSaintPage08 => Construct(0x14017);
        public static FormLink<IBookGetter> DLC1VQSaintPage07 => Construct(0x14016);
        public static FormLink<IBookGetter> DLC1VQSaintPage06 => Construct(0x14015);
        public static FormLink<IBookGetter> DLC1VQSaintPage05 => Construct(0x14014);
        public static FormLink<IBookGetter> DLC1VQSaintPage04 => Construct(0x14013);
        public static FormLink<IBookGetter> DLC1VQSaintPage03 => Construct(0x14012);
        public static FormLink<IBookGetter> DLC1VQSaintPage02 => Construct(0x14011);
        public static FormLink<IBookGetter> DLC1VQSaintPage01 => Construct(0x14010);
        public static FormLink<IBookGetter> DLC1RuunvaldJournal01 => Construct(0x135cb);
        public static FormLink<IBookGetter> DLC1ElderScrollDragon => Construct(0x126dc);
        public static FormLink<IBookGetter> DLC1ElderScrollSun => Construct(0x11a13);
        public static FormLink<IBookGetter> DLC1ElderScrollBlood => Construct(0x118f9);
        public static FormLink<IBookGetter> DLC1BookofLifeandService => Construct(0xfac2);
        public static FormLink<IBookGetter> DLC1VQ01Book => Construct(0xd070);
        public static FormLink<IBookGetter> DLC1VQ03HunterStage55Note => Construct(0x6e58);
        public static FormLink<IBookGetter> DLC1DarkfallCaveNote01 => Construct(0xa83b);
        public static FormLink<IBookGetter> DLC1RH07Letter => Construct(0x7ecb);
        public static FormLink<IBookGetter> DLC1RH05BanditLetter => Construct(0x6bb3);
        public static FormLink<IBookGetter> DLC1RH04Letter => Construct(0x6956);
        public static FormLink<IBookGetter> DLC1RV03Letter => Construct(0x50ca);
        public static FormLink<IBookGetter> DLC1LD_AetheriumWars => Construct(0x4d5b);
        public static FormLink<IBookGetter> DLC1VQ04ValericaBook => Construct(0x3c4b);
        public static FormLink<IBookGetter> DLC1_WESC08Orders => Construct(0x3521);
        public static FormLink<IBookGetter> DLC1_WESC06Orders => Construct(0x3517);
        public static FormLink<IBookGetter> DLC1_WESC07Orders => Construct(0x350b);
        public static FormLink<IBookGetter> DLC1_WESC05Note => Construct(0x34dc);
    }
}
