// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE;

public static partial class Dawnguard
{
    public static partial class Explosion
    {
        private static FormLink<IExplosionGetter> Construct(uint id) => new FormLink<IExplosionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IExplosionGetter> DLC1SEBossBlastBackFX => Construct(0x138cc);
        public static FormLink<IExplosionGetter> DLC1VampChangeStaggerExp => Construct(0x12fee);
        public static FormLink<IExplosionGetter> DLC1VampireAbsorbExplosion => Construct(0x12fed);
        public static FormLink<IExplosionGetter> DLC1HarkonShieldAurielsBowExplosion => Construct(0x11cd9);
        public static FormLink<IExplosionGetter> DLC1dunHarkonDeathExplosion => Construct(0x113c2);
        public static FormLink<IExplosionGetter> DLC1BoltExplosionShock02 => Construct(0x10d92);
        public static FormLink<IExplosionGetter> DLC1BoltExplosionFrost02 => Construct(0x10d91);
        public static FormLink<IExplosionGetter> DLC1BoltExplosionFire02 => Construct(0x10d90);
        public static FormLink<IExplosionGetter> DLC1SGargoyleHavokExplosion => Construct(0x10cf9);
        public static FormLink<IExplosionGetter> TrapPoisonBloomGasExplosion06 => Construct(0xf3c6);
        public static FormLink<IExplosionGetter> TrapPoisonBloomGasExplosion05 => Construct(0xf3c5);
        public static FormLink<IExplosionGetter> TrapPoisonBloomGasExplosion04 => Construct(0xf3c4);
        public static FormLink<IExplosionGetter> TrapPoisonBloomGasExplosion03 => Construct(0xf3c3);
        public static FormLink<IExplosionGetter> TrapPoisonBloomGasExplosion02 => Construct(0xf3c2);
        public static FormLink<IExplosionGetter> TrapPoisonBloomGasExplosion01 => Construct(0xf3c1);
        public static FormLink<IExplosionGetter> DLC1nVampireBloodPlagueExplosion => Construct(0xe7b4);
        public static FormLink<IExplosionGetter> DLC1AurielsBowActivatorPlacerExp => Construct(0x3285);
        public static FormLink<IExplosionGetter> DLC1CacoonExplosion => Construct(0x1aade);
        public static FormLink<IExplosionGetter> DLC1BridgeBreakExplosion => Construct(0x1aa5e);
        public static FormLink<IExplosionGetter> DLC01FrozenLakeBreakExplosionExit => Construct(0x19dba);
        public static FormLink<IExplosionGetter> DLC1VampiresBaneExplosion => Construct(0x18f01);
        public static FormLink<IExplosionGetter> DLC1AurielsBowExpNoEnchant => Construct(0x18eff);
        public static FormLink<IExplosionGetter> DLC01FrozenLakeBreakExplosionEnter => Construct(0x17f70);
        public static FormLink<IExplosionGetter> DLC1VampiresBaneSunBurst => Construct(0x17e8d);
        public static FormLink<IExplosionGetter> DLC1VampDetectLifeExplosion => Construct(0x169da);
        public static FormLink<IExplosionGetter> DLC1ChaurusFrozeAwakeExplosion => Construct(0x16128);
        public static FormLink<IExplosionGetter> DLC1FrozenChaurusExplosion => Construct(0x16126);
        public static FormLink<IExplosionGetter> DLC1FalmerFrozeAwakeExplosion => Construct(0x15fd6);
        public static FormLink<IExplosionGetter> testSuperMageLightExp => Construct(0x1540e);
        public static FormLink<IExplosionGetter> DLC1VampChangeExplosion => Construct(0x15373);
        public static FormLink<IExplosionGetter> DLC1LD_SteamTriggerExplosion => Construct(0x15370);
        public static FormLink<IExplosionGetter> DLC1LD_LavaTriggerExplosion => Construct(0x1536f);
        public static FormLink<IExplosionGetter> DLC1SC_LightningBoltImpactExplosion => Construct(0x14324);
        public static FormLink<IExplosionGetter> DLC1LD_AetherialStaffEffectExplosion => Construct(0x142b3);
        public static FormLink<IExplosionGetter> DLC1AurielsBowEclipseExplosion => Construct(0x11599);
        public static FormLink<IExplosionGetter> DLC1BoltExplosionFire03 => Construct(0xf1b5);
        public static FormLink<IExplosionGetter> DLC1BoltExplosionShock03 => Construct(0xf1b4);
        public static FormLink<IExplosionGetter> DLC1BoltExplosionFrost03 => Construct(0xf1b3);
        public static FormLink<IExplosionGetter> DLC1SnowElfColumnHavokExplosion => Construct(0xef27);
        public static FormLink<IExplosionGetter> DLC1SnowElfFlatHavokExplosion => Construct(0xef26);
        public static FormLink<IExplosionGetter> DLC1FrozenFalmerExplosion => Construct(0xd97b);
        public static FormLink<IExplosionGetter> DLC1AurielsBowSunBurstExplosion => Construct(0xc611);
        public static FormLink<IExplosionGetter> DLC1AurielsBowExp01 => Construct(0xaeb4);
        public static FormLink<IExplosionGetter> DLC1SoulCairnCrystalExplosion => Construct(0x69c4);
        public static FormLink<IExplosionGetter> DLC1TrapCrossbowExplosion01 => Construct(0x37e8);
    }
}
