using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE
{
    public static partial class Dawnguard
    {
        public static class Keyword
        {
            private static FormLink<IKeywordGetter> Construct(uint id) => new FormLink<IKeywordGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IKeywordGetter> DLC1VampireFeedBystanderStart => Construct(0x14cbb);
            public static FormLink<IKeywordGetter> DLC1ArmorMaterialVampire => Construct(0x1463e);
            public static FormLink<IKeywordGetter> DLC1ProtectChange => Construct(0x1463d);
            public static FormLink<IKeywordGetter> DLC1DurnehviirKeyword => Construct(0x145cc);
            public static FormLink<IKeywordGetter> DLC1LinkUseWeaponRanged => Construct(0x13f70);
            public static FormLink<IKeywordGetter> DLC1LinkUseWeaponTarget => Construct(0x13f6e);
            public static FormLink<IKeywordGetter> DLC1LinkUseWeaponMelee => Construct(0x13f6b);
            public static FormLink<IKeywordGetter> DLC1ArmorMaterielFalmerHeavyOriginal => Construct(0x12cd0);
            public static FormLink<IKeywordGetter> DLC1ArmorMaterielFalmerHeavy => Construct(0x12ccf);
            public static FormLink<IKeywordGetter> DLC1ArmorMaterialFalmerHardened => Construct(0x12cce);
            public static FormLink<IKeywordGetter> DLC1ArmorMaterialDawnguard => Construct(0x12ccd);
            public static FormLink<IKeywordGetter> ActorTypeDLC1Boss => Construct(0x1269f);
            public static FormLink<IKeywordGetter> DLC1ArvakExclusion => Construct(0x1223c);
            public static FormLink<IKeywordGetter> DLC1LinkEatLunchNight2 => Construct(0x10f5c);
            public static FormLink<IKeywordGetter> DLC1LinkEatLunchNight1 => Construct(0x10f5b);
            public static FormLink<IKeywordGetter> DLC1LinkEatDinnerNight2 => Construct(0x10f5a);
            public static FormLink<IKeywordGetter> DLC1LinkEatDinnerNight1 => Construct(0x10f59);
            public static FormLink<IKeywordGetter> DLC1LinkEatBreakfastNight2 => Construct(0x10f58);
            public static FormLink<IKeywordGetter> DLC1LinkEatBreakfastNight1 => Construct(0x10f57);
            public static FormLink<IKeywordGetter> DLC1LD_ImmuneToAetherialShield => Construct(0x10e97);
            public static FormLink<IKeywordGetter> DLC1LDAetherialSummon => Construct(0xf37f);
            public static FormLink<IKeywordGetter> DLC1WispWall => Construct(0xebb3);
            public static FormLink<IKeywordGetter> DLC1VampireDrainEffect => Construct(0xd840);
            public static FormLink<IKeywordGetter> DLC1DawnguardArmorShield => Construct(0xd83f);
            public static FormLink<IKeywordGetter> DLC1DawnguardArmorHelmet => Construct(0xd83e);
            public static FormLink<IKeywordGetter> DLC1DawnguardArmorGloves => Construct(0xd83d);
            public static FormLink<IKeywordGetter> DLC1DawnguardArmorBoots => Construct(0xd83c);
            public static FormLink<IKeywordGetter> DLC1DawnguardArmorBody => Construct(0xd83b);
            public static FormLink<IKeywordGetter> DLC1DawnguardItem => Construct(0xd839);
            public static FormLink<IKeywordGetter> DLC1LegendaryDragon => Construct(0xcd59);
            public static FormLink<IKeywordGetter> DLC1LinkFeedTableThrall247 => Construct(0xcd55);
            public static FormLink<IKeywordGetter> DLC1AurielsConditionalExplosionKeyword => Construct(0xcbc0);
            public static FormLink<IKeywordGetter> DLC1WispWallEffect => Construct(0x5155);
            public static FormLink<IKeywordGetter> DLC1WispWallWisp3 => Construct(0x5154);
            public static FormLink<IKeywordGetter> DLC1WispWallWisp2 => Construct(0x5153);
            public static FormLink<IKeywordGetter> DLC1WispWallWisp1 => Construct(0x5152);
            public static FormLink<IKeywordGetter> DLC1CrossbowIsEnhanced => Construct(0x399c);
            public static FormLink<IKeywordGetter> DLC1RadiantHunterTechStart => Construct(0x2f22);
            public static FormLink<IKeywordGetter> DLC1LD_LavaImagespaceKeyword => Construct(0x2981);
            public static FormLink<IKeywordGetter> DLC1ReadElderScroll => Construct(0x1a95a);
            public static FormLink<IKeywordGetter> DLC1VampirePowersExclude => Construct(0x1a320);
            public static FormLink<IKeywordGetter> DLC1BthalftSoundLink => Construct(0x19d96);
            public static FormLink<IKeywordGetter> DLC1CoffinPuzzleBowl => Construct(0x19909);
            public static FormLink<IKeywordGetter> DLC1WeapMaterialDragonbone => Construct(0x19822);
            public static FormLink<IKeywordGetter> DLC1isVampireCoffinHorizontal => Construct(0x1932a);
            public static FormLink<IKeywordGetter> ActorTypeMount => Construct(0x191fe);
            public static FormLink<IKeywordGetter> DLC1VampireDetectLifeDispelKeyword => Construct(0x169d8);
            public static FormLink<IKeywordGetter> DLC1LinkFerrySeat2 => Construct(0x1685b);
            public static FormLink<IKeywordGetter> DLC1LinkFerrySeat1 => Construct(0x1685a);
            public static FormLink<IKeywordGetter> DLC1WerewolfFeedExclude => Construct(0x15fd3);
            public static FormLink<IKeywordGetter> WeapDwarvenCrossbow => Construct(0x15992);
            public static FormLink<IKeywordGetter> VampireEatingChair => Construct(0x15770);
            public static FormLink<IKeywordGetter> isVampireFeastVictim => Construct(0x1576d);
            public static FormLink<IKeywordGetter> DLC1CrystalDrainKeyword => Construct(0x1542a);
            public static FormLink<IKeywordGetter> DLC1LD_LavaKeyword => Construct(0x15336);
            public static FormLink<IKeywordGetter> DLC1LD_LavaLingeringKeyword => Construct(0x15335);
            public static FormLink<IKeywordGetter> DLC1LD_SteamKeyword => Construct(0x15334);
            public static FormLink<IKeywordGetter> DLC1LD_SteamLingeringKeyword => Construct(0x15333);
            public static FormLink<IKeywordGetter> DLC1BloodPortal => Construct(0x15039);
            public static FormLink<IKeywordGetter> DLC1VQ05SkeletonKeyword => Construct(0x14ede);
            public static FormLink<IKeywordGetter> FreeformRiverwood01SceneKeywordDUPLICATE001 => Construct(0x14edd);
            public static FormLink<IKeywordGetter> DLC1BloodChaliceActivate => Construct(0x14193);
            public static FormLink<IKeywordGetter> DLC1CraftingDawnguard => Construct(0xf806);
            public static FormLink<IKeywordGetter> DLC1SeranaCoffin => Construct(0xf7f6);
            public static FormLink<IKeywordGetter> DLC1LD_CraftingMaterialAetherium => Construct(0xe299);
            public static FormLink<IKeywordGetter> DLC1VampReading => Construct(0xd07d);
            public static FormLink<IKeywordGetter> DLC01SoulHorseEnd => Construct(0xbdd8);
            public static FormLink<IKeywordGetter> DLC01SoulHorseStart => Construct(0xbdd7);
            public static FormLink<IKeywordGetter> DLC1isVampireCoffinVertical => Construct(0xb64d);
            public static FormLink<IKeywordGetter> ActorTypeVampireBrute => Construct(0xa2cb);
            public static FormLink<IKeywordGetter> DLC1LD_Ghost => Construct(0xa2b4);
            public static FormLink<IKeywordGetter> DLC1_ScrapeBarkKeyword => Construct(0xa25c);
            public static FormLink<IKeywordGetter> DLC1_WayShrineWaterScoopKeyword => Construct(0xa25b);
            public static FormLink<IKeywordGetter> DLC1_WayShrineWaterPourKeyWord => Construct(0xa25a);
            public static FormLink<IKeywordGetter> DLC1VampFeast => Construct(0x7d92);
            public static FormLink<IKeywordGetter> DLC1VampSpectateSpeech => Construct(0x7d91);
            public static FormLink<IKeywordGetter> DLC1VampSpectateTorture => Construct(0x7d90);
            public static FormLink<IKeywordGetter> DLC1HarkonFloorCenter => Construct(0x7d8f);
            public static FormLink<IKeywordGetter> DLC1_SnowElfThroneKeyword => Construct(0x7060);
            public static FormLink<IKeywordGetter> DLC1LD_CraftingForgeAetherium => Construct(0x5756);
            public static FormLink<IKeywordGetter> DLC1RV03HunterGarb => Construct(0x50c8);
            public static FormLink<IKeywordGetter> DLC1ArmorMaterialHunter => Construct(0x50c4);
            public static FormLink<IKeywordGetter> DLC1RV03KillLocation => Construct(0x50c2);
            public static FormLink<IKeywordGetter> DLC1RadiantHunterStart => Construct(0x4c1e);
            public static FormLink<IKeywordGetter> DLC1RadiantVampireStart => Construct(0x4c1d);
            public static FormLink<IKeywordGetter> DLC1LinkGuard => Construct(0x33cb);
            public static FormLink<IKeywordGetter> DLC1LinkKeepEyeOn => Construct(0x33ca);
            public static FormLink<IKeywordGetter> DLC1LinkServices => Construct(0x33c7);
            public static FormLink<IKeywordGetter> DLC1LinkEatDinner2 => Construct(0x33c6);
            public static FormLink<IKeywordGetter> DLC1LinkEatDinner1 => Construct(0x33c5);
            public static FormLink<IKeywordGetter> DLC1LinkEatLunch2 => Construct(0x33c4);
            public static FormLink<IKeywordGetter> DLC1LinkEatLunch1 => Construct(0x33c3);
            public static FormLink<IKeywordGetter> DLC1LinkEatBreakfast2 => Construct(0x33c2);
            public static FormLink<IKeywordGetter> DLC1LinkEatBreakfast1 => Construct(0x33c1);
            public static FormLink<IKeywordGetter> DLC1LinkSandbox => Construct(0x33c0);
            public static FormLink<IKeywordGetter> DLC1LinkSleepDay3 => Construct(0x33bf);
            public static FormLink<IKeywordGetter> DLC1LinkSleepDay2 => Construct(0x33be);
            public static FormLink<IKeywordGetter> DLC1LinkSleepDay1 => Construct(0x33bd);
            public static FormLink<IKeywordGetter> DLC1LinkSleepNight3 => Construct(0x33bc);
            public static FormLink<IKeywordGetter> DLC1LinkSleepNight2 => Construct(0x33bb);
            public static FormLink<IKeywordGetter> DLC1LinkSleepNight1 => Construct(0x33ba);
        }
    }
}
