// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE;

public static partial class Dragonborn
{
    public static partial class Explosion
    {
        private static FormLink<IExplosionGetter> Construct(uint id) => new FormLink<IExplosionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IExplosionGetter> DLC2ConstellationExplosion => Construct(0x3d5ce);
        public static FormLink<IExplosionGetter> DLC2MiraakCycloneStaggerExplosion => Construct(0x3d3b5);
        public static FormLink<IExplosionGetter> DLC2MiraakBackExplosion => Construct(0x3d381);
        public static FormLink<IExplosionGetter> DLC2MiraakAwayExplosion => Construct(0x3d380);
        public static FormLink<IExplosionGetter> DLC2LurkerStompInvis => Construct(0x3cef9);
        public static FormLink<IExplosionGetter> DLC2LurkerStompArtExplosion => Construct(0x3cef4);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderGlowingCrumbleExplosion => Construct(0x3ca9e);
        public static FormLink<IExplosionGetter> DLC2MkTentacleExplosion => Construct(0x39e48);
        public static FormLink<IExplosionGetter> DLC2MKMiraakRobeExplosion => Construct(0x39d1b);
        public static FormLink<IExplosionGetter> DLC2dunKarstaagBlizzardForceExplosion => Construct(0x38aba);
        public static FormLink<IExplosionGetter> DLC2FakeExplosionDark01 => Construct(0x36a67);
        public static FormLink<IExplosionGetter> DLC2MQ06MiraakTeleportExplosion => Construct(0x34815);
        public static FormLink<IExplosionGetter> DLC2ExplosionAshSpawn => Construct(0x3280b);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderOilCrumbleExplosion => Construct(0x32791);
        public static FormLink<IExplosionGetter> DLC2ExpStandingStoneRelease => Construct(0x323fd);
        public static FormLink<IExplosionGetter> DLC2MiraakTeleportReturnExp => Construct(0x31ac3);
        public static FormLink<IExplosionGetter> DLC2MiraakTeleportExp => Construct(0x30cea);
        public static FormLink<IExplosionGetter> DLC2FXBarrelForce01 => Construct(0x30cc1);
        public static FormLink<IExplosionGetter> DLC2ExpStandingStoneExplosion => Construct(0x30c8a);
        public static FormLink<IExplosionGetter> fakeForceBall1024NoKnockdown => Construct(0x2bfa5);
        public static FormLink<IExplosionGetter> DLC2ExplosionBardInstrumentBuff => Construct(0x2bd28);
        public static FormLink<IExplosionGetter> DLC2SRieklingHavokExplosion => Construct(0x2bb0d);
        public static FormLink<IExplosionGetter> DLC2BenthicLurkerExplosion => Construct(0x2b0fd);
        public static FormLink<IExplosionGetter> DLC2dunHighpointExpAshGuardian => Construct(0x296bd);
        public static FormLink<IExplosionGetter> DLC2fakeForceBall1024 => Construct(0x2865e);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockExplosion6 => Construct(0x285e8);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockExplosion5 => Construct(0x285e7);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockExplosion4 => Construct(0x285e6);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockExplosion3 => Construct(0x285e5);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockExplosion2 => Construct(0x285e4);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockExplosion1 => Construct(0x285e3);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonExplosion6 => Construct(0x285e2);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonExplosion5 => Construct(0x285e1);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonExplosion4 => Construct(0x285e0);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonExplosion3 => Construct(0x285df);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonExplosion2 => Construct(0x285de);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostExplosion6 => Construct(0x285dd);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostExplosion4 => Construct(0x285dc);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostExplosion5 => Construct(0x285db);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostExplosion3 => Construct(0x285da);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostExplosion2 => Construct(0x285d9);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireExplosion6 => Construct(0x285d8);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireExplosion5 => Construct(0x285d7);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireExplosion4 => Construct(0x285d6);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireExplosion3 => Construct(0x285d5);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireExplosion2 => Construct(0x285d4);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireJumpingSpawnENEMY => Construct(0x285d3);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireCloakingSpawnENEMY => Construct(0x285ce);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireBombExplosionENEMY => Construct(0x285cb);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPackmuleSpawnFriend => Construct(0x274a7);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderOilSpawnFriend => Construct(0x2749f);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderGlowingSpawnFriend => Construct(0x27494);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockBombExplosion => Construct(0x26d65);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostExplosion1 => Construct(0x26d52);
        public static FormLink<IExplosionGetter> DLC2KagrumezSteamExplosion => Construct(0x26629);
        public static FormLink<IExplosionGetter> DLC2KagrumezShockExplosion => Construct(0x260ea);
        public static FormLink<IExplosionGetter> DLC2HMDaedraMouthExp01 => Construct(0x24fc2);
        public static FormLink<IExplosionGetter> DLC2HMDaedraBallExp01 => Construct(0x24fba);
        public static FormLink<IExplosionGetter> DLC2HMDaedraDeathExplosion => Construct(0x23f84);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockCrumbleExplosion => Construct(0x2096c);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockSpawnFriend => Construct(0x2096b);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockJumpingSpawn => Construct(0x2096a);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderShockCloakingSpawnFriend => Construct(0x20969);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostSpawn => Construct(0x206e4);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostJumpingSpawnFriend => Construct(0x206e3);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostCloakingSpawnFriend => Construct(0x206e2);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostBombExplosion => Construct(0x206da);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFrostCrumbleExplosion => Construct(0x206c9);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonCrumbleExplosion => Construct(0x200cb);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireCrumbleExplosion => Construct(0x1ff3f);
        public static FormLink<IExplosionGetter> DLC2PoisonRuneExplosion => Construct(0x1d748);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonCloakingSpawnFriend => Construct(0x1cab2);
        public static FormLink<IExplosionGetter> DLC2ExplosionAshGuardianNoStone => Construct(0x1aac0);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireBombExplosion => Construct(0x19531);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireCloakingSpawnFriend => Construct(0x1952b);
        public static FormLink<IExplosionGetter> DLC2FrenzyRuneExplosion => Construct(0x177ba);
        public static FormLink<IExplosionGetter> DLC2AshRuneExplosion => Construct(0x177b1);
        public static FormLink<IExplosionGetter> DLC2ExplosionAshGuardian => Construct(0x17781);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonBombExplosion => Construct(0x1707d);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderZombieSpawnFriend => Construct(0x16e19);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderAlbinoSpawnFriend => Construct(0x145ce);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderEggSackExplosion => Construct(0x145c9);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireJumpingSpawnFriend => Construct(0x14492);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonJumpingSpawnFriend => Construct(0x1448c);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireSpawn => Construct(0x14483);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderFireExplosion1 => Construct(0x1447c);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonExplosion1 => Construct(0x1445d);
        public static FormLink<IExplosionGetter> DLC2ExpSpiderPoisonJumpingSpawn => Construct(0x14456);
    }
}
