// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimLE;

public static partial class Dragonborn
{
    public static partial class Location
    {
        private static FormLink<ILocationGetter> Construct(uint id) => new FormLink<ILocationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILocationGetter> DLC2HoldingCellBardLocation => Construct(0x3a4a1);
        public static FormLink<ILocationGetter> DLC2ColdcinderCaveLocation => Construct(0x3a42f);
        public static FormLink<ILocationGetter> DLC2ApocrypaMiraaksTowerLocation => Construct(0x3a1e7);
        public static FormLink<ILocationGetter> DLC2BloodskalBarrowBanditLocation => Construct(0x3a07f);
        public static FormLink<ILocationGetter> DLC2HeadwatersOfHarstradLocation => Construct(0x39f98);
        public static FormLink<ILocationGetter> DLC2ApoIslandALocation => Construct(0x382f5);
        public static FormLink<ILocationGetter> DLC2POIFallForest28Location => Construct(0x35bf3);
        public static FormLink<ILocationGetter> DLC2RamshackleTradingPostLocation => Construct(0x34ee6);
        public static FormLink<ILocationGetter> DLC2BristlebackCaveLocation => Construct(0x32892);
        public static FormLink<ILocationGetter> DLC2DamphallMineLocation => Construct(0x296da);
        public static FormLink<ILocationGetter> DLC2ThroatoftheWorldPath => Construct(0x2659f);
        public static FormLink<ILocationGetter> DLC2RRTempleTombLocation => Construct(0x24dfd);
        public static FormLink<ILocationGetter> DLC2SnowcladRuinsLocation => Construct(0x247c6);
        public static FormLink<ILocationGetter> DLC2DremoraShopLocation => Construct(0x1ff28);
        public static FormLink<ILocationGetter> DLC2Book02DungeonLocationNEW => Construct(0x1ee08);
        public static FormLink<ILocationGetter> DLC2Book06DungeonLocation => Construct(0x1ee07);
        public static FormLink<ILocationGetter> DLC2Book04DungeonLocation => Construct(0x1ee06);
        public static FormLink<ILocationGetter> DLC2POI8Location => Construct(0x1e8c6);
        public static FormLink<ILocationGetter> DLC2RegionGlacierLocation => Construct(0x1e7dd);
        public static FormLink<ILocationGetter> DLC2RegionNorthLocation => Construct(0x1e7dc);
        public static FormLink<ILocationGetter> DLC2RegionAshlandLocation => Construct(0x1e7db);
        public static FormLink<ILocationGetter> DLC2SVWulfsHouseLocation => Construct(0x1d93a);
        public static FormLink<ILocationGetter> DLC2SVEdlasHouseLocation => Construct(0x1d938);
        public static FormLink<ILocationGetter> DLC2SVShamansHutLocation => Construct(0x1d936);
        public static FormLink<ILocationGetter> DLC2SVOslafsHouseLocation => Construct(0x1d934);
        public static FormLink<ILocationGetter> DLC2SVMorwensHouseLocation => Construct(0x1d932);
        public static FormLink<ILocationGetter> DLC2SVDeorsHouseLocation => Construct(0x1d930);
        public static FormLink<ILocationGetter> DLC2SVBaldorsHouseLocation => Construct(0x1d92e);
        public static FormLink<ILocationGetter> DLC2SVGreathallLocation => Construct(0x1d92c);
        public static FormLink<ILocationGetter> DLC2TelMithrynStewardLocation => Construct(0x1cded);
        public static FormLink<ILocationGetter> DLC2TelMithrynKitchenLocation => Construct(0x1cdec);
        public static FormLink<ILocationGetter> DLC2TelMithrynApothecaryLocation => Construct(0x1cdeb);
        public static FormLink<ILocationGetter> DLC2TelMithrynTowerLocation => Construct(0x1cdea);
        public static FormLink<ILocationGetter> DLC2RR01AttiusFarmLocation => Construct(0x1bfe4);
        public static FormLink<ILocationGetter> DLC2RR01AmbushCellLocation => Construct(0x1b912);
        public static FormLink<ILocationGetter> DLC2ThirskUnifyingDummyLocation => Construct(0x1a513);
        public static FormLink<ILocationGetter> DLC2SaeringsWatchLocation => Construct(0x19d2b);
        public static FormLink<ILocationGetter> DLC2RRBulwarkJailLocation => Construct(0x19a26);
        public static FormLink<ILocationGetter> DLC2RRBulwarkLocation => Construct(0x19a25);
        public static FormLink<ILocationGetter> DLC2RRRetchingNetchLocation => Construct(0x19a24);
        public static FormLink<ILocationGetter> DLC2RRAlorHouseLocation => Construct(0x19a23);
        public static FormLink<ILocationGetter> DLC2RRGloverMalloryHouseLocation => Construct(0x19a22);
        public static FormLink<ILocationGetter> DLC2RRTempleLocation => Construct(0x19a21);
        public static FormLink<ILocationGetter> DLC2RRSeverinManorLocation => Construct(0x19a20);
        public static FormLink<ILocationGetter> DLC2RRIenthFarmLocation => Construct(0x19a1f);
        public static FormLink<ILocationGetter> DLC2RRCresciusHouseLocation => Construct(0x19a1e);
        public static FormLink<ILocationGetter> DLC2RRAbandonedBuildingLocation => Construct(0x19a1d);
        public static FormLink<ILocationGetter> DLC2RRMorvaynManorLocation => Construct(0x19a1c);
        public static FormLink<ILocationGetter> DLC2HighpointTowerLocation => Construct(0x184fc);
        public static FormLink<ILocationGetter> DLC2HrothmundsBarrowLocation => Construct(0x17bad);
        public static FormLink<ILocationGetter> DLC2ThirskMeadHallInteriorLocation => Construct(0x16ffe);
        public static FormLink<ILocationGetter> DLC2ApocryphaLocation => Construct(0x16e2b);
        public static FormLink<ILocationGetter> DLC2SolstheimLocation => Construct(0x16e2a);
        public static FormLink<ILocationGetter> DLC2TelMithrynLocation => Construct(0x143bc);
        public static FormLink<ILocationGetter> DLC2SkaalVillageLocation => Construct(0x143bb);
        public static FormLink<ILocationGetter> DLC2ThirskMeadHallLocation => Construct(0x143ba);
        public static FormLink<ILocationGetter> DLC2RavenRockLocation => Construct(0x143b9);
        public static FormLink<ILocationGetter> DLC2StoneWindLocation => Construct(0x142df);
        public static FormLink<ILocationGetter> DLC2StoneWaterLocation => Construct(0x142de);
        public static FormLink<ILocationGetter> DLC2StoneSunLocation => Construct(0x142dc);
        public static FormLink<ILocationGetter> DLC2MoesringPassLocation => Construct(0x142da);
        public static FormLink<ILocationGetter> DLC2POI13Location => Construct(0x142cc);
        public static FormLink<ILocationGetter> DLC2FrostmoonCragLocation => Construct(0x142cb);
        public static FormLink<ILocationGetter> DLC2BujoldsRetreatLocation => Construct(0x142ca);
        public static FormLink<ILocationGetter> DLC2StridentSquallLocation => Construct(0x142c9);
        public static FormLink<ILocationGetter> DLC2NorthshoreLandingLocation => Construct(0x142c7);
        public static FormLink<ILocationGetter> DLC2AshfallowLocation => Construct(0x142c5);
        public static FormLink<ILocationGetter> DLC2GlacialCaveLocation => Construct(0x142c4);
        public static FormLink<ILocationGetter> DLC2HrodulfsHouseLocation => Construct(0x142c3);
        public static FormLink<ILocationGetter> DLC2HaknirsShoalLocation => Construct(0x142c2);
        public static FormLink<ILocationGetter> DLC2BrokenTuskMineLocation => Construct(0x142c1);
        public static FormLink<ILocationGetter> DLC2AbandonedLodgeLocation => Construct(0x142c0);
        public static FormLink<ILocationGetter> DLC2WhiteRidgeBarrowLocation => Construct(0x142bc);
        public static FormLink<ILocationGetter> DLC2KolbjornBarrowLocation => Construct(0x142bb);
        public static FormLink<ILocationGetter> DLC2VahloksTombLocation => Construct(0x142ba);
        public static FormLink<ILocationGetter> DLC2TempleOfMiraakLocation => Construct(0x142b6);
        public static FormLink<ILocationGetter> DLC2NchardakLocation => Construct(0x142b4);
        public static FormLink<ILocationGetter> DLC2Book01DungeonLocation => Construct(0x142b0);
        public static FormLink<ILocationGetter> DLC2Book03DungeonLocation => Construct(0x142af);
        public static FormLink<ILocationGetter> DLC2Book07DungeonLocationNEW => Construct(0x142ae);
        public static FormLink<ILocationGetter> DLC2Book05DungeonLocation => Construct(0x142ac);
        public static FormLink<ILocationGetter> DLC2HorkerIslandLocation => Construct(0x142aa);
        public static FormLink<ILocationGetter> DLC2GyldenhulBarrowLocation => Construct(0x142a8);
        public static FormLink<ILocationGetter> DLC2FrosselLocation => Construct(0x142a6);
        public static FormLink<ILocationGetter> DLC2StoneEarthLocation => Construct(0x142a4);
        public static FormLink<ILocationGetter> DLC2KagrumezLocation => Construct(0x142a2);
        public static FormLink<ILocationGetter> DLC2FahlbtharzLocation => Construct(0x142a0);
        public static FormLink<ILocationGetter> DLC2CastleKarstaagRuinsLocation => Construct(0x1429e);
        public static FormLink<ILocationGetter> DLC2BrodirGroveLocation => Construct(0x1429c);
        public static FormLink<ILocationGetter> DLC2RavenRockMineLocation => Construct(0x1429a);
        public static FormLink<ILocationGetter> DLC2BenkongerikeLocation => Construct(0x14298);
        public static FormLink<ILocationGetter> DLC2StoneBeastLocation => Construct(0x14296);
        public static FormLink<ILocationGetter> DLC2AltarofThrondLocation => Construct(0x14294);
        public static FormLink<ILocationGetter> DLC2FortFrostmothLocation => Construct(0x14293);
    }
}
