// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Oblivion;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Oblivion;

public static partial class BattlehornCastle
{
    public static partial class IdleAnimation
    {
        private static FormLink<IIdleAnimationGetter> Construct(uint id) => new FormLink<IIdleAnimationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IIdleAnimationGetter> DLCBattlehornOpenGate => Construct(0x13918);
    }
}
