using Mutagen.Bethesda.Oblivion;

namespace Mutagen.Bethesda.FormKeys.Oblivion
{
    public static partial class Knights
    {
        public static class Activator
        {
            private readonly static ModKey ModKey = ModKey.FromNameAndExtension("Knights.esp");
            private static FormLink<IActivatorGetter> Construct(uint id) => new FormLink<IActivatorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IActivatorGetter> ND01ARGateNORESET => Construct(0xe2e);
            public static FormLink<IActivatorGetter> ND10TriggerZoneBattle02A => Construct(0xe2f);
            public static FormLink<IActivatorGetter> ND10TriggerZoneBattle02B => Construct(0xe30);
            public static FormLink<IActivatorGetter> ND10TriggerZoneBattle01B => Construct(0xe31);
            public static FormLink<IActivatorGetter> ND10TriggerZoneBattle01A => Construct(0xe32);
            public static FormLink<IActivatorGetter> NDBulwark02SwitchThedretCell => Construct(0xe33);
            public static FormLink<IActivatorGetter> NDVanuaTrigZone04 => Construct(0xe34);
            public static FormLink<IActivatorGetter> NDVanuaTrigZone03 => Construct(0xe35);
            public static FormLink<IActivatorGetter> RFSwitchLeverND01 => Construct(0xe36);
            public static FormLink<IActivatorGetter> NDKnightTombGregory => Construct(0xe37);
            public static FormLink<IActivatorGetter> NDKnightTombCasimir => Construct(0xe38);
            public static FormLink<IActivatorGetter> NDKnightTombTorolf => Construct(0xe39);
            public static FormLink<IActivatorGetter> NDKnightTombHenrik => Construct(0xe3a);
            public static FormLink<IActivatorGetter> NDKnightTombRalvas => Construct(0xe3b);
            public static FormLink<IActivatorGetter> NDKnightTombJuncan => Construct(0xe3c);
            public static FormLink<IActivatorGetter> NDKnightTombCaius => Construct(0xe3d);
            public static FormLink<IActivatorGetter> NDKnightTombAmiel => Construct(0xe3e);
            public static FormLink<IActivatorGetter> ND10FINSceneControl => Construct(0xe3f);
            public static FormLink<IActivatorGetter> ND10ARGate01 => Construct(0xe40);
            public static FormLink<IActivatorGetter> NDGarlasSteps => Construct(0xe41);
            public static FormLink<IActivatorGetter> ND10TestTrig => Construct(0xe42);
            public static FormLink<IActivatorGetter> ND05WallPlate => Construct(0xe43);
            public static FormLink<IActivatorGetter> ND10UmarilBattleControl => Construct(0xe44);
            public static FormLink<IActivatorGetter> NDTestPlasmaCloud => Construct(0xe45);
            public static FormLink<IActivatorGetter> ND10SkyBattleControl => Construct(0xe46);
            public static FormLink<IActivatorGetter> ND10BattleTrigger02 => Construct(0xe47);
            public static FormLink<IActivatorGetter> ND10BattleControl02 => Construct(0xe48);
            public static FormLink<IActivatorGetter> ND10TriggerZoneBattle02 => Construct(0xe49);
            public static FormLink<IActivatorGetter> ND10BattleTrigger01 => Construct(0xe4a);
            public static FormLink<IActivatorGetter> ND10BattleControl01 => Construct(0xe4b);
            public static FormLink<IActivatorGetter> ND10TriggerZoneBattle => Construct(0xe4c);
            public static FormLink<IActivatorGetter> NDArmorStandSword => Construct(0xe4d);
            public static FormLink<IActivatorGetter> NDArmorStandMace => Construct(0xe4e);
            public static FormLink<IActivatorGetter> NDArmorStandShield => Construct(0xe4f);
            public static FormLink<IActivatorGetter> NDArmorStandGreaves => Construct(0xe50);
            public static FormLink<IActivatorGetter> NDArmorStandGauntlets => Construct(0xe51);
            public static FormLink<IActivatorGetter> NDArmorStandBoots => Construct(0xe52);
            public static FormLink<IActivatorGetter> NDArmorStand => Construct(0xe53);
            public static FormLink<IActivatorGetter> NDArmorStandCuirass => Construct(0xe54);
            public static FormLink<IActivatorGetter> NDArmorStandHelm => Construct(0xe55);
            public static FormLink<IActivatorGetter> NDPrioryAnimatingStairs01 => Construct(0xe56);
            public static FormLink<IActivatorGetter> ND05GemChestStatue => Construct(0xe57);
            public static FormLink<IActivatorGetter> ND05SkullChestStatue => Construct(0xe58);
            public static FormLink<IActivatorGetter> ND05HammerChestStatue => Construct(0xe59);
            public static FormLink<IActivatorGetter> ND05BookChestStatue => Construct(0xe5a);
            public static FormLink<IActivatorGetter> ND05SwordChestStatue => Construct(0xe5b);
            public static FormLink<IActivatorGetter> ND05GobletChestStatue => Construct(0xe5c);
            public static FormLink<IActivatorGetter> ND05HelmChestStatue => Construct(0xe5d);
            public static FormLink<IActivatorGetter> ND05StoneChestStatue => Construct(0xe5e);
            public static FormLink<IActivatorGetter> NDVanuaTrigZone02 => Construct(0xe5f);
            public static FormLink<IActivatorGetter> NDVanuaTrigZone01 => Construct(0xe60);
            public static FormLink<IActivatorGetter> ND10SmiteItem => Construct(0xe61);
            public static FormLink<IActivatorGetter> ND10GarlasBarrier => Construct(0xe62);
            public static FormLink<IActivatorGetter> NDBossMinionTrigger => Construct(0xe63);
            public static FormLink<IActivatorGetter> ND02LightControl => Construct(0xe64);
            public static FormLink<IActivatorGetter> NDBulwark01PressurePlateMain => Construct(0xe65);
            public static FormLink<IActivatorGetter> NDBulwark01PressurePlateDummy => Construct(0xe66);
            public static FormLink<IActivatorGetter> NDBulwark01PressurePlate03 => Construct(0xe67);
            public static FormLink<IActivatorGetter> NDBulwark01PressurePlate02 => Construct(0xe68);
            public static FormLink<IActivatorGetter> NDBulwark01PressurePlate01 => Construct(0xe69);
            public static FormLink<IActivatorGetter> ND06Altar => Construct(0xe6a);
            public static FormLink<IActivatorGetter> ND02TriggerZone01 => Construct(0xe6b);
            public static FormLink<IActivatorGetter> ND02TriggerZone02 => Construct(0xe6c);
            public static FormLink<IActivatorGetter> ND02BattleControl => Construct(0xe6d);
            public static FormLink<IActivatorGetter> ND02ActArmorCuirass => Construct(0xe6e);
            public static FormLink<IActivatorGetter> NDBossRoomFXTrigger01 => Construct(0xe6f);
            public static FormLink<IActivatorGetter> NDBossRoomFXTrigger02 => Construct(0xe70);
            public static FormLink<IActivatorGetter> NDSpellTarget => Construct(0xe71);
            public static FormLink<IActivatorGetter> NDGarlasSpellTarget01 => Construct(0xe72);
            public static FormLink<IActivatorGetter> NDGarlasSpellTrap01 => Construct(0xe73);
            public static FormLink<IActivatorGetter> NDBulwark02Portcullis01 => Construct(0xe74);
            public static FormLink<IActivatorGetter> NDBulwark02DrawBridgeRAISED01 => Construct(0xe75);
            public static FormLink<IActivatorGetter> NDBulwark02Switch01 => Construct(0xe76);
            public static FormLink<IActivatorGetter> NDBulwark02DartsDEADLY01 => Construct(0xe77);
            public static FormLink<IActivatorGetter> ND05Statue04 => Construct(0xe78);
            public static FormLink<IActivatorGetter> ND05Statue03 => Construct(0xe79);
            public static FormLink<IActivatorGetter> ND05Statue02 => Construct(0xe7a);
            public static FormLink<IActivatorGetter> ND05Statue01 => Construct(0xe7b);
            public static FormLink<IActivatorGetter> ND04BattleTrigger => Construct(0xe7c);
            public static FormLink<IActivatorGetter> ND08TombDELETEME => Construct(0xe7d);
            public static FormLink<IActivatorGetter> ND03SecretDoor => Construct(0xe7e);
            public static FormLink<IActivatorGetter> ND04Altar => Construct(0xe7f);
            public static FormLink<IActivatorGetter> ND04TriggerZoneFall => Construct(0xe80);
            public static FormLink<IActivatorGetter> ND05PressurePlate => Construct(0xe81);
            public static FormLink<IActivatorGetter> ND05ActSword => Construct(0xe82);
            public static FormLink<IActivatorGetter> ND05ActStone => Construct(0xe83);
            public static FormLink<IActivatorGetter> ND05ActSkull => Construct(0xe84);
            public static FormLink<IActivatorGetter> ND05ActHelm => Construct(0xe85);
            public static FormLink<IActivatorGetter> ND05ActHammer => Construct(0xe86);
            public static FormLink<IActivatorGetter> ND05ActGoblet => Construct(0xe87);
            public static FormLink<IActivatorGetter> ND05ActGem => Construct(0xe88);
            public static FormLink<IActivatorGetter> ND05ActBook => Construct(0xe89);
            public static FormLink<IActivatorGetter> NDActArmorShield => Construct(0xe8a);
            public static FormLink<IActivatorGetter> ND01ActArmorHelmet => Construct(0xe8b);
            public static FormLink<IActivatorGetter> NDActArmorBoots => Construct(0xe8c);
            public static FormLink<IActivatorGetter> NDActArmorGauntlets => Construct(0xe8d);
            public static FormLink<IActivatorGetter> NDActWeaponMace => Construct(0xe8e);
            public static FormLink<IActivatorGetter> ND08CathedralAltar01 => Construct(0xe8f);
            public static FormLink<IActivatorGetter> ND02PrioryDoor => Construct(0xe90);
        }
    }
}
