// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class Update
{
    public static partial class Armor
    {
        private static FormLink<IArmorGetter> Construct(uint id) => new FormLink<IArmorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IArmorGetter> CCHorseArmorSteelUnicorn => Construct(0x30cc);
        public static FormLink<IArmorGetter> CCHorseArmorElvenUnicorn => Construct(0x30cb);
        public static FormLink<IArmorGetter> CCHorseArmorSteel => Construct(0x30bd);
        public static FormLink<IArmorGetter> CCHorseArmorElven => Construct(0x30bc);
        public static FormLink<IArmorGetter> CCHorseArmorDummy => Construct(0x30ba);
    }
}
