// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class Update
    {
        public static class Door
        {
            private static FormLink<IDoorGetter> Construct(uint id) => new FormLink<IDoorGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IDoorGetter> ccBGS_ARGateDoor01 => Construct(0x3160);
            public static FormLink<IDoorGetter> ccBGS_ARDoor01MinUse => Construct(0x315f);
            public static FormLink<IDoorGetter> ccBGS_ARDoor01b => Construct(0x315e);
            public static FormLink<IDoorGetter> ccBGS_ARDoor01 => Construct(0x315d);
            public static FormLink<IDoorGetter> ccRMSSSE001_ImpDoorExtHoleDoorLoad01 => Construct(0x30db);
            public static FormLink<IDoorGetter> SDoorManholeCoverInvisible => Construct(0x308b);
            public static FormLink<IDoorGetter> ccEEJSSE003_RiftenRWDoorLoad01 => Construct(0x2fca);
            public static FormLink<IDoorGetter> ccEEJSSE003_RiftenRWDoorJail01 => Construct(0x2fc8);
            public static FormLink<IDoorGetter> ccBGSSSE043_FarmBTrapdoor01 => Construct(0x2fc6);
            public static FormLink<IDoorGetter> ccBGSSSE043_FarmBTrapdoor02 => Construct(0x2fc5);
            public static FormLink<IDoorGetter> CreationClubPlaceHolderDoor => Construct(0x2f3b);
        }
    }
}
