using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class Dragonborn
    {
        public static class Faction
        {
            private readonly static ModKey ModKey = ModKey.FromNameAndExtension("Dragonborn.esm");
            private static FormLink<IFactionGetter> Construct(uint id) => new FormLink<IFactionGetter>(ModKey.MakeFormKey(id));
            public static FormLink<IFactionGetter> DLC2SVMorwensBedFaction => Construct(0x1dc43);
            public static FormLink<IFactionGetter> DLC2MQ06MiraakFaction => Construct(0x3d5c4);
            public static FormLink<IFactionGetter> DLC2RR01VelethAllyFaction => Construct(0x3d3ae);
            public static FormLink<IFactionGetter> DLC2MorasGraspExcludedFaction => Construct(0x3d2fb);
            public static FormLink<IFactionGetter> DLC2TamedDragonTrackingFaction => Construct(0x3d2f3);
            public static FormLink<IFactionGetter> DLC2ThirskNordCrimeFaction => Construct(0x3d126);
            public static FormLink<IFactionGetter> DLC2MH02SpecialCombatFaction => Construct(0x3bda0);
            public static FormLink<IFactionGetter> DLC2HunterFaction => Construct(0x3a4ca);
            public static FormLink<IFactionGetter> DLC2RavenRockMinersFaction => Construct(0x39d11);
            public static FormLink<IFactionGetter> DLC2BookReadingCommentFaction => Construct(0x398e9);
            public static FormLink<IFactionGetter> DLC2ApoTentacleNoHitFaction => Construct(0x397e3);
            public static FormLink<IFactionGetter> DLC2TTF1AshGuardianFriendFaction => Construct(0x39231);
            public static FormLink<IFactionGetter> DLC2HirelingTeldrynCrimeFaction => Construct(0x38562);
            public static FormLink<IFactionGetter> DLC2ApocryphaTrapOwnerFaction => Construct(0x3789d);
            public static FormLink<IFactionGetter> DLC2NorthernMaidenFaction => Construct(0x376f3);
            public static FormLink<IFactionGetter> DLC2ServicesThirskElmus => Construct(0x3572d);
            public static FormLink<IFactionGetter> DLC2CultistFaction => Construct(0x34fbc);
            public static FormLink<IFactionGetter> DLC2MQ02AllyFaction => Construct(0x34b93);
            public static FormLink<IFactionGetter> DLC2Book01Seeker3rdFloorFaction => Construct(0x339cd);
            public static FormLink<IFactionGetter> DLC2Book01Seeker2ndFloorFaction => Construct(0x339cc);
            public static FormLink<IFactionGetter> DLC2Book01Seeker1stFloorFaction => Construct(0x339cb);
            public static FormLink<IFactionGetter> dlc2MerchMerchantFaction => Construct(0x32801);
            public static FormLink<IFactionGetter> DLC2WyrmFaction => Construct(0x31846);
            public static FormLink<IFactionGetter> DLC2SkaalDialogueFaction => Construct(0x31786);
            public static FormLink<IFactionGetter> DLC2ApocryphaFaction => Construct(0x2bc5e);
            public static FormLink<IFactionGetter> DLC2MiraakFaction => Construct(0x2bc5d);
            public static FormLink<IFactionGetter> DLC2MiraakDragonAllyFaction => Construct(0x2bc5c);
            public static FormLink<IFactionGetter> DLC2BenthicLurkerFaction => Construct(0x2b0f2);
            public static FormLink<IFactionGetter> DLC2MoragTongFaction => Construct(0x2929a);
            public static FormLink<IFactionGetter> DLC2SeekerFaction => Construct(0x2856c);
            public static FormLink<IFactionGetter> DLC2AncarionServicesFaction => Construct(0x27e12);
            public static FormLink<IFactionGetter> DLC2DremoraPCAlly => Construct(0x279ec);
            public static FormLink<IFactionGetter> DLC2BBReward3Exclude => Construct(0x279eb);
            public static FormLink<IFactionGetter> DLC2WaterStoneSailors => Construct(0x2783f);
            public static FormLink<IFactionGetter> DLC2dunKolbjornMinerFaction => Construct(0x27802);
            public static FormLink<IFactionGetter> DLC2SkaalShamanFaction => Construct(0x27291);
            public static FormLink<IFactionGetter> DLC2MogrulFaction => Construct(0x271ff);
            public static FormLink<IFactionGetter> DLC2ServicesThirskHalbarn => Construct(0x27107);
            public static FormLink<IFactionGetter> DLC2SV01TombFaction => Construct(0x265fe);
            public static FormLink<IFactionGetter> DLC2TribalWerebearFaction => Construct(0x2655f);
            public static FormLink<IFactionGetter> DLC2MQ02Faction => Construct(0x2645d);
            public static FormLink<IFactionGetter> DLC2NetchFaction => Construct(0x2507c);
            public static FormLink<IFactionGetter> DLC2RRServicesRavenRockGeldis => Construct(0x25028);
            public static FormLink<IFactionGetter> DLC2RRServicesRavenRockGlover => Construct(0x25027);
            public static FormLink<IFactionGetter> DLC2RRServicesRavenRockGaryn => Construct(0x25026);
            public static FormLink<IFactionGetter> DLC2RRServicesRavenRockFethis => Construct(0x25025);
            public static FormLink<IFactionGetter> DLC2RRServicesRavenRockMilore => Construct(0x2501a);
            public static FormLink<IFactionGetter> DLC2BanditDialogueFaction => Construct(0x24cab);
            public static FormLink<IFactionGetter> DLC2MQ06HostileFaction => Construct(0x23f77);
            public static FormLink<IFactionGetter> DLC2MQ06NonHostileFaction => Construct(0x23f72);
            public static FormLink<IFactionGetter> DLC2SV02ThalmorCrimeFaction => Construct(0x2173a);
            public static FormLink<IFactionGetter> DLC2ThirskRieklingFaction => Construct(0x208d9);
            public static FormLink<IFactionGetter> DLC2BendWillImmuneFaction => Construct(0x200e7);
            public static FormLink<IFactionGetter> DLC2BendWillFollowerFaction => Construct(0x1ff1d);
            public static FormLink<IFactionGetter> DLC2MQ06DragonFaction => Construct(0x1fb95);
            public static FormLink<IFactionGetter> DLC2SkaalBlacksmith => Construct(0x1f899);
            public static FormLink<IFactionGetter> DLC2SkaalMerchant => Construct(0x1f88c);
            public static FormLink<IFactionGetter> DLC2DremoraMerchantFaction => Construct(0x1eec4);
            public static FormLink<IFactionGetter> DLC2MQ05DragonFaction => Construct(0x1e8bd);
            public static FormLink<IFactionGetter> DLC2MQ05AllyFaction => Construct(0x1e8bc);
            public static FormLink<IFactionGetter> DLC2dunFrostmoonWerewolvesVendorFaction => Construct(0x1dc62);
            public static FormLink<IFactionGetter> DLC2dunFrostmoonWerewolvesFaction => Construct(0x1dc61);
            public static FormLink<IFactionGetter> DLC2RieklingFaction => Construct(0x1d9c9);
            public static FormLink<IFactionGetter> DLC2SummonedAshGuardianFaction => Construct(0x1d750);
            public static FormLink<IFactionGetter> DLC2PillarBuilderFaction => Construct(0x1c4e5);
            public static FormLink<IFactionGetter> DLC2AshSpawnFaction => Construct(0x1b63b);
            public static FormLink<IFactionGetter> DLC2MQ02MiraakEnemyFaction => Construct(0x1aaf9);
            public static FormLink<IFactionGetter> DLC2ThirskNordFaction => Construct(0x1a514);
            public static FormLink<IFactionGetter> DLC2MQ04MiraakEnemyFaction => Construct(0x19ccd);
            public static FormLink<IFactionGetter> DLC2MQ04MiraakFaction => Construct(0x19ccc);
            public static FormLink<IFactionGetter> DLC2StaffMakerFaction => Construct(0x19b8a);
            public static FormLink<IFactionGetter> DLC2RavenRockGuardFaction => Construct(0x195ad);
            public static FormLink<IFactionGetter> DLC2SVGreathallFaction => Construct(0x18fc6);
            public static FormLink<IFactionGetter> DLC2SVEdlasHouseFaction => Construct(0x18fbc);
            public static FormLink<IFactionGetter> DLC2SVBaldorIronShapersHouseFaction => Construct(0x18fb6);
            public static FormLink<IFactionGetter> DLC2SVWulfWildbloodsHouseFaction => Construct(0x18faf);
            public static FormLink<IFactionGetter> DLC2SVMorwensHouseFaction => Construct(0x18fab);
            public static FormLink<IFactionGetter> DLC2SVDeorWoodcuttersHouseFaction => Construct(0x18fa6);
            public static FormLink<IFactionGetter> DLC2SVOslafsHouseFaction => Construct(0x18f9b);
            public static FormLink<IFactionGetter> DLC2SkaalVillageCitizenFaction => Construct(0x18f9a);
            public static FormLink<IFactionGetter> DLC2RRBeggarFaction => Construct(0x18f1e);
            public static FormLink<IFactionGetter> DLC2RRSeverinSpouseFaction => Construct(0x184d1);
            public static FormLink<IFactionGetter> DLC2RRCresciusSpouseFaction => Construct(0x184c9);
            public static FormLink<IFactionGetter> DLC2RRAlorHouseFaction => Construct(0x184bd);
            public static FormLink<IFactionGetter> DLC2RRAranoSpouseFaction => Construct(0x184a9);
            public static FormLink<IFactionGetter> DLC2RRIenthFarmFaction => Construct(0x18426);
            public static FormLink<IFactionGetter> DLC2RRSeverinManorFaction => Construct(0x18425);
            public static FormLink<IFactionGetter> DLC2RRCresciusCaerelliusHouseFaction => Construct(0x18424);
            public static FormLink<IFactionGetter> DLC2RRGloverMalloryFaction => Construct(0x18423);
            public static FormLink<IFactionGetter> DLC2RRNetchFaction => Construct(0x18421);
            public static FormLink<IFactionGetter> DLC2RRTempleFaction => Construct(0x18420);
            public static FormLink<IFactionGetter> DLC2RRBulwarkFaction => Construct(0x1841f);
            public static FormLink<IFactionGetter> DLC2RRMorvaynManorFaction => Construct(0x1841e);
            public static FormLink<IFactionGetter> DLC2CrimeRavenRockFaction => Construct(0x18279);
            public static FormLink<IFactionGetter> DLC2TameDragonFaction => Construct(0x17ebd);
            public static FormLink<IFactionGetter> DLC2ExpSpiderFriendFaction => Construct(0x17964);
            public static FormLink<IFactionGetter> DLC2ExpSpiderEnemyFaction => Construct(0x17960);
            public static FormLink<IFactionGetter> DLC2ServicesTelMithrynNeloth => Construct(0x177c7);
            public static FormLink<IFactionGetter> DLC2ServicesTelMithrynTalvas => Construct(0x177c6);
            public static FormLink<IFactionGetter> DLC2ServicesTelMithrynElynea => Construct(0x177c5);
            public static FormLink<IFactionGetter> DLC2encAshGuardianFaction => Construct(0x17785);
            public static FormLink<IFactionGetter> DLC2TelMithrynFaction => Construct(0x17775);
        }
    }
}
