// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Fallout4
{
    public static class BendableSpline
    {
        private static FormLink<IBendableSplineGetter> Construct(uint id) => new FormLink<IBendableSplineGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBendableSplineGetter> RopeSpline01_Wind => Construct(0x240c29);
        public static FormLink<IBendableSplineGetter> RedWireSpline01_Wind => Construct(0x240c28);
        public static FormLink<IBendableSplineGetter> BlackWireTowerSpline01_Wind => Construct(0x240c27);
        public static FormLink<IBendableSplineGetter> MetalCableSpline01_Wind => Construct(0x240c26);
        public static FormLink<IBendableSplineGetter> BlackWireSpline02_Wind => Construct(0x240c25);
        public static FormLink<IBendableSplineGetter> BlackWireSpline01_Wind => Construct(0x240c24);
        public static FormLink<IBendableSplineGetter> RedWireSpline01 => Construct(0x35a21);
        public static FormLink<IBendableSplineGetter> BlackWireTowerSpline01 => Construct(0x7cdac);
        public static FormLink<IBendableSplineGetter> BlackWireSpline02 => Construct(0x1d972);
        public static FormLink<IBendableSplineGetter> BlackWireSpline01 => Construct(0x1d971);
        public static FormLink<IBendableSplineGetter> RopeSpline01 => Construct(0x21f34);
        public static FormLink<IBendableSplineGetter> MetalCableSpline01 => Construct(0x37213);
    }
}
