// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Fallout4
{
    public static class Flora
    {
        private static FormLink<IFloraGetter> Construct(uint id) => new FormLink<IFloraGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFloraGetter> FloraGSWildMelonVine01 => Construct(0x1f24b5);
        public static FormLink<IFloraGetter> BoSExperiment01 => Construct(0x1ee1fd);
        public static FormLink<IFloraGetter> FloraWildTatoPlant02 => Construct(0x1c4bef);
        public static FormLink<IFloraGetter> FloraWildCornStalk01 => Construct(0x1c4014);
        public static FormLink<IFloraGetter> FloraWildCarrotPlant => Construct(0x1c400c);
        public static FormLink<IFloraGetter> FloraWildRazorgrain01 => Construct(0x1c400b);
        public static FormLink<IFloraGetter> FloraWildGourdVine01 => Construct(0x1c400a);
        public static FormLink<IFloraGetter> FloraWildMelonVine01 => Construct(0x1c4009);
        public static FormLink<IFloraGetter> FloraWildTatoPlant01 => Construct(0x1c4008);
        public static FormLink<IFloraGetter> FloraFungusBrain02 => Construct(0x1c0fcf);
        public static FormLink<IFloraGetter> FloraFungusBrain01 => Construct(0x1c0fce);
        public static FormLink<IFloraGetter> FloraFungusGlowing06 => Construct(0x1c0fcd);
        public static FormLink<IFloraGetter> FloraFungusGlowing05 => Construct(0x1c0fcc);
        public static FormLink<IFloraGetter> FloraFungusGlowing04 => Construct(0x1c0fcb);
        public static FormLink<IFloraGetter> FloraFungusGlowing03 => Construct(0x1c0fca);
        public static FormLink<IFloraGetter> FloraFungusGlowing02 => Construct(0x1c0fc9);
        public static FormLink<IFloraGetter> FloraFungusGlowing01 => Construct(0x1c0fc8);
        public static FormLink<IFloraGetter> FloraFungusBrain03 => Construct(0x1c0fc7);
        public static FormLink<IFloraGetter> FloraBloodLeaf02 => Construct(0x1c0e6c);
        public static FormLink<IFloraGetter> FloraBloodLeaf01 => Construct(0x1c0e6b);
        public static FormLink<IFloraGetter> FloraHubFlower01 => Construct(0x1c0e69);
        public static FormLink<IFloraGetter> FloraHubFlower02 => Construct(0x1c0e66);
        public static FormLink<IFloraGetter> FloraSiltBean02 => Construct(0x1bceb0);
        public static FormLink<IFloraGetter> FloraSiltBean01 => Construct(0x1bceac);
        public static FormLink<IFloraGetter> FloraWildTarberryFloat02 => Construct(0x66548);
        public static FormLink<IFloraGetter> FloraWildTarberryFloat01 => Construct(0x66544);
        public static FormLink<IFloraGetter> FloraInsCornStalk02 => Construct(0x4512b);
        public static FormLink<IFloraGetter> FloraInsCornStalk01 => Construct(0x450f7);
        public static FormLink<IFloraGetter> Vault81Planter01Melon01 => Construct(0x1994b0);
        public static FormLink<IFloraGetter> Vault81Planter01Corn01 => Construct(0x1994af);
        public static FormLink<IFloraGetter> Vault81Planter01Carrot01 => Construct(0x1994ad);
        public static FormLink<IFloraGetter> FloraInstituteGourdVine01 => Construct(0x106a40);
        public static FormLink<IFloraGetter> GreenHsPlanter01Mutfruit => Construct(0x100cab);
        public static FormLink<IFloraGetter> GreenHsPlanter01Carrot => Construct(0x100ca3);
        public static FormLink<IFloraGetter> GreenHsPlanterGourd01 => Construct(0x100ca2);
        public static FormLink<IFloraGetter> GreenHsPlanterMelon01 => Construct(0x100ca1);
        public static FormLink<IFloraGetter> GreenHsPlanterTato01 => Construct(0x100c9a);
        public static FormLink<IFloraGetter> GreenHsPlanter01Corn => Construct(0x100c90);
        public static FormLink<IFloraGetter> FloraFern02 => Construct(0xe34eb);
        public static FormLink<IFloraGetter> FloraFern01 => Construct(0xe34ea);
        public static FormLink<IFloraGetter> FloraMelonVine01 => Construct(0xfafe7);
        public static FormLink<IFloraGetter> FloraCarrotPlant => Construct(0xf5d8f);
        public static FormLink<IFloraGetter> FloraGourdVine01 => Construct(0xef24a);
        public static FormLink<IFloraGetter> FloraCornStalk02 => Construct(0xe7745);
        public static FormLink<IFloraGetter> FloraCornStalk01 => Construct(0xe7744);
        public static FormLink<IFloraGetter> FloraRazorgrain02 => Construct(0xe0063);
        public static FormLink<IFloraGetter> FloraTarberryFloat01 => Construct(0xe004e);
        public static FormLink<IFloraGetter> FloraTarberryFloat02 => Construct(0xe004d);
        public static FormLink<IFloraGetter> FloraRazorgrain01 => Construct(0xe004b);
        public static FormLink<IFloraGetter> FloraWildMutfruit => Construct(0xa2958);
        public static FormLink<IFloraGetter> FloraMutfruit01 => Construct(0x9d107);
        public static FormLink<IFloraGetter> FloraTatoPlant02 => Construct(0x88fad);
        public static FormLink<IFloraGetter> FloraTatoPlant01 => Construct(0x88fac);
    }
}
