// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Fallout4
{
    public static partial class Grass
    {
        private static FormLink<IGrassGetter> Construct(uint id) => new FormLink<IGrassGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGrassGetter> GSRockGrassObj02 => Construct(0x23ad22);
        public static FormLink<IGrassGetter> DriedGrassLongObj01Sparse => Construct(0x23888f);
        public static FormLink<IGrassGetter> DebrisRubbleHightech02 => Construct(0x1d1ada);
        public static FormLink<IGrassGetter> DebrisRubbleHightech01 => Construct(0x1d1ad9);
        public static FormLink<IGrassGetter> DebrisRubbleHightech03 => Construct(0x1d1ad8);
        public static FormLink<IGrassGetter> DriedGrassObj01ForWoodPile => Construct(0x1c4da1);
        public static FormLink<IGrassGetter> DebrisRubbleObj06 => Construct(0x1c40a8);
        public static FormLink<IGrassGetter> RockGrassObj02 => Construct(0x1b2ce0);
        public static FormLink<IGrassGetter> DebrisRubbleObj05 => Construct(0x1ac8a2);
        public static FormLink<IGrassGetter> DebrisRubbleObj04 => Construct(0x1ac899);
        public static FormLink<IGrassGetter> DebrisRubbleBrickObj01 => Construct(0xb37c1);
        public static FormLink<IGrassGetter> DebrisRubbleObj03 => Construct(0xb37c0);
        public static FormLink<IGrassGetter> DebrisRubbleObj02 => Construct(0xb37bf);
        public static FormLink<IGrassGetter> DebrisRubbleObj01 => Construct(0xb37be);
        public static FormLink<IGrassGetter> DebrisRubbleObj01Dense => Construct(0xb378c);
        public static FormLink<IGrassGetter> RiverRockWetGrassObj01 => Construct(0x1a4d79);
        public static FormLink<IGrassGetter> RiverRockWetGrassObj02 => Construct(0x1a4d78);
        public static FormLink<IGrassGetter> ForestGrassObj03_Heavy => Construct(0x19df1d);
        public static FormLink<IGrassGetter> NF_Grass02Obj02_Sparse => Construct(0x19df0e);
        public static FormLink<IGrassGetter> NF_Grass02Obj01 => Construct(0x19df0a);
        public static FormLink<IGrassGetter> NF_Grass01Obj01 => Construct(0x19df09);
        public static FormLink<IGrassGetter> RiverGrassObj02 => Construct(0x1793df);
        public static FormLink<IGrassGetter> RiverGrassObj01 => Construct(0x1793de);
        public static FormLink<IGrassGetter> TallKelpGrassObj03 => Construct(0x166727);
        public static FormLink<IGrassGetter> TallKelpGrassObj02 => Construct(0x166726);
        public static FormLink<IGrassGetter> TallKelpGrassObj01 => Construct(0x166724);
        public static FormLink<IGrassGetter> RedKelpGrassObj02 => Construct(0x166723);
        public static FormLink<IGrassGetter> RedKelpGrassObj01 => Construct(0x166722);
        public static FormLink<IGrassGetter> BlastedForestTwigsObj02 => Construct(0x12c09b);
        public static FormLink<IGrassGetter> BlastedForestTwigsObj01 => Construct(0x12c09a);
        public static FormLink<IGrassGetter> BlastedForestRocksObj02 => Construct(0x12c096);
        public static FormLink<IGrassGetter> BlastedForestRocksObj01 => Construct(0x12c095);
        public static FormLink<IGrassGetter> BlastedForestGrassObj02 => Construct(0x12c091);
        public static FormLink<IGrassGetter> BlastedForestGrassObj01 => Construct(0x12c090);
        public static FormLink<IGrassGetter> PreWarForestGrassObj04 => Construct(0x12630f);
        public static FormLink<IGrassGetter> PreWarForestGrassObj03 => Construct(0x12630e);
        public static FormLink<IGrassGetter> PreWarForestGrassObj02 => Construct(0x12630d);
        public static FormLink<IGrassGetter> PreWarForestGrassObj01 => Construct(0x12630c);
        public static FormLink<IGrassGetter> PreWarWildGrassObj03 => Construct(0x12630b);
        public static FormLink<IGrassGetter> PreWarWildGrassObj02 => Construct(0x126308);
        public static FormLink<IGrassGetter> PreWarWildGrassObj01 => Construct(0x126307);
        public static FormLink<IGrassGetter> PreWarLawnGrassObj03 => Construct(0x1240f5);
        public static FormLink<IGrassGetter> PreWarLawnGrassObj02 => Construct(0x1240f4);
        public static FormLink<IGrassGetter> PreWarLawnGrassObj01 => Construct(0x1240f3);
        public static FormLink<IGrassGetter> MarshGrassObj04 => Construct(0x10e9af);
        public static FormLink<IGrassGetter> MarshGrassObj03 => Construct(0x10e9ae);
        public static FormLink<IGrassGetter> MarshGrassObj02 => Construct(0x10c70c);
        public static FormLink<IGrassGetter> MarshGrassObj01 => Construct(0x109809);
        public static FormLink<IGrassGetter> GSRockGrassObj01 => Construct(0xe2e75);
        public static FormLink<IGrassGetter> GSMudPileGrassObj03 => Construct(0xeca07);
        public static FormLink<IGrassGetter> GSRubbleGrassObj02 => Construct(0xeafbd);
        public static FormLink<IGrassGetter> GSRubbleGrassObj01 => Construct(0xeafbc);
        public static FormLink<IGrassGetter> GSMudPileGrassObj02 => Construct(0xe971b);
        public static FormLink<IGrassGetter> GSMudPileGrassObj01 => Construct(0xe971a);
        public static FormLink<IGrassGetter> GSCrackedMudGrassObj03 => Construct(0xe879f);
        public static FormLink<IGrassGetter> GSCrackedMudGrassObj02 => Construct(0xe879e);
        public static FormLink<IGrassGetter> GSCrackedMudGrassObj01 => Construct(0xe879d);
        public static FormLink<IGrassGetter> RockGrassObj01Sparse => Construct(0xc55f4);
        public static FormLink<IGrassGetter> ForestGrassObj03Sparse => Construct(0xc55f0);
        public static FormLink<IGrassGetter> DriedGrassObj01Clumps => Construct(0xc55ef);
        public static FormLink<IGrassGetter> RiverRockGrassObj02 => Construct(0xba521);
        public static FormLink<IGrassGetter> RiverRockGrassObj01 => Construct(0xba520);
        public static FormLink<IGrassGetter> CoastRockGrassObj01 => Construct(0xba4f1);
        public static FormLink<IGrassGetter> BeachGrassObj02 => Construct(0xab731);
        public static FormLink<IGrassGetter> BeachGrassObj01 => Construct(0xab72f);
        public static FormLink<IGrassGetter> GrassphaltObj03 => Construct(0x44181);
        public static FormLink<IGrassGetter> GrassphaltObj02 => Construct(0x44180);
        public static FormLink<IGrassGetter> GrassphaltObj01 => Construct(0x4417e);
        public static FormLink<IGrassGetter> DriedGrassLongObj02 => Construct(0x13ae1);
        public static FormLink<IGrassGetter> DriedGrassLongObj01 => Construct(0x8e9eb);
        public static FormLink<IGrassGetter> ForestGrassObj04 => Construct(0x8b122);
        public static FormLink<IGrassGetter> ForestGrassObj03 => Construct(0x89201);
        public static FormLink<IGrassGetter> ForestGrassObj02 => Construct(0x87900);
        public static FormLink<IGrassGetter> ForestGrassObj01 => Construct(0x878ff);
        public static FormLink<IGrassGetter> DriedGrassObj01Sparse => Construct(0x84766);
        public static FormLink<IGrassGetter> RockGrassObj01 => Construct(0x84764);
        public static FormLink<IGrassGetter> BentGrassObj01 => Construct(0x6e619);
        public static FormLink<IGrassGetter> MeadowGrassObj02 => Construct(0x4a04a);
        public static FormLink<IGrassGetter> MeadowGrassObj01 => Construct(0x39dbf);
        public static FormLink<IGrassGetter> DriedGrassObj01 => Construct(0x1d407);
        public static FormLink<IGrassGetter> DriedGrassObj02 => Construct(0x1d9a7);
        public static FormLink<IGrassGetter> DriedGrassObj03 => Construct(0x22b62);
    }
}
