// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Fallout4
{
    public static partial class IdleMarker
    {
        private static FormLink<IIdleMarkerGetter> Construct(uint id) => new FormLink<IIdleMarkerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IIdleMarkerGetter> RobotWorkshopMarker => Construct(0x249f17);
        public static FormLink<IIdleMarkerGetter> StandingLoopIdleMarker => Construct(0x238f0a);
        public static FormLink<IIdleMarkerGetter> MQ206IngramConsoleMarker => Construct(0x2305d0);
        public static FormLink<IIdleMarkerGetter> CowerLoopingIdleMarker => Construct(0x20c2c4);
        public static FormLink<IIdleMarkerGetter> MrHandyTrailerMarker => Construct(0x1d1ad0);
        public static FormLink<IIdleMarkerGetter> NPCUsePipBoy => Construct(0x1cb006);
        public static FormLink<IIdleMarkerGetter> NPCUseJet => Construct(0x1b9b83);
        public static FormLink<IIdleMarkerGetter> MrHandyGardening => Construct(0x1b19b8);
        public static FormLink<IIdleMarkerGetter> MrHandyWeldingLeftArm => Construct(0x1acbfa);
        public static FormLink<IIdleMarkerGetter> MrHandyMaintenance => Construct(0x19d592);
        public static FormLink<IIdleMarkerGetter> MrHandyWeldingRightArm => Construct(0x1538d9);
        public static FormLink<IIdleMarkerGetter> NPCMilitaryPoseIdleMarkerChild => Construct(0x14eb06);
        public static FormLink<IIdleMarkerGetter> InstituteGorillaIdleMarker => Construct(0xcff66);
        public static FormLink<IIdleMarkerGetter> NPCLockpickingMediumHeightIdleMarker => Construct(0xbd694);
        public static FormLink<IIdleMarkerGetter> HeldHostageIdleMarker => Construct(0xa51e4);
        public static FormLink<IIdleMarkerGetter> CharGenCodsworthRattleMarker => Construct(0x3f8b0);
        public static FormLink<IIdleMarkerGetter> DogmeatIdleMarkerSniffScratch => Construct(0x19fcca);
        public static FormLink<IIdleMarkerGetter> NPCPowerArmorExamineIdleMarker => Construct(0x197e67);
        public static FormLink<IIdleMarkerGetter> DNPrime_BoS304_PrimePunch01 => Construct(0x17ee2a);
        public static FormLink<IIdleMarkerGetter> DNPrime_BoS304_PrimeScan01 => Construct(0x17ee26);
        public static FormLink<IIdleMarkerGetter> CharGenCodsworthDustIdleMarker => Construct(0x17ca33);
        public static FormLink<IIdleMarkerGetter> NPCHandsUpIdleMarker => Construct(0x17ca30);
        public static FormLink<IIdleMarkerGetter> NPCMilitaryPoseIdleMarker => Construct(0x161f26);
        public static FormLink<IIdleMarkerGetter> NPCNeedlePrepIdleMarker => Construct(0x15efb8);
        public static FormLink<IIdleMarkerGetter> MQ101MrCallahanIdleMarker => Construct(0x15e91e);
        public static FormLink<IIdleMarkerGetter> AssaultronShopkeeperIdleMarker => Construct(0x15a402);
        public static FormLink<IIdleMarkerGetter> MrHandyPatrolIdleMarkerSandboxable => Construct(0x14dd59);
        public static FormLink<IIdleMarkerGetter> NPCStandingExamineIdleMarker => Construct(0x14b737);
        public static FormLink<IIdleMarkerGetter> NPCHoldingClipboardIdleMarker => Construct(0x122f9e);
        public static FormLink<IIdleMarkerGetter> NPCLockpickingLowHeightIdleMarker => Construct(0x11b184);
        public static FormLink<IIdleMarkerGetter> MrHandyTrimHedgesIdleMarker_Workshop => Construct(0x10f1e6);
        public static FormLink<IIdleMarkerGetter> NPCSmokeIdleMarker => Construct(0xe210e);
        public static FormLink<IIdleMarkerGetter> SentryBotIdleBlockDoor => Construct(0xb3dbc);
        public static FormLink<IIdleMarkerGetter> EmptyIdleMarker => Construct(0x91c84);
        public static FormLink<IIdleMarkerGetter> MrHandyPatrolIdleMarker => Construct(0x6aac4);
        public static FormLink<IIdleMarkerGetter> MrHandyTrimHedgesIdleMarker => Construct(0x68041);
        public static FormLink<IIdleMarkerGetter> NPCShoppingIdleMarker => Construct(0x1f86d);
        public static FormLink<IIdleMarkerGetter> PatrolIdleMarker => Construct(0x2ce2);
        public static FormLink<IIdleMarkerGetter> MarcyPatrolIdleMarker => Construct(0x2670a);
    }
}
