// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Fallout4;

public static partial class Fallout4
{
    public static partial class ReverbParameters
    {
        private static FormLink<IReverbParametersGetter> Construct(uint id) => new FormLink<IReverbParametersGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IReverbParametersGetter> IntHighTechReverbLarge => Construct(0x23ab4d);
        public static FormLink<IReverbParametersGetter> IntFakeWoodSmall => Construct(0x239e65);
        public static FormLink<IReverbParametersGetter> IntFakeWoodMedium => Construct(0x239e64);
        public static FormLink<IReverbParametersGetter> IntFakeWoodLarge => Construct(0x239e63);
        public static FormLink<IReverbParametersGetter> IntFakeMetalSmall => Construct(0x239e62);
        public static FormLink<IReverbParametersGetter> IntFakeMetalMedium => Construct(0x239e61);
        public static FormLink<IReverbParametersGetter> IntFakeMetalLarge => Construct(0x239e60);
        public static FormLink<IReverbParametersGetter> IntFakeBrickLarge => Construct(0x239e59);
        public static FormLink<IReverbParametersGetter> IntFakeBrickMedium => Construct(0x239e58);
        public static FormLink<IReverbParametersGetter> IntFakeBrickSmall => Construct(0x239e57);
        public static FormLink<IReverbParametersGetter> IntIndustrialMediumReverb => Construct(0x239b34);
        public static FormLink<IReverbParametersGetter> IntSteamTunnelsRoomsReverb => Construct(0x239284);
        public static FormLink<IReverbParametersGetter> IntSteamTunnelsLargeReverb => Construct(0x239283);
        public static FormLink<IReverbParametersGetter> IntWoodLargeExtraReverb => Construct(0x238d08);
        public static FormLink<IReverbParametersGetter> IntWoodRoomsReverb => Construct(0x238d06);
        public static FormLink<IReverbParametersGetter> IntWoodMediumReverb => Construct(0x238d05);
        public static FormLink<IReverbParametersGetter> IntWoodLargeReverb => Construct(0x238d04);
        public static FormLink<IReverbParametersGetter> IntGenericCReverb => Construct(0x238cd4);
        public static FormLink<IReverbParametersGetter> IntIndustrialLargeExtraReverb => Construct(0x238cad);
        public static FormLink<IReverbParametersGetter> IntIndustrialLargeReverb => Construct(0x238bd6);
        public static FormLink<IReverbParametersGetter> IntIndustrialRoomsSmallReverb => Construct(0x238bd5);
        public static FormLink<IReverbParametersGetter> IntCaveLargeReverb => Construct(0x238bb1);
        public static FormLink<IReverbParametersGetter> IntCaveLargeExtraReverb => Construct(0x238a9b);
        public static FormLink<IReverbParametersGetter> IntCaveAReverb => Construct(0x238a9a);
        public static FormLink<IReverbParametersGetter> IntPrydwenAReverb => Construct(0x238a87);
        public static FormLink<IReverbParametersGetter> IntSteamTunnelsMediumReverb => Construct(0x238a80);
        public static FormLink<IReverbParametersGetter> IntNauticalRoomsSmallReverb => Construct(0x238a72);
        public static FormLink<IReverbParametersGetter> IntRoomWoodMediumReverb => Construct(0x2388e7);
        public static FormLink<IReverbParametersGetter> IntCaveSewerPipeReverb => Construct(0x231fac);
        public static FormLink<IReverbParametersGetter> IntHighTechRoomsReverb => Construct(0x2313d8);
        public static FormLink<IReverbParametersGetter> IntHighTechReverbMedium => Construct(0x2313d7);
        public static FormLink<IReverbParametersGetter> IntIndustrialRoomsReverb => Construct(0x22d145);
        public static FormLink<IReverbParametersGetter> IntIndustrialSaugusRoomsReverb => Construct(0x224d30);
        public static FormLink<IReverbParametersGetter> IntIndustrialSaugusReverb => Construct(0x224d2d);
        public static FormLink<IReverbParametersGetter> IntVaultGenericRoomSmallReverb => Construct(0x21812c);
        public static FormLink<IReverbParametersGetter> IntVaultGenericRoomLargeReverb => Construct(0x21812b);
        public static FormLink<IReverbParametersGetter> IntVaultGenericRoomMediumReverb => Construct(0x21812a);
        public static FormLink<IReverbParametersGetter> IntGenericBReverb => Construct(0x1ffc22);
        public static FormLink<IReverbParametersGetter> IntGenericAReverb => Construct(0x1ffc21);
        public static FormLink<IReverbParametersGetter> IntInstituteWingReverb => Construct(0x1f266b);
        public static FormLink<IReverbParametersGetter> IntInstituteTeleporterRoomReverb => Construct(0x1f086d);
        public static FormLink<IReverbParametersGetter> ExtCommonwealthInteriorReverbTEST => Construct(0x1e7709);
        public static FormLink<IReverbParametersGetter> IntSubwayTunnelsReverb => Construct(0x1e4f32);
        public static FormLink<IReverbParametersGetter> IntSubwayTrainReverb => Construct(0x1e4f31);
        public static FormLink<IReverbParametersGetter> IntSubwayRoomsReverb => Construct(0x1e4f30);
        public static FormLink<IReverbParametersGetter> IntVault111Reverb => Construct(0x9befe);
        public static FormLink<IReverbParametersGetter> IntChargenPodInt => Construct(0x19ece2);
        public static FormLink<IReverbParametersGetter> PowerArmorHelmetInterior => Construct(0x10df71);
        public static FormLink<IReverbParametersGetter> IntNauticalAReverb => Construct(0xf0504);
        public static FormLink<IReverbParametersGetter> ExtCommonwealthTEST => Construct(0x38c8b);
        public static FormLink<IReverbParametersGetter> IntRoomWoodLargeReverb => Construct(0xc5d09);
        public static FormLink<IReverbParametersGetter> DefaultReverb => Construct(0xc5b6e);
        public static FormLink<IReverbParametersGetter> IntRoomStoneMediumReverb => Construct(0xc5b6c);
        public static FormLink<IReverbParametersGetter> IntRoomWoodRoomsReverb => Construct(0xc5b6a);
        public static FormLink<IReverbParametersGetter> IntRoomStoneNarrow => Construct(0xe322e);
        public static FormLink<IReverbParametersGetter> Underwater => Construct(0x97608);
        public static FormLink<IReverbParametersGetter> IntRoomStoneLargeReverb => Construct(0xe3246);
        public static FormLink<IReverbParametersGetter> IntMQ203KelloggsBrain => Construct(0xfd92a);
        public static FormLink<IReverbParametersGetter> IntRoomStoneLargeExtraReverb => Construct(0x1079e9);
    }
}
